//-------------------------------------------------------
// Autogenerated from 'ammo_cabinet.vmf'
//-------------------------------------------------------
AmmoCabinet <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.prop_ammo,
			EntityGroup.SpawnTables.ammo_explosive,
			EntityGroup.SpawnTables.button,
			EntityGroup.SpawnTables.cabinet,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.usetarget,
			EntityGroup.SpawnTables.template_ammo,
			EntityGroup.SpawnTables.cabinet,
			EntityGroup.SpawnTables.button,
			EntityGroup.SpawnTables.prop_ammo,
			EntityGroup.SpawnTables.relay_ammo_restock,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			prop_ammo = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/w_models/weapons/w_eq_explosive_ammopack.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "prop_ammo"
					updatechildren = "0"
					origin = Vector( -1, 2, -8.4368 )
				}
			}
			ammo_explosive = 
			{
				SpawnInfo =
				{
					classname = "weapon_upgradepack_explosive_spawn"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disableshadows = "0"
					model = "models/w_models/weapons/w_eq_explosive_ammopack.mdl"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "ammo_explosive"
					origin = Vector( -1, 2, -8.4368 )
				}
			}
			template_ammo = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "2"
					targetname = "template_ammo"
					Template02 = "ammo_explosive"
					origin = Vector( 15, 16, -33 )
				}
			}
			relay_ammo_restock = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "1"
					StartDisabled = "0"
					targetname = "relay_ammo_restock"
					origin = Vector( 15, -16, -33 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "template_ammoForceSpawn0-1"
							cmd2 = "prop_ammoDisable0-1"
							cmd3 = "cabinetSetAnimationopen0-1"
							cmd4 = "template_ammoKill0.1-1"
						}
					}
				}
			}
			usetarget = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "button"
					origin = Vector( 15, -1, -33 )
					targetname = "usetarget"
					vscripts = "usetargets/emergency_ammo"
					connections =
					{
						OnUser1 =
						{
							cmd1 = "!selfKill0.2-1"
							cmd2 = "!selfDisable0.1-1"
							cmd3 = "!selflock0-1"
							cmd4 = "relay_ammo_restockTrigger0-1"
						}
					}
				}
			}
			button = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "121 202 0"
					glowrange = "120"
					glowrangemin = "0"
					glowstate = "3"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/buildable_button.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "button"
					updatechildren = "0"
					origin = Vector( 0, -1.90735e-006, -22 )
				}
			}
			cabinet = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/small_cabinet_ammo.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "cabinet"
					updatechildren = "0"
					origin = Vector( 0, 0, -9 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // AmmoCabinet

RegisterEntityGroup( "AmmoCabinet", AmmoCabinet )
