//-------------------------------------------------------
// Autogenerated from 'blocknav128.vmf'
//-------------------------------------------------------
Blocknav128 <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.attrib,
			EntityGroup.SpawnTables.nav_blocker,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "logic_auto"
					spawnflags = "1"
					origin = Vector( 0, 0, 48 )
					connections =
					{
						OnMapSpawn =
						{
							cmd1 = "nav_blockerBlockNav0-1"
							cmd2 = "attribKill2-1"
						}
					}
				}
			}
			nav_blocker = 
			{
				SpawnInfo =
				{
					classname = "script_nav_blocker"
					affectsFlow = "1"
					targetname = "nav_blocker"
					teamToBlock = "-1"
					extent = Vector( 64, 64, 32 )
					origin = Vector( 0, 0, 32 )
				}
			}
			attrib = 
			{
				SpawnInfo =
				{
					classname = "point_nav_attribute_region"
					maxs = "64 64 16"
					mins = "-64 -64 -16"
					spawnflags = "8194"
					targetname = "attrib"
					origin = Vector( 0, 0, 16 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // Blocknav128

RegisterEntityGroup( "Blocknav128", Blocknav128 )
