//-------------------------------------------------------
// Autogenerated from 'buildable_ladder.vmf'
//-------------------------------------------------------
BuildableLadder <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.ranchhouse_ladder_1_model,
			EntityGroup.SpawnTables.button_ranchhouse_ladder,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.ranchhouse_ladder_1_spawn_timer,
			EntityGroup.SpawnTables.ranchhouse_ladder_1_nav_blocker,
			EntityGroup.SpawnTables.ranchhouse_ladder_1,
			EntityGroup.SpawnTables.usetarget_ranchhouse_ladder,
			EntityGroup.SpawnTables.ranchhouse_ladder_1_model,
			EntityGroup.SpawnTables.button_ranchhouse_ladder,
			EntityGroup.SpawnTables.ranchhouse_ladder_1_spawn_trigger,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			ranchhouse_ladder_1_model = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( -15, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props/de_train/ladderaluminium.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "ranchhouse_ladder_1_model"
					updatechildren = "0"
					origin = Vector( 18.8695, -0.280998, -3.8486 )
				}
			}
			ranchhouse_ladder_1 = 
			{
				SpawnInfo =
				{
					classname = "func_brush"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					InputFilter = "0"
					invert_exclusion = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					origin = Vector( 23.72, -0.28, -7.79 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					solidbsp = "0"
					Solidity = "0"
					spawnflags = "2"
					StartDisabled = "1"
					targetname = "ranchhouse_ladder_1"
					vrad_brush_cast_shadows = "0"
				}
			}
			ranchhouse_ladder_1_nav_blocker = 
			{
				SpawnInfo =
				{
					classname = "script_nav_blocker"
					affectsFlow = "1"
					StartDisabled = "0"
					targetname = "ranchhouse_ladder_1_nav_blocker"
					teamToBlock = "-1"
					extent = Vector( 31.99998, 16, 82.0002 )
					origin = Vector( 28.00052, 0, -1.10019999999999 )
				}
			}
			ranchhouse_ladder_1_spawn_trigger = 
			{
				SpawnInfo =
				{
					classname = "script_trigger_multiple"
					allowghost = "0"
					allowincap = "0"
					entireteam = "0"
					filtername = "@survivor_filter"
					origin = Vector( 28, 0, -1.1 )
					spawnflags = "1"
					StartDisabled = "0"
					targetname = "ranchhouse_ladder_1_spawn_trigger"
					wait = "0"
					extent = Vector( 30.00095, 16, 82.0002 )
					connections =
					{
						OnNotTouching =
						{
							cmd1 = "ranchhouse_ladder_1Enable01"
							cmd2 = "ranchhouse_ladder_1_spawn_timerKill01"
							cmd3 = "ranchhouse_ladder_1_nav_blockerUnblockNav0.11"
							cmd4 = "ranchhouse_ladder_1_modelEnable01"
						}
					}
				}
			}
			ranchhouse_ladder_1_spawn_timer = 
			{
				SpawnInfo =
				{
					classname = "logic_timer"
					RefireTime = ".3"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "ranchhouse_ladder_1_spawn_timer"
					origin = Vector( 10.9205, -25, -73.0878 )
					connections =
					{
						OnTimer =
						{
							cmd1 = "ranchhouse_ladder_1_spawn_triggerTouchTest0-1"
						}
					}
				}
			}
			button_ranchhouse_ladder = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( -90, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "194 223 94"
					glowrange = "300"
					glowrangemin = "0"
					glowstate = "3"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props/de_train/ladderaluminium.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "2"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "button_ranchhouse_ladder"
					updatechildren = "0"
					origin = Vector( 82.0005, -89.6867, -83 )
				}
			}
			usetarget_ranchhouse_ladder = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "button_ranchhouse_ladder"
					origin = Vector( 92.63, -56.58, -76 )
					targetname = "usetarget_ranchhouse_ladder"
					vscripts = "usetargets/ladder_free"
					connections =
					{
						OnUser1 =
						{
							cmd1 = "!selfKill0.21"
							cmd2 = "!selfDisable0.11"
							cmd3 = "ranchhouse_ladder_1_spawn_timerEnable01"
							cmd4 = "button_ranchhouse_ladderKill0.21"
						}
					}
				}
			}
		} // SpawnTables
	} // EntityGroup
} // BuildableLadder

RegisterEntityGroup( "BuildableLadder", BuildableLadder )
