//-------------------------------------------------------
// Autogenerated from 'buildable_minigun.vmf'
//-------------------------------------------------------
BuildableMinigun <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.minigun_1,
			EntityGroup.SpawnTables.button,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.use_target,
			EntityGroup.SpawnTables.minigun_1_template,
			EntityGroup.SpawnTables.button,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			minigun_1 = 
			{
				SpawnInfo =
				{
					classname = "prop_minigun"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "2300"
					fademindist = "2200"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MaxPitch = "40"
					MaxYaw = "80"
					MinAnimTime = "5"
					MinPitch = "-30"
					model = "models/w_models/weapons/50cal.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "minigun_1"
					origin = Vector( 0, 0, 0 )
				}
			}
			minigun_1_template = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "2"
					targetname = "minigun_1_template"
					Template01 = "minigun_1"
					origin = Vector( -26, 0, 18 )
				}
			}
			use_target = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "button"
					origin = Vector( -24, 9, 27.85 )
					targetname = "use_target"
					vscripts = "usetargets/minigun"
					connections =
					{
						OnUser1 =
						{
							cmd1 = "minigun_1_templateForceSpawn0-1"
							cmd2 = "buttonKill0-1"
							cmd3 = "use_targetKill0-1"
						}
					}
				}
			}
			button = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "2300"
					fademindist = "2200"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "168 0 0"
					glowrange = "480"
					glowstate = "3"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/w_models/weapons/50_cal_broken.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "button"
					origin = Vector( 0, 0, 0 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // BuildableMinigun

RegisterEntityGroup( "BuildableMinigun", BuildableMinigun )
