//-------------------------------------------------------
// Autogenerated from 'c4m1_milltown_a_zombiehouse.vmf'
//-------------------------------------------------------
C4m1MilltownAZombiehouse <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.zombiehouse_panel_1,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.zombiehouse_doorbreak_blood_1,
			EntityGroup.SpawnTables.zombiehouse_spawn_unique_2,
			EntityGroup.SpawnTables.zombiehouse_front_nav_blocker1,
			EntityGroup.SpawnTables.zombiehouse_front_nav_blocker,
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.zombiehouse_spawn_specials,
			EntityGroup.SpawnTables.nav_blocker1,
			EntityGroup.SpawnTables.nav_blocker,
			EntityGroup.SpawnTables.zombiehouse_panel_trigger,
			EntityGroup.SpawnTables.zombiehouse_spawn_six4,
			EntityGroup.SpawnTables.zombiehouse_spawn_six3,
			EntityGroup.SpawnTables.zombiehouse_spawn_six2,
			EntityGroup.SpawnTables.zombiehouse_spawn_six1,
			EntityGroup.SpawnTables.zombiehouse_spawn_six,
			EntityGroup.SpawnTables.zombiehouse_panel_1,
			EntityGroup.SpawnTables.zombiehouse_spawn_unique_1,
			EntityGroup.SpawnTables.zombiehouse_spawn_four3,
			EntityGroup.SpawnTables.zombiehouse_spawn_four2,
			EntityGroup.SpawnTables.zombiehouse_spawn_four1,
			EntityGroup.SpawnTables.zombiehouse_spawn_four,
			EntityGroup.SpawnTables.zombiehouse_doorbreak_smoke_1,
			EntityGroup.SpawnTables.attrib1,
			EntityGroup.SpawnTables.attrib,
			EntityGroup.SpawnTables.zombiehouse_doorbreak_sound,
			EntityGroup.SpawnTables.zombiehouse_preparehouse_relay,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "logic_auto"
					spawnflags = "1"
					origin = Vector( 1216, 6336, 192 )
					connections =
					{
						OnMapSpawn =
						{
							cmd1 = "zombiehouse_front_nav_blockerBlockNav0-1"
							cmd2 = "attribKill2-1"
							cmd3 = "nav_blockerBlockNav0-1"
						}
					}
				}
			}
			zombiehouse_panel_1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 90, 0, 0 )
					disableshadows = "1"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "255 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_highway/corrugated_panel_04.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "zombiehouse_panel_1"
					origin = Vector( 1140, 6224, 117.176 )
				}
			}
			zombiehouse_preparehouse_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "@zombiehouse_preparehouse_relay"
					origin = Vector( 1232, 6336, 195.281 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "zombiehouse_panel_triggerEnable0-1"
							cmd2 = "zombiehouse_front_nav_blockerUnblockNav0-1"
							cmd3 = "zombiehouse_panel_1StartGlowing0-1"
							cmd4 = "zombiehouse_spawn_specialsTrigger01"
						}
					}
				}
			}
			zombiehouse_front_nav_blocker = 
			{
				SpawnInfo =
				{
					classname = "script_nav_blocker"
					affectsFlow = "1"
					targetname = "zombiehouse_front_nav_blocker"
					teamToBlock = "-1"
					extent = Vector( 78, 194, 32 )
					origin = Vector( 1226, 6262, 151 )
				}
			}
			nav_blocker = 
			{
				SpawnInfo =
				{
					classname = "script_nav_blocker"
					affectsFlow = "1"
					targetname = "nav_blocker"
					teamToBlock = "-1"
					extent = Vector( 74, 218, 32 )
					origin = Vector( 1378, 6442, 151 )
				}
			}
			attrib = 
			{
				SpawnInfo =
				{
					classname = "point_nav_attribute_region"
					maxs = "74 218 16"
					mins = "-74 -218 -16"
					spawnflags = "8194"
					targetname = "attrib"
					origin = Vector( 1378, 6442, 135.273 )
				}
			}
			nav_blocker1 = 
			{
				SpawnInfo =
				{
					classname = "script_nav_blocker"
					affectsFlow = "1"
					targetname = "nav_blocker"
					teamToBlock = "-1"
					extent = Vector( 78, 98, 32 )
					origin = Vector( 1226, 6562, 151 )
				}
			}
			attrib1 = 
			{
				SpawnInfo =
				{
					classname = "point_nav_attribute_region"
					maxs = "78 98 16"
					mins = "-78 -98 -16"
					spawnflags = "8194"
					targetname = "attrib"
					origin = Vector( 1226, 6562, 135.273 )
				}
			}
			zombiehouse_front_nav_blocker1 = 
			{
				SpawnInfo =
				{
					classname = "script_nav_blocker"
					affectsFlow = "1"
					targetname = "zombiehouse_front_nav_blocker"
					teamToBlock = "-1"
					extent = Vector( 74, 74, 32 )
					origin = Vector( 1378, 6142, 151 )
				}
			}
			zombiehouse_doorbreak_blood_1 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "boomer_explode"
					render_in_front = "0"
					start_active = "0"
					targetname = "zombiehouse_doorbreak_blood_1"
					origin = Vector( 1152, 6256, 128 )
				}
			}
			zombiehouse_doorbreak_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "WoodenDoor.Break"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "0"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "zombiehouse_doorbreak_sound"
					volstart = "0"
					origin = Vector( 1140, 6256, 184.708 )
				}
			}
			zombiehouse_doorbreak_smoke_1 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( -90, 90, 0 )
					effect_name = "aircraft_destroy_fb_smoke1"
					targetname = "zombiehouse_doorbreak_smoke_1"
					origin = Vector( 1132, 6256, 144 )
				}
			}
			zombiehouse_spawn_six = 
			{
				SpawnInfo =
				{
					classname = "commentary_zombie_spawner"
					angles = Vector( 0, 105, 0 )
					targetname = "zombiehouse_spawn_six"
					origin = Vector( 1288, 6168, 120 )
				}
			}
			zombiehouse_spawn_specials = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "zombiehouse_spawn_specials"
					origin = Vector( 1253.82, 6300.46, 192 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "zombiehouse_spawn_sixSpawnZombiecommon_male_clown0-1"
							cmd2 = "zombiehouse_spawn_fourSpawnZombiecommon_male_clown0-1"
							cmd3 = "zombiehouse_spawn_unique_2SpawnZombiecommon_male_fallen_survivor0-1"
							cmd4 = "zombiehouse_spawn_unique_1SpawnZombiecommon_male_clown0-1"
						}
					}
				}
			}
			zombiehouse_spawn_six1 = 
			{
				SpawnInfo =
				{
					classname = "commentary_zombie_spawner"
					angles = Vector( 0, 90, 0 )
					targetname = "zombiehouse_spawn_six"
					origin = Vector( 1256, 6116, 120 )
				}
			}
			zombiehouse_spawn_six2 = 
			{
				SpawnInfo =
				{
					classname = "commentary_zombie_spawner"
					angles = Vector( 0, 270, 0 )
					targetname = "zombiehouse_spawn_six"
					origin = Vector( 1232, 6380, 120 )
				}
			}
			zombiehouse_spawn_six3 = 
			{
				SpawnInfo =
				{
					classname = "commentary_zombie_spawner"
					angles = Vector( 0, 270, 0 )
					targetname = "zombiehouse_spawn_six"
					origin = Vector( 1180, 6388, 120 )
				}
			}
			zombiehouse_spawn_six4 = 
			{
				SpawnInfo =
				{
					classname = "commentary_zombie_spawner"
					angles = Vector( 0, 270, 0 )
					targetname = "zombiehouse_spawn_six"
					origin = Vector( 1188, 6428, 120 )
				}
			}
			zombiehouse_spawn_four = 
			{
				SpawnInfo =
				{
					classname = "commentary_zombie_spawner"
					angles = Vector( 0, 90, 0 )
					targetname = "zombiehouse_spawn_four"
					origin = Vector( 1280, 6088, 120 )
				}
			}
			zombiehouse_spawn_four1 = 
			{
				SpawnInfo =
				{
					classname = "commentary_zombie_spawner"
					angles = Vector( 0, 90, 0 )
					targetname = "zombiehouse_spawn_four"
					origin = Vector( 1276, 6140, 120 )
				}
			}
			zombiehouse_spawn_four2 = 
			{
				SpawnInfo =
				{
					classname = "commentary_zombie_spawner"
					angles = Vector( 0, 270, 0 )
					targetname = "zombiehouse_spawn_four"
					origin = Vector( 1244, 6428, 120 )
				}
			}
			zombiehouse_spawn_four3 = 
			{
				SpawnInfo =
				{
					classname = "commentary_zombie_spawner"
					angles = Vector( 0, 270, 0 )
					targetname = "zombiehouse_spawn_four"
					origin = Vector( 1280, 6396, 120 )
				}
			}
			zombiehouse_spawn_unique_1 = 
			{
				SpawnInfo =
				{
					classname = "commentary_zombie_spawner"
					angles = Vector( 0, 90, 0 )
					targetname = "zombiehouse_spawn_unique_1"
					origin = Vector( 1240, 6172, 120 )
				}
			}
			zombiehouse_panel_trigger = 
			{
				SpawnInfo =
				{
					classname = "script_trigger_once"
					origin = Vector( 1160, 6256, 181.18 )
					spawnflags = "3"
					StartDisabled = "0"
					targetname = "zombiehouse_panel_trigger"
					extent = Vector( 12, 32, 66 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "zombiehouse_panel_1Kill0-1"
							cmd2 = "zombiehouse_doorbreak_smoke_1Start0-1"
							cmd3 = "zombiehouse_doorbreak_blood_1Start0-1"
							cmd4 = "zombiehouse_doorbreak_soundPlaySound0-1"
							cmd5 = "zombiehouse_doorbreak_blood_1Stop5-1"
							cmd6 = "zombiehouse_doorbreak_blood_1Kill6-1"
						}
					}
				}
			}
			zombiehouse_spawn_unique_2 = 
			{
				SpawnInfo =
				{
					classname = "commentary_zombie_spawner"
					angles = Vector( 0, 195, 0 )
					targetname = "zombiehouse_spawn_unique_2"
					origin = Vector( 1268, 6248, 120 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // C4m1MilltownAZombiehouse

RegisterEntityGroup( "C4m1MilltownAZombiehouse", C4m1MilltownAZombiehouse )
