//-------------------------------------------------------
// Autogenerated from 'carnivalgame_stachewhacker.vmf'
//-------------------------------------------------------
CarnivalgameStachewhacker <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.plunger_1_target,
			EntityGroup.SpawnTables.plunger_4_target,
			EntityGroup.SpawnTables.plunger_3_target,
			EntityGroup.SpawnTables.plunger_2_target,
			EntityGroup.SpawnTables.plunger_5_target,
			EntityGroup.SpawnTables.game_start_button_model,
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.unnamed1,
			EntityGroup.SpawnTables.unnamed2,
			EntityGroup.SpawnTables.unnamed3,
			EntityGroup.SpawnTables.unnamed4,
			EntityGroup.SpawnTables.wam_continue_sign,
			EntityGroup.SpawnTables.wam_animated_sign,
			EntityGroup.SpawnTables.wam_glass_intact,
			EntityGroup.SpawnTables.wam_glass_broken,
			EntityGroup.SpawnTables.wam_game_start_button,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.fx_boom2,
			EntityGroup.SpawnTables.fx_smoke,
			EntityGroup.SpawnTables.fx_ticket_jackpot,
			EntityGroup.SpawnTables.timer_0,
			EntityGroup.SpawnTables.plunger_4,
			EntityGroup.SpawnTables.fx_smoke_target_3,
			EntityGroup.SpawnTables.wam_animated_sign,
			EntityGroup.SpawnTables.fx_sparks3,
			EntityGroup.SpawnTables.fx_sparks2,
			EntityGroup.SpawnTables.fx_sparks1,
			EntityGroup.SpawnTables.fx_sparks,
			EntityGroup.SpawnTables.fx_smoke_target_4,
			EntityGroup.SpawnTables.game_start_button_model,
			EntityGroup.SpawnTables.plunger_3,
			EntityGroup.SpawnTables.wam_low_score_sound,
			EntityGroup.SpawnTables.fx_smoke_target_1,
			EntityGroup.SpawnTables.wam_continue_sign,
			EntityGroup.SpawnTables.fx_smoke_target_2,
			EntityGroup.SpawnTables.wam_game_start_sound,
			EntityGroup.SpawnTables.wam_game_start_button,
			EntityGroup.SpawnTables.wam_point_score_sound,
			EntityGroup.SpawnTables.game_start_button,
			EntityGroup.SpawnTables.timer_script,
			EntityGroup.SpawnTables.counter_1,
			EntityGroup.SpawnTables.wam_game_countdown_sound,
			EntityGroup.SpawnTables.wam_achievement_event,
			EntityGroup.SpawnTables.wam_game_over_sound,
			EntityGroup.SpawnTables.plunger_5,
			EntityGroup.SpawnTables.plunger_2,
			EntityGroup.SpawnTables.plunger_1,
			EntityGroup.SpawnTables.end_game_rl,
			EntityGroup.SpawnTables.wam_damage_filter_multi,
			EntityGroup.SpawnTables.counter_script,
			EntityGroup.SpawnTables.wam_game_music,
			EntityGroup.SpawnTables.plunger_5_target,
			EntityGroup.SpawnTables.wam_bullet_filter,
			EntityGroup.SpawnTables.wam_animated_sign_timer,
			EntityGroup.SpawnTables.timer_1,
			EntityGroup.SpawnTables.wam_break_machine_rl,
			EntityGroup.SpawnTables.timer_2,
			EntityGroup.SpawnTables.wam_target_surprise_sound,
			EntityGroup.SpawnTables.fx_boom13,
			EntityGroup.SpawnTables.fx_boom12,
			EntityGroup.SpawnTables.fx_boom11,
			EntityGroup.SpawnTables.fx_boom1,
			EntityGroup.SpawnTables.plunger_4_target,
			EntityGroup.SpawnTables.plunger_2_target,
			EntityGroup.SpawnTables.wam_continue_relay,
			EntityGroup.SpawnTables.wam_glass_broken,
			EntityGroup.SpawnTables.plunger_1_target,
			EntityGroup.SpawnTables.wam_glass_intact,
			EntityGroup.SpawnTables.unnamed4,
			EntityGroup.SpawnTables.unnamed3,
			EntityGroup.SpawnTables.unnamed2,
			EntityGroup.SpawnTables.unnamed1,
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.wam_target_hit_sound,
			EntityGroup.SpawnTables.stachewhacker_usetarget,
			EntityGroup.SpawnTables.plunger_3_target,
			EntityGroup.SpawnTables.fx_ticket_single,
			EntityGroup.SpawnTables.counter_0,
			EntityGroup.SpawnTables.wam_high_score_sound,
			EntityGroup.SpawnTables.wam_melee_filter,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			counter_0 = 
			{
				SpawnInfo =
				{
					classname = "momentary_rot_button"
					_minlight = "1"
					angles = Vector( 0, 0, 0 )
					distance = "360"
					fademindist = "-1"
					fadescale = "1"
					origin = Vector( -5, 25, 41 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					returnspeed = "0"
					sounds = "0"
					spawnflags = "161"
					speed = "10000"
					startdirection = "1"
					targetname = "counter_0"
				}
			}
			counter_1 = 
			{
				SpawnInfo =
				{
					classname = "momentary_rot_button"
					_minlight = "1"
					angles = Vector( 0, 0, 0 )
					distance = "360"
					fademindist = "-1"
					fadescale = "1"
					origin = Vector( -5, 19.5, 41 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					returnspeed = "0"
					sounds = "0"
					spawnflags = "161"
					speed = "10000"
					startdirection = "1"
					targetname = "counter_1"
				}
			}
			plunger_1 = 
			{
				SpawnInfo =
				{
					classname = "func_door"
					disablereceiveshadows = "0"
					disableshadows = "0"
					dmg = "0"
					fademindist = "-1"
					fadescale = "1"
					forceclosed = "0"
					health = "0"
					ignoredebris = "0"
					lip = "-28"
					locked_sentence = "0"
					loopmovesound = "0"
					movedir = "-90 0 0"
					noise1 = "WAM.popUp"
					origin = Vector( 35, -10, 10 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					spawnflags = "1064"
					spawnpos = "0"
					speed = "100"
					targetname = "plunger_1"
					unlocked_sentence = "0"
					wait = "4"
					connections =
					{
						OnFullyOpen =
						{
							cmd1 = "!selfClose0.5-1"
						}
						OnOpen =
						{
							cmd1 = "wam_target_surprise_soundPlaySound0-1"
						}
						OnFullyClosed =
						{
							cmd1 = "counter_scriptRunscriptcodeClearHitTargetOne()0-1"
						}
					}
				}
			}
			plunger_4 = 
			{
				SpawnInfo =
				{
					classname = "func_door"
					disablereceiveshadows = "0"
					disableshadows = "0"
					dmg = "0"
					fademindist = "-1"
					fadescale = "1"
					forceclosed = "0"
					health = "0"
					ignoredebris = "0"
					lip = "-28"
					locked_sentence = "0"
					loopmovesound = "0"
					movedir = "-90 0 0"
					noise1 = "WAM.popUp"
					origin = Vector( 16, 0, 10 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					spawnflags = "1056"
					spawnpos = "0"
					speed = "100"
					targetname = "plunger_4"
					unlocked_sentence = "0"
					wait = "4"
					connections =
					{
						OnFullyOpen =
						{
							cmd1 = "!selfClose0.5-1"
						}
						OnOpen =
						{
							cmd1 = "wam_target_surprise_soundPlaySound0-1"
						}
						OnFullyClosed =
						{
							cmd1 = "counter_scriptRunscriptcodeClearHitTargetFour()0-1"
						}
					}
				}
			}
			plunger_3 = 
			{
				SpawnInfo =
				{
					classname = "func_door"
					disablereceiveshadows = "0"
					disableshadows = "0"
					dmg = "0"
					fademindist = "-1"
					fadescale = "1"
					forceclosed = "0"
					health = "0"
					ignoredebris = "0"
					lip = "-28"
					locked_sentence = "0"
					loopmovesound = "0"
					movedir = "-90 0 0"
					noise1 = "WAM.popUp"
					origin = Vector( 16, -19, 10 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					spawnflags = "1056"
					spawnpos = "0"
					speed = "100"
					targetname = "plunger_3"
					unlocked_sentence = "0"
					wait = "4"
					connections =
					{
						OnFullyOpen =
						{
							cmd1 = "!selfClose0.5-1"
						}
						OnOpen =
						{
							cmd1 = "wam_target_surprise_soundPlaySound0-1"
						}
						OnFullyClosed =
						{
							cmd1 = "counter_scriptRunscriptcodeClearHitTargetThree()0-1"
						}
					}
				}
			}
			plunger_2 = 
			{
				SpawnInfo =
				{
					classname = "func_door"
					disablereceiveshadows = "0"
					disableshadows = "0"
					dmg = "0"
					fademindist = "-1"
					fadescale = "1"
					forceclosed = "0"
					health = "0"
					ignoredebris = "0"
					lip = "-28"
					locked_sentence = "0"
					loopmovesound = "0"
					movedir = "-90 0 0"
					noise1 = "WAM.popUp"
					origin = Vector( 35, 10, 10 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					spawnflags = "1056"
					spawnpos = "0"
					speed = "100"
					targetname = "plunger_2"
					unlocked_sentence = "0"
					wait = "4"
					connections =
					{
						OnFullyOpen =
						{
							cmd1 = "!selfClose0.5-1"
						}
						OnOpen =
						{
							cmd1 = "wam_target_surprise_soundPlaySound0-1"
						}
						OnFullyClosed =
						{
							cmd1 = "counter_scriptRunscriptcodeClearHitTargetTwo()0-1"
						}
					}
				}
			}
			plunger_5 = 
			{
				SpawnInfo =
				{
					classname = "func_door"
					disablereceiveshadows = "0"
					disableshadows = "0"
					dmg = "0"
					fademindist = "-1"
					fadescale = "1"
					forceclosed = "0"
					health = "0"
					ignoredebris = "0"
					lip = "-28"
					locked_sentence = "0"
					loopmovesound = "0"
					movedir = "-90 0 0"
					noise1 = "WAM.popUp"
					origin = Vector( 16, 20, 10 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					spawnflags = "1056"
					spawnpos = "0"
					speed = "100"
					targetname = "plunger_5"
					unlocked_sentence = "0"
					wait = "4"
					connections =
					{
						OnFullyOpen =
						{
							cmd1 = "!selfClose0.5-1"
						}
						OnOpen =
						{
							cmd1 = "wam_target_surprise_soundPlaySound0-1"
						}
						OnFullyClosed =
						{
							cmd1 = "counter_scriptRunscriptcodeClearHitTargetFive()0-1"
						}
					}
				}
			}
			timer_script = 
			{
				SpawnInfo =
				{
					classname = "logic_script"
					Group00 = "timer_0"
					Group01 = "timer_1"
					Group02 = "timer_2"
					Group03 = "plunger_1"
					Group04 = "plunger_2"
					Group05 = "plunger_3"
					Group06 = "plunger_4"
					Group07 = "plunger_5"
					targetname = "timer_script"
					thinkfunction = "Think"
					vscripts = "whacker_timer"
					origin = Vector( 15, -22, 61 )
					connections =
					{
						OnUser1 =
						{
							cmd1 = "end_game_rlTrigger0-1"
						}
					}
				}
			}
			counter_script = 
			{
				SpawnInfo =
				{
					classname = "logic_script"
					Group00 = "counter_0"
					Group01 = "counter_1"
					Group02 = "wam_high_score_sound"
					Group04 = "wam_point_score_sound"
					Group05 = "wam_break_machine_rl"
					Group06 = "fx_ticket_single"
					targetname = "counter_script"
					thinkfunction = "Think"
					vscripts = "whacker_counter"
					origin = Vector( 15, 21, 61 )
					connections =
					{
						OnUser2 =
						{
							cmd1 = "wam_low_score_soundPlaySound0-1"
						}
						OnUser1 =
						{
							cmd1 = "wam_high_score_soundPlaySound0-1"
						}
					}
				}
			}
			plunger_1_target = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 0, 0, 0 )
					damagefilter = "wam_damage_filter_multi"
					disableshadows = "1"
					fademaxdist = "600"
					fademindist = "500"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					health = "0"
					LagCompensate = "1"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_fairgrounds/mr_mustachio.mdl"
					parentname = "plunger_1"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "plunger_1_target"
					origin = Vector( 35, -10, 8.0188 )
					connections =
					{
						OnTakeDamage =
						{
							cmd1 = "counter_scriptRunscriptcodeScoreHitTargetOne()0-1"
							cmd2 = "wam_target_hit_soundPlaySound0.2-1"
						}
					}
				}
			}
			plunger_4_target = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 0, 0, 0 )
					damagefilter = "wam_damage_filter_multi"
					disableshadows = "1"
					fademaxdist = "600"
					fademindist = "500"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					health = "0"
					LagCompensate = "1"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_fairgrounds/mr_mustachio.mdl"
					parentname = "plunger_4"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "plunger_4_target"
					origin = Vector( 16, 0, 8.0188 )
					connections =
					{
						OnTakeDamage =
						{
							cmd1 = "counter_scriptRunscriptcodeScoreHitTargetFour()0-1"
							cmd2 = "wam_target_hit_soundPlaySound0.2-1"
						}
					}
				}
			}
			plunger_3_target = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 0, 0, 0 )
					damagefilter = "wam_damage_filter_multi"
					disableshadows = "1"
					fademaxdist = "600"
					fademindist = "500"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					health = "0"
					LagCompensate = "1"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_fairgrounds/mr_mustachio.mdl"
					parentname = "plunger_3"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "plunger_3_target"
					origin = Vector( 16, -19, 8.0188 )
					connections =
					{
						OnTakeDamage =
						{
							cmd1 = "counter_scriptRunscriptcodeScoreHitTargetThree()0-1"
							cmd2 = "wam_target_hit_soundPlaySound0.2-1"
						}
					}
				}
			}
			plunger_2_target = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 0, 0, 0 )
					damagefilter = "wam_damage_filter_multi"
					disableshadows = "1"
					fademaxdist = "600"
					fademindist = "500"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					health = "0"
					LagCompensate = "1"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_fairgrounds/mr_mustachio.mdl"
					parentname = "plunger_2"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "plunger_2_target"
					origin = Vector( 35, 10, 8.0188 )
					connections =
					{
						OnTakeDamage =
						{
							cmd1 = "counter_scriptRunscriptcodeScoreHitTargetTwo()0-1"
							cmd2 = "wam_target_hit_soundPlaySound0.2-1"
						}
					}
				}
			}
			plunger_5_target = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 0, 0, 0 )
					damagefilter = "wam_damage_filter_multi"
					disableshadows = "1"
					fademaxdist = "600"
					fademindist = "500"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					health = "0"
					LagCompensate = "1"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_fairgrounds/mr_mustachio.mdl"
					parentname = "plunger_5"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "plunger_5_target"
					origin = Vector( 16, 20, 8.0188 )
					connections =
					{
						OnTakeDamage =
						{
							cmd1 = "counter_scriptRunscriptcodeScoreHitTargetFive()0-1"
							cmd2 = "wam_target_hit_soundPlaySound0.2-1"
						}
					}
				}
			}
			end_game_rl = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "end_game_rl"
					origin = Vector( 9, 13, 70 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "game_start_buttonenable3-1"
							cmd2 = "game_start_button_modelSetAnimationidle_off3-1"
							cmd3 = "wam_continue_relayTrigger3-1"
							cmd4 = "wam_low_score_soundPlaySound0-1"
							cmd5 = "wam_game_musicFadeOut10-1"
						}
					}
				}
			}
			game_start_button_model = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowstate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_fairgrounds/arcadegame01.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "game_start_button_model"
					updatechildren = "0"
					origin = Vector( -19, -32, 0 )
				}
			}
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					disableshadows = "1"
					fademaxdist = "600"
					fademindist = "500"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_fairgrounds/arcadegame01_wheel.mdl"
					parentname = "timer_2"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					origin = Vector( -14, -30, 32 )
				}
			}
			unnamed1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					disableshadows = "1"
					fademaxdist = "600"
					fademindist = "500"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_fairgrounds/arcadegame01_wheel.mdl"
					parentname = "timer_1"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					origin = Vector( -14, -25, 32 )
				}
			}
			unnamed2 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					disableshadows = "1"
					fademaxdist = "600"
					fademindist = "500"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_fairgrounds/arcadegame01_wheel.mdl"
					parentname = "timer_0"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					origin = Vector( -14, -19, 32 )
				}
			}
			unnamed3 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					disableshadows = "1"
					fademaxdist = "600"
					fademindist = "500"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_fairgrounds/arcadegame01_wheel.mdl"
					parentname = "counter_1"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					origin = Vector( -14, 17, 32 )
				}
			}
			unnamed4 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					disableshadows = "1"
					fademaxdist = "600"
					fademindist = "500"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_fairgrounds/arcadegame01_wheel.mdl"
					parentname = "counter_0"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					origin = Vector( -14, 22, 32 )
				}
			}
			wam_game_music = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					fadeoutsecs = "1"
					health = "10"
					message = "WAM.Music"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					spindown = "0"
					targetname = "wam_game_music"
					origin = Vector( -14, 1, 72 )
				}
			}
			wam_game_start_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "WAM.StartUp"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "wam_game_start_sound"
					origin = Vector( 41, 1, 44 )
				}
			}
			wam_high_score_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "WAM.HighScore"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "wam_high_score_sound"
					origin = Vector( 2, -7, 71 )
				}
			}
			wam_point_score_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "WAM.PointScored"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "wam_point_score_sound"
					origin = Vector( 10, 22, 50 )
				}
			}
			wam_melee_filter = 
			{
				SpawnInfo =
				{
					classname = "filter_melee_damage"
					damagetype = "0"
					Negated = "0"
					targetname = "@wam_melee_filter"
					origin = Vector( 34, 1, 55 )
				}
			}
			wam_continue_sign = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					disableshadows = "1"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_fairgrounds/arcadegame01_screen.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "1"
					solid = "6"
					targetname = "wam_continue_sign"
					origin = Vector( 3.22243, -11, 46.2316 )
				}
			}
			wam_continue_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "wam_continue_relay"
					origin = Vector( 29, -17, 53 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "wam_continue_signSkin00-1"
							cmd2 = "wam_continue_signSkin11-1"
							cmd3 = "wam_continue_signSkin02-1"
							cmd4 = "wam_continue_signSkin13-1"
							cmd5 = "wam_continue_signSkin04-1"
							cmd6 = "wam_continue_signSkin15-1"
							cmd7 = "counter_scriptRunScriptCodeResetScore()10-1"
							cmd8 = "wam_continue_signSkin06-1"
							cmd9 = "wam_continue_signSkin17-1"
							cmd10 = "wam_continue_signSkin08-1"
							cmd11 = "wam_continue_signSkin19-1"
							cmd12 = "timer_scriptrunscriptcodeBeginContinueMode()0-1"
							cmd13 = "stachewhacker_usetargetRunScriptCodeGameOver()0-1"
						}
					}
				}
			}
			wam_target_hit_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "Moustachio_WHACKSMASH01"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "wam_target_hit_sound"
					origin = Vector( 26, 0, 50 )
				}
			}
			wam_target_surprise_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "Moustachio_WHACKPOPUP01"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "wam_target_surprise_sound"
					origin = Vector( 27, 0, 47 )
				}
			}
			timer_1 = 
			{
				SpawnInfo =
				{
					classname = "momentary_rot_button"
					_minlight = "1"
					angles = Vector( 0, 0, 0 )
					distance = "360"
					fademindist = "-1"
					fadescale = "1"
					origin = Vector( -5, -22, 41 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					returnspeed = "0"
					sounds = "0"
					spawnflags = "161"
					speed = "10000"
					startdirection = "1"
					targetname = "timer_1"
				}
			}
			timer_2 = 
			{
				SpawnInfo =
				{
					classname = "momentary_rot_button"
					_minlight = "1"
					angles = Vector( 0, 0, 0 )
					distance = "360"
					fademindist = "-1"
					fadescale = "1"
					origin = Vector( -5, -27.5, 41 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					returnspeed = "0"
					sounds = "0"
					spawnflags = "161"
					speed = "10000"
					startdirection = "1"
					targetname = "timer_2"
				}
			}
			timer_0 = 
			{
				SpawnInfo =
				{
					classname = "func_rotating"
					_minlight = "1"
					angles = Vector( 0, 0, 0 )
					disableshadows = "0"
					dmg = "0"
					fademindist = "-1"
					fadescale = "1"
					fanfriction = "0"
					maxspeed = "360"
					origin = Vector( -5, -16.5, 41 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					spawnflags = "74"
					targetname = "timer_0"
					volume = "10"
				}
			}
			wam_game_countdown_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "WAM.CountDown"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "wam_game_countdown_sound"
					origin = Vector( -3, 1, 62 )
				}
			}
			wam_low_score_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "WAM.LowScore"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "wam_low_score_sound"
					origin = Vector( 2, 12, 71 )
				}
			}
			wam_break_machine_rl = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "wam_break_machine_rl"
					origin = Vector( 36, 22, 69 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "wam_continue_relayKill0.01-1"
							cmd2 = "game_start_buttonKill0-1"
							cmd3 = "wam_game_musicFadeOut10-1"
							cmd4 = "timer_scriptRunScriptCodeStopTimer()0-1"
							cmd5 = "wam_game_over_soundPlaySound0-1"
							cmd6 = "wam_glass_intactKill0-1"
							cmd7 = "wam_glass_brokenEnable0-1"
							cmd8 = "plunger_3_targetSetAnimationbreak010.1-1"
							cmd9 = "plunger_1_targetSetAnimationbreak010.1-1"
							cmd10 = "plunger_2_targetSetAnimationbreak020.5-1"
							cmd11 = "plunger_4_targetSetAnimationbreak021-1"
							cmd12 = "plunger_5_targetSetAnimationbreak011.5-1"
							cmd13 = "wam_target_hit_soundKill0-1"
							cmd14 = "wam_game_start_buttonKill0-1"
							cmd15 = "wam_animated_sign_timerEnable0-1"
							cmd16 = "plunger_1Close0-1"
							cmd17 = "plunger_2Close0-1"
							cmd18 = "plunger_3Close0-1"
							cmd19 = "plunger_4Close0-1"
							cmd20 = "plunger_5Close0-1"
							cmd21 = "fx_ticket_jackpotStart0-1"
							cmd22 = "fx_sparksStart0.5-1"
							cmd23 = "fx_smokeStart1-1"
							cmd24 = "fx_boom1Start0-1"
							cmd25 = "fx_boom2Start0.25-1"
							cmd26 = "wam_continue_relayCancelPending0-1"
							cmd27 = "wam_achievement_eventGenerateGameEvent1-1"
							cmd28 = "wam_animated_sign_timerDisable10-1"
							cmd29 = "fx_boom2Stop10-1"
							cmd30 = "fx_boom1Stop10-1"
						}
					}
				}
			}
			wam_animated_sign = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowstate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_fairgrounds/arcadegame01_panel.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "wam_animated_sign"
					updatechildren = "0"
					origin = Vector( -6, -28, 53 )
				}
			}
			wam_glass_intact = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowstate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_fairgrounds/arcadegame01_glasswhole.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "wam_glass_intact"
					updatechildren = "0"
					origin = Vector( -6, -28, 53 )
				}
			}
			wam_glass_broken = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowstate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_fairgrounds/arcadegame01_glassbroken.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "wam_glass_broken"
					updatechildren = "0"
					origin = Vector( -6, -28, 53 )
				}
			}
			wam_game_over_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "WAM.GameOver"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "wam_game_over_sound"
					origin = Vector( 2, 3, 72 )
				}
			}
			wam_animated_sign_timer = 
			{
				SpawnInfo =
				{
					classname = "logic_timer"
					RefireTime = "1"
					spawnflags = "1"
					StartDisabled = "1"
					targetname = "wam_animated_sign_timer"
					origin = Vector( 11, -9, 52.9981 )
					connections =
					{
						OnTimerLow =
						{
							cmd1 = "wam_animated_signSkin10-1"
						}
						OnTimerHigh =
						{
							cmd1 = "wam_animated_signSkin00-1"
						}
					}
				}
			}
			fx_ticket_single = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "ticket_stasche_wacker"
					start_active = "0"
					targetname = "fx_ticket_single"
					origin = Vector( 44, -6, 25 )
				}
			}
			fx_ticket_jackpot = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "ticket_stasche_wacker_jackpot"
					start_active = "0"
					targetname = "fx_ticket_jackpot"
					origin = Vector( 44, -6, 25 )
				}
			}
			fx_boom1 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "sparks_generic_random"
					start_active = "0"
					targetname = "fx_boom1"
					origin = Vector( -7, 21, 70 )
				}
			}
			fx_smoke = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1 = "fx_smoke_target_1"
					cpoint1_parent = "0"
					cpoint2 = "fx_smoke_target_2"
					cpoint2_parent = "0"
					cpoint3 = "fx_smoke_target_3"
					cpoint3_parent = "0"
					cpoint4 = "fx_smoke_target_4"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "smoke_stache"
					start_active = "0"
					targetname = "fx_smoke"
					origin = Vector( 16, 20, 40 )
				}
			}
			fx_smoke_target_1 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_target"
					angles = Vector( 0, 0, 0 )
					targetname = "fx_smoke_target_1"
					origin = Vector( 35, 10, 40 )
				}
			}
			fx_smoke_target_2 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_target"
					angles = Vector( 0, 0, 0 )
					targetname = "fx_smoke_target_2"
					origin = Vector( 16, 0, 40 )
				}
			}
			fx_smoke_target_3 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_target"
					angles = Vector( 0, 0, 0 )
					targetname = "fx_smoke_target_3"
					origin = Vector( 35, -10, 40 )
				}
			}
			fx_smoke_target_4 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_target"
					angles = Vector( 0, 0, 0 )
					targetname = "fx_smoke_target_4"
					origin = Vector( 16, -19, 40 )
				}
			}
			fx_sparks = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "railroad_light_explode"
					start_active = "0"
					targetname = "fx_sparks"
					origin = Vector( -7, 9, 70 )
				}
			}
			fx_sparks1 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "stache_break"
					start_active = "0"
					targetname = "fx_sparks"
					origin = Vector( -7, 16, 70 )
				}
			}
			fx_sparks2 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "stache_break_metal"
					start_active = "0"
					targetname = "fx_sparks"
					origin = Vector( 15, 0, 40 )
				}
			}
			fx_boom11 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "impact_electronic"
					start_active = "0"
					targetname = "fx_boom1"
					origin = Vector( 15, 0, 40 )
				}
			}
			fx_boom2 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "impact_metal"
					start_active = "0"
					targetname = "fx_boom2"
					origin = Vector( 35, 10, 40 )
				}
			}
			fx_boom12 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 75, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "impact_electronic"
					start_active = "0"
					targetname = "fx_boom1"
					origin = Vector( -6, 16, 67 )
				}
			}
			fx_sparks3 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "impact_glass"
					start_active = "0"
					targetname = "fx_sparks"
					origin = Vector( -7, 11, 70 )
				}
			}
			fx_boom13 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 90, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "impact_glass"
					start_active = "0"
					targetname = "fx_boom1"
					origin = Vector( -7, 7, 70 )
				}
			}
			wam_achievement_event = 
			{
				SpawnInfo =
				{
					classname = "info_game_event_proxy"
					event_name = "stashwhacker_game_won"
					range = "50"
					targetname = "wam_achievement_event"
					origin = Vector( 10.3614, 7.06856, 50 )
				}
			}
			wam_bullet_filter = 
			{
				SpawnInfo =
				{
					classname = "filter_damage_type"
					damagetype = "2"
					Negated = "0"
					targetname = "@wam_bullet_filter"
					origin = Vector( 33, 1, 66 )
				}
			}
			wam_damage_filter_multi = 
			{
				SpawnInfo =
				{
					classname = "filter_multi"
					Filter01 = "@wam_bullet_filter"
					Filter02 = "@wam_melee_filter"
					filtertype = "1"
					Negated = "0"
					targetname = "wam_damage_filter_multi"
					origin = Vector( 21, -10.4681, 71 )
				}
			}
			game_start_button = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					targetname = "game_start_button"
					origin = Vector( 34, 22, 45 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "timer_scriptRunScriptCodeStartGame()4-1"
							cmd2 = "wam_game_musicPlaySound4-1"
							cmd3 = "wam_game_countdown_soundPlaySound1-1"
							cmd4 = "timer_scriptRunScriptCodeEndContinueMode()0-1"
							cmd5 = "wam_continue_signSkin10-1"
							cmd6 = "wam_continue_relayCancelPending0-1"
							cmd7 = "wam_game_start_soundPlaySound0-1"
							cmd8 = "game_start_button_modelSetAnimationidle_on0-1"
							cmd9 = "!selfDisable0-1"
						}
					}
				}
			}
			stachewhacker_usetarget = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "wam_game_start_button"
					origin = Vector( 36, -21, 37.89 )
					targetname = "stachewhacker_usetarget"
					vscripts = "usetargets/stachewhacker_use_target"
					connections =
					{
						OnUser1 =
						{
							cmd1 = "game_start_buttonTrigger0-1"
						}
					}
				}
			}
			wam_game_start_button = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, -180 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = ".2"
					glowcolor = "121 202 0"
					glowrange = "128"
					glowrangemin = "0"
					glowstate = "3"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/buildable_button.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "wam_game_start_button"
					updatechildren = "0"
					origin = Vector( 47, -10, 39.8922 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // CarnivalgameStachewhacker

RegisterEntityGroup( "CarnivalgameStachewhacker", CarnivalgameStachewhacker )
