//-------------------------------------------------------
// Autogenerated from 'ceiling_fan.vmf'
//-------------------------------------------------------
CeilingFan <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.fan_body,
			EntityGroup.SpawnTables.fan_blade,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.fan_rope_top,
			EntityGroup.SpawnTables.fan_rope_bottom,
			EntityGroup.SpawnTables.fan_spring,
			EntityGroup.SpawnTables.fan_blade,
			EntityGroup.SpawnTables.infected_filter,
			EntityGroup.SpawnTables.fan_spin_sound,
			EntityGroup.SpawnTables.fan_collision_pair,
			EntityGroup.SpawnTables.fan_start_rl,
			EntityGroup.SpawnTables.fan_spark,
			EntityGroup.SpawnTables.fan_break_rl,
			EntityGroup.SpawnTables.fan_hurt1,
			EntityGroup.SpawnTables.fan_hurt,
			EntityGroup.SpawnTables.fan_ragdoll_const,
			EntityGroup.SpawnTables.fan_die_sound,
			EntityGroup.SpawnTables.fan_const_system,
			EntityGroup.SpawnTables.fan_physexp,
			EntityGroup.SpawnTables.fan_motor,
			EntityGroup.SpawnTables.fan_body,
			EntityGroup.SpawnTables.fan_chop_sound,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			fan_body = 
			{
				SpawnInfo =
				{
					classname = "prop_physics_override"
					angles = Vector( 0, 0, 0 )
					body = "0"
					damagetoenablemotion = "0"
					Damagetype = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "3250"
					fademindist = "3050"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "9999"
					inertiaScale = "1.0"
					massScale = "0"
					minhealthdmg = "0"
					model = "models/props/de_inferno/ceiling_fan.mdl"
					nodamageforces = "0"
					PerformanceMode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					shadowcastdist = "0"
					spawnflags = "264"
					targetname = "fan_body"
					origin = Vector( 0, 0, 0 )
					connections =
					{
						OnTakeDamage =
						{
							cmd1 = "!selfSetHealth999901"
							cmd2 = "fan_start_rlTrigger01"
						}
					}
				}
			}
			fan_blade = 
			{
				SpawnInfo =
				{
					classname = "prop_physics_override"
					angles = Vector( 0, 0, 0 )
					damagetoenablemotion = "0"
					Damagetype = "0"
					disableshadows = "1"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					health = "0"
					inertiaScale = "1.0"
					massScale = "0"
					minhealthdmg = "0"
					model = "models/props/de_inferno/ceiling_fan_blade.mdl"
					nodamageforces = "0"
					PerformanceMode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "264"
					targetname = "fan_blade"
					origin = Vector( 0, 0, -20 )
					connections =
					{
						OnTakeDamage =
						{
							cmd1 = "fan_start_rlTrigger01"
							cmd2 = "!selfSetHealth999901"
						}
					}
				}
			}
			fan_motor = 
			{
				SpawnInfo =
				{
					classname = "phys_motor"
					attach1 = "fan_blade"
					axis = Vector( 0, 0, -19 )
					inertiafactor = "5.0"
					spawnflags = "0"
					speed = "1000"
					spinup = ".5"
					targetname = "fan_motor"
					origin = Vector( 0, 0, -25 )
				}
			}
			fan_start_rl = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "1"
					targetname = "fan_start_rl"
					origin = Vector( 0, 0, -52 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "fan_motorTurnOn01"
							cmd2 = "fan_bladeEnableMotion01"
							cmd3 = "fan_bodyEnableMotion0.21"
							cmd4 = "fan_hurtEnable01"
							cmd5 = "fan_spin_soundPlaySound01"
							cmd6 = "fan_break_rlTrigger151"
							cmd7 = "fan_sparkSparkOnce01"
							cmd8 = "fan_physexpExplode0.31"
							cmd9 = "fan_physexpExplode0.51"
						}
					}
				}
			}
			fan_spring = 
			{
				SpawnInfo =
				{
					classname = "phys_spring"
					attach2 = "fan_body"
					constant = "5000"
					damping = "1000"
					length = "75"
					relativedamping = "0.9"
					spawnflags = "1"
					springaxis = Vector( 0, 0, -2 )
					targetname = "fan_spring"
					origin = Vector( 0, 0, -2 )
				}
			}
			fan_collision_pair = 
			{
				SpawnInfo =
				{
					classname = "logic_collision_pair"
					attach1 = "fan_body"
					attach2 = "fan_blade"
					startdisabled = "1"
					targetname = "fan_collision_pair"
					origin = Vector( 0, 0, -124 )
				}
			}
			fan_ragdoll_const = 
			{
				SpawnInfo =
				{
					classname = "phys_ragdollconstraint"
					angles = Vector( 0, 0, 0 )
					attach1 = "fan_blade"
					attach2 = "fan_body"
					constraintsystem = "fan_const_system"
					spawnflags = "3"
					targetname = "fan_ragdoll_const"
					xmax = "0"
					xmin = "0"
					ymax = "0"
					ymin = "0"
					zmax = "9999"
					zmin = "-9999"
					origin = Vector( 0, 0, -22 )
				}
			}
			fan_const_system = 
			{
				SpawnInfo =
				{
					classname = "phys_constraintsystem"
					additionaliterations = "10"
					targetname = "fan_const_system"
					origin = Vector( 0, 0, -40 )
				}
			}
			fan_rope_top = 
			{
				SpawnInfo =
				{
					classname = "keyframe_rope"
					angles = Vector( 0, 0, 0 )
					MoveSpeed = "64"
					NextKey = "fan_rope_bottom"
					RopeMaterial = "cable/cable.vmt"
					Slack = "140"
					spawnflags = "0"
					Subdiv = "2"
					targetname = "fan_rope_top"
					TextureScale = "1"
					Width = "2"
					origin = Vector( 0, 0, 0 )
				}
			}
			fan_rope_bottom = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 0, 0 )
					Breakable = "1"
					MoveSpeed = "64"
					parentname = "fan_body"
					PositionInterpolator = "2"
					RopeMaterial = "cable/cable.vmt"
					Slack = "25"
					spawnflags = "1"
					Subdiv = "2"
					targetname = "fan_rope_bottom"
					TextureScale = "1"
					Width = "2"
					origin = Vector( 0, 0, -2 )
				}
			}
			fan_hurt = 
			{
				SpawnInfo =
				{
					classname = "script_trigger_hurt"
					damage = "50"
					damagecap = "50"
					damagemodel = "0"
					damagetype = "16777216"
					filtername = "infected_filter"
					nodmgforce = "0"
					origin = Vector( 0, 0, -21.7 )
					parentname = "fan_body"
					spawnflags = "2"
					StartDisabled = "1"
					targetname = "fan_hurt"
					thinkalways = "1"
					extent = Vector( 40, 40, 4 )
					connections =
					{
						OnHurt =
						{
							cmd1 = "fan_chop_soundPlaySound0-1"
							cmd2 = "fan_sparkSparkOnce0-1"
							cmd3 = "fan_physexpExplode0-1"
						}
					}
				}
			}
			infected_filter = 
			{
				SpawnInfo =
				{
					classname = "filter_activator_team"
					filterteam = "3"
					Negated = "Allow entities that match criteria"
					targetname = "infected_filter"
					origin = Vector( 0, 0, -80 )
				}
			}
			fan_hurt1 = 
			{
				SpawnInfo =
				{
					classname = "script_trigger_hurt"
					damage = "10"
					damagecap = "10"
					damagemodel = "0"
					damagetype = "0"
					nodmgforce = "0"
					origin = Vector( 0, 0, -21.7 )
					parentname = "fan_body"
					spawnflags = "1"
					StartDisabled = "1"
					targetname = "fan_hurt"
					thinkalways = "0"
					extent = Vector( 38, 38, 4 )
					connections =
					{
						OnHurtPlayer =
						{
							cmd1 = "fan_chop_soundPlaySound0-1"
							cmd2 = "fan_sparkSparkOnce0-1"
						}
					}
				}
			}
			fan_break_rl = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "1"
					targetname = "fan_break_rl"
					origin = Vector( 0, 0, -64 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "fan_motorTurnOff0-1"
							cmd2 = "fan_springKill0-1"
							cmd3 = "fan_die_soundPlaySound0-1"
							cmd4 = "fan_sparkSparkOnce0-1"
							cmd5 = "fan_spin_soundStopSound0-1"
							cmd6 = "fan_rope_bottomBreak0-1"
							cmd7 = "fan_ragdoll_constBreak0-1"
							cmd8 = "fan_hurtKill0-1"
							cmd9 = "fan_physexpKill0-1"
							cmd10 = "infected_filterKill0-1"
							cmd11 = "fan_spin_soundKill3-1"
							cmd12 = "fan_die_soundKill3-1"
							cmd13 = "fan_chop_soundKill3-1"
							cmd14 = "fan_collision_pairKill0-1"
							cmd15 = "fan_motorKill0-1"
							cmd16 = "fan_sparkSparkOnce2-1"
							cmd17 = "fan_sparkKill4-1"
							cmd18 = "fan_const_systemKill0-1"
							cmd19 = "fan_sparkSparkOnce3-1"
						}
					}
				}
			}
			fan_spin_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "Chainsaw.Idle"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					SourceEntityName = "fan_blade"
					spawnflags = "16"
					targetname = "fan_spin_sound"
					origin = Vector( 0, 0, -104 )
				}
			}
			fan_die_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "Chainsaw.Stop"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					SourceEntityName = "fan_blade"
					spawnflags = "48"
					targetname = "fan_die_sound"
					origin = Vector( 0, 0, -112 )
				}
			}
			fan_chop_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "Chainsaw.Gore"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					SourceEntityName = "fan_blade"
					spawnflags = "48"
					targetname = "fan_chop_sound"
					origin = Vector( 0, 0, -96 )
				}
			}
			fan_spark = 
			{
				SpawnInfo =
				{
					classname = "env_spark"
					angles = Vector( 0, 0, 0 )
					Magnitude = "2"
					MaxDelay = "1"
					parentname = "fan_body"
					spawnflags = "0"
					targetname = "fan_spark"
					TrailLength = "2"
					origin = Vector( 0, 0, -1 )
				}
			}
			fan_physexp = 
			{
				SpawnInfo =
				{
					classname = "env_physexplosion"
					inner_radius = "0"
					magnitude = "5"
					parentname = "fan_body"
					radius = "0"
					spawnflags = "1"
					targetname = "fan_physexp"
					origin = Vector( 13, -12, 0 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // CeilingFan

RegisterEntityGroup( "CeilingFan", CeilingFan )
