//-------------------------------------------------------
// Autogenerated from 'combiner.vmf'
//-------------------------------------------------------
Combiner <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.combiner_model,
			EntityGroup.SpawnTables.combiner_spawn_target,
			EntityGroup.SpawnTables.combiner_glass_model,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.combiner_creation_fx_relay,
			EntityGroup.SpawnTables.combiner_creation_arc_particles_target_1,
			EntityGroup.SpawnTables.combiner_script,
			EntityGroup.SpawnTables.combiner_creation_arc_particles,
			EntityGroup.SpawnTables.combiner_glass_model,
			EntityGroup.SpawnTables.combiner_spawn_target,
			EntityGroup.SpawnTables.combiner_creation_particles,
			EntityGroup.SpawnTables.combiner_creation_arc_particles_target_2,
			EntityGroup.SpawnTables.combiner_model,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			combiner_model = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 270, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_collectables/alchemy_table.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "combiner_model"
					origin = Vector( 0, 0, 0 )
				}
			}
			combiner_script = 
			{
				SpawnInfo =
				{
					classname = "logic_script"
					Group00 = "combiner_model"
					Group01 = "combiner_spawn_target"
					Group02 = "combiner_creation_fx_relay"
					targetname = "combiner_script"
					thinkfunction = "Think"
					vscripts = "usetargets/combiner"
					origin = Vector( 0, 0, 28 )
				}
			}
			combiner_spawn_target = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					health = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_collectables/piepan.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "combiner_spawn_target"
					origin = Vector( -24, 0, 0 )
				}
			}
			combiner_creation_particles = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( -90, 0, 0 )
					effect_name = "electrical_arc_01_system"
					targetname = "combiner_creation_particles"
					origin = Vector( -24, 0, 4 )
				}
			}
			combiner_creation_arc_particles_target_2 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_target"
					angles = Vector( 0, 0, 0 )
					targetname = "combiner_creation_arc_particles_target_2"
					origin = Vector( -24, 0, 0.508902 )
				}
			}
			combiner_creation_arc_particles = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( -90, 0, 0 )
					cpoint1 = "combiner_creation_arc_particles_target_1"
					cpoint2 = "combiner_creation_arc_particles_target_2"
					effect_name = "electrical_arc_01"
					targetname = "combiner_creation_arc_particles"
					origin = Vector( 0, 0, -0.491098 )
				}
			}
			combiner_creation_arc_particles_target_1 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_target"
					angles = Vector( 0, 0, 0 )
					targetname = "combiner_creation_arc_particles_target_1"
					origin = Vector( 0, 0, 20.5089 )
				}
			}
			combiner_creation_fx_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					targetname = "combiner_creation_fx_relay"
					origin = Vector( 0, 0, 44 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "combiner_creation_arc_particlesStart0-1"
							cmd2 = "combiner_creation_arc_particlesStop2-1"
							cmd3 = "combiner_creation_particlesStart0-1"
							cmd4 = "combiner_creation_particlesStop2-1"
						}
					}
				}
			}
			combiner_glass_model = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 270, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_collectables/alchemy_table_glass.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "combiner_glass_model"
					origin = Vector( 0, 0, 0 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // Combiner

RegisterEntityGroup( "Combiner", Combiner )
