//-------------------------------------------------------
// Autogenerated from 'cooldown_extension_button.vmf'
//-------------------------------------------------------
CooldownExtensionButton <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.button_radio,
			EntityGroup.SpawnTables.unnamed,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.button_radio,
			EntityGroup.SpawnTables.hint,
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.cooldown_extension_sound_2,
			EntityGroup.SpawnTables.cooldown_extension_sound_1,
			EntityGroup.SpawnTables.usetarget_cooldown,
			EntityGroup.SpawnTables.radio_time_extension_relay,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			radio_time_extension_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					targetname = "radio_time_extension_relay"
					origin = Vector( 0, 0, 0 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "cooldown_extension_sound_1PlaySound0-1"
							cmd2 = "cooldown_extension_sound_2PlaySound3.5-1"
							cmd3 = "usetarget_cooldownRunScriptCodeExtendCooldownTime()0-1"
							cmd4 = "hintShowHint0-1"
							cmd5 = "hintEndHint8-1"
						}
					}
				}
			}
			button_radio = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "78 184 41"
					glowrange = "240"
					glowrangemin = "0"
					glowstate = "3"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_placeable/radio_box.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "button_radio"
					updatechildren = "0"
					origin = Vector( 0, 0, 0 )
				}
			}
			usetarget_cooldown = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "button_radio"
					origin = Vector( 0, 0, 0 )
					targetname = "usetarget_cooldown"
					vscripts = "usetargets/cooldown_extension"
					connections =
					{
						OnUser1 =
						{
							cmd1 = "radio_time_extension_relayTrigger0-1"
						}
						OnUser3 =
						{
							cmd1 = "button_radioColor0 255 00-1"
						}
						OnUser4 =
						{
							cmd1 = "button_radioColor255 0 00-1"
						}
					}
				}
			}
			cooldown_extension_sound_1 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "npc.ChopperPilot_hospital_intro_heli_10"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "cooldown_extension_sound_1"
					origin = Vector( 0, 0, 0 )
				}
			}
			cooldown_extension_sound_2 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "npc.ChopperPilot_hospital_intro_heli_07"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "cooldown_extension_sound_2"
					origin = Vector( 0, 0, 0 )
				}
			}
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_placeable/clock_trophy.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					origin = Vector( 0, 0, 9 )
				}
			}
			hint = 
			{
				SpawnInfo =
				{
					classname = "env_instructor_hint"
					hint_allow_nodraw_target = "1"
					hint_auto_start = "1"
					hint_caption = "You now have more time until the next wave!"
					hint_color = "255 255 255"
					hint_forcecaption = "1"
					hint_icon_offscreen = "icon_tip"
					hint_icon_onscreen = "icon_alert"
					hint_instance_type = "2"
					hint_nooffscreen = "1"
					hint_static = "1"
					hint_timeout = "7"
					targetname = "hint"
					origin = Vector( 0, 0, 16 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // CooldownExtensionButton

RegisterEntityGroup( "CooldownExtensionButton", CooldownExtensionButton )
