//-------------------------------------------------------
// Autogenerated from 'curling_rock.vmf'
//-------------------------------------------------------
CurlingRock <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.rock,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.rock,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			rock = 
			{
				SpawnInfo =
				{
					classname = "prop_physics_override"
					angles = Vector( 0, 0, 0 )
					damagetoenablemotion = "0"
					Damagetype = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					health = "0"
					inertiaScale = "1.0"
					massScale = "0"
					minhealthdmg = "0"
					model = "models/props_placeable/curling_stone.mdl"
					nodamageforces = "0"
					physdamagescale = "0.1"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "8512"
					targetname = "rock"
					origin = Vector( 0, 0, 1.18255 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // CurlingRock

RegisterEntityGroup( "CurlingRock", CurlingRock )
