//-------------------------------------------------------
// Autogenerated from 'dash_waypoint_short.vmf'
//-------------------------------------------------------
DashWaypointShort <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.touch_indicator_1,
			EntityGroup.SpawnTables.touch_indicator_2,
			EntityGroup.SpawnTables.touch_indicator_3,
			EntityGroup.SpawnTables.touch_indicator_4,
			EntityGroup.SpawnTables.waypoint,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.touch_indicator_3,
			EntityGroup.SpawnTables.touch_indicator_2,
			EntityGroup.SpawnTables.touch_indicator_1,
			EntityGroup.SpawnTables.firework_1,
			EntityGroup.SpawnTables.firework_1_launch_sound,
			EntityGroup.SpawnTables.waypoint,
			EntityGroup.SpawnTables.firework_1_fire_sound,
			EntityGroup.SpawnTables.firework_2,
			EntityGroup.SpawnTables.firework_3,
			EntityGroup.SpawnTables.firework_4,
			EntityGroup.SpawnTables.touch_indicator_4,
			EntityGroup.SpawnTables.smoke_puff,
			EntityGroup.SpawnTables.waypoint_entgroup_script,
			EntityGroup.SpawnTables.firework_1_burst_sound,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			waypoint_entgroup_script = 
			{
				SpawnInfo =
				{
					classname = "logic_script"
					Group00 = "waypoint"
					Group01 = "touch_indicator_1"
					Group02 = "touch_indicator_2"
					Group03 = "touch_indicator_3"
					Group04 = "touch_indicator_4"
					targetname = "waypoint_entgroup_script"
					origin = Vector( 0, 0, 32 )
				}
			}
			touch_indicator_1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 270, -90 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "255 0 0"
					glowrange = "0"
					glowstate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props/de_nuke/wall_light.mdl"
					renderamt = "255"
					rendercolor = "255 0 0"
					rendermode = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "touch_indicator_1"
					origin = Vector( 0, -1, 21 )
					connections =
					{
						OnUser1 =
						{
							cmd1 = "firework_1Stop31"
							cmd2 = "firework_1_burst_soundPlaySound2.21"
							cmd3 = "firework_1_launch_soundPlaySound0.11"
							cmd4 = "firework_1Start01"
							cmd5 = "firework_1_fire_soundPlaySound01"
							cmd6 = "firework_1Kill41"
						}
					}
				}
			}
			firework_1_launch_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "c2m5.fireworks_launch"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "firework_1_launch_sound"
					origin = Vector( 0, 0, 86 )
				}
			}
			firework_1 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 90, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "fireworks_03"
					start_active = "0"
					targetname = "firework_1"
					origin = Vector( 0, -8, 50 )
				}
			}
			firework_1_fire_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "GrenadeLauncher.Fire"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "firework_1_fire_sound"
					origin = Vector( 0, 0, 70 )
				}
			}
			firework_1_burst_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "c2m5.fireworks_burst"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "6000"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "firework_1_burst_sound"
					volstart = "0"
					origin = Vector( 0, 0, 102 )
				}
			}
			firework_2 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 90, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "fireworks_03"
					start_active = "0"
					targetname = "firework_2"
					origin = Vector( -8, 0, 50 )
				}
			}
			firework_3 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 90, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "fireworks_03"
					start_active = "0"
					targetname = "firework_3"
					origin = Vector( 0, 8, 50 )
				}
			}
			firework_4 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 90, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "fireworks_03"
					start_active = "0"
					targetname = "firework_4"
					origin = Vector( 8, 0, 50 )
				}
			}
			touch_indicator_2 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 180, -90 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "255 0 0"
					glowrange = "0"
					glowstate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props/de_nuke/wall_light.mdl"
					renderamt = "255"
					rendercolor = "255 0 0"
					rendermode = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "touch_indicator_2"
					origin = Vector( -1, 0, 21 )
					connections =
					{
						OnUser1 =
						{
							cmd1 = "firework_2Stop31"
							cmd2 = "firework_1_burst_soundPlaySound2.21"
							cmd3 = "firework_1_launch_soundPlaySound0.11"
							cmd4 = "firework_2Start01"
							cmd5 = "firework_1_fire_soundPlaySound01"
							cmd6 = "firework_2Kill41"
						}
					}
				}
			}
			touch_indicator_3 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 90, -90 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "255 0 0"
					glowrange = "0"
					glowstate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props/de_nuke/wall_light.mdl"
					renderamt = "255"
					rendercolor = "255 0 0"
					rendermode = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "touch_indicator_3"
					origin = Vector( 0, 1, 21 )
					connections =
					{
						OnUser1 =
						{
							cmd1 = "firework_3Stop31"
							cmd2 = "firework_3Start01"
							cmd3 = "firework_3Kill41"
							cmd4 = "firework_1_burst_soundPlaySound2.21"
							cmd5 = "firework_1_launch_soundPlaySound0.11"
							cmd6 = "firework_1_fire_soundPlaySound01"
						}
					}
				}
			}
			touch_indicator_4 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, -90 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "255 0 0"
					glowrange = "0"
					glowstate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props/de_nuke/wall_light.mdl"
					renderamt = "255"
					rendercolor = "255 0 0"
					rendermode = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "touch_indicator_4"
					origin = Vector( 1, 0, 21 )
					connections =
					{
						OnUser1 =
						{
							cmd1 = "firework_4Stop31"
							cmd2 = "firework_4Start01"
							cmd3 = "firework_4Kill41"
							cmd4 = "firework_1_burst_soundPlaySound2.21"
							cmd5 = "firework_1_launch_soundPlaySound0.11"
							cmd6 = "firework_1_fire_soundPlaySound01"
						}
					}
				}
			}
			waypoint = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 0, 270, 0 )
					body = "0"
					DefaultAnim = "idle"
					disablereceiveshadows = "0"
					disableshadows = "1"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "2300"
					fademindist = "2200"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowstate = "0"
					health = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_waterfront/sign_underriver_linepost.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "waypoint"
					thinkfunction = "Think"
					updatechildren = "0"
					vscripts = "dash_waypoint"
					origin = Vector( 0, 0, 0 )
					connections =
					{
						OnUser1 =
						{
							cmd1 = "smoke_puffStart0-1"
							cmd2 = "smoke_puffStop2-1"
							cmd3 = "smoke_puffKill3-1"
						}
					}
				}
			}
			smoke_puff = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( -32.5, 180, -90 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "bridge_isparkA"
					render_in_front = "0"
					start_active = "0"
					targetname = "smoke_puff"
					origin = Vector( 0.162989, -0.278092, 25.0283 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // DashWaypointShort

RegisterEntityGroup( "DashWaypointShort", DashWaypointShort )
