//-------------------------------------------------------
// Autogenerated from 'defib_cabinet.vmf'
//-------------------------------------------------------
DefibCabinet <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.defib,
			EntityGroup.SpawnTables.prop_defib,
			EntityGroup.SpawnTables.prop_defib1,
			EntityGroup.SpawnTables.defib1,
			EntityGroup.SpawnTables.button,
			EntityGroup.SpawnTables.cabinet,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.useTarget,
			EntityGroup.SpawnTables.prop_defib1,
			EntityGroup.SpawnTables.prop_defib,
			EntityGroup.SpawnTables.relay_defib_restock,
			EntityGroup.SpawnTables.cabinet,
			EntityGroup.SpawnTables.button,
			EntityGroup.SpawnTables.template_defib,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			defib = 
			{
				SpawnInfo =
				{
					classname = "weapon_defibrillator_spawn"
					angles = Vector( 3.53431, 271.95, -60.3907 )
					body = "0"
					disableshadows = "0"
					model = "models/w_models/weapons/w_eq_defibrillator.mdl"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "defib"
					origin = Vector( -1.30979, 5.00192, 7.92826 )
				}
			}
			prop_defib = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 3.53431, 271.95, -60.3907 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/w_models/weapons/w_eq_defibrillator.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "prop_defib"
					updatechildren = "0"
					origin = Vector( -1.30979, 5.00192, 7.92826 )
				}
			}
			prop_defib1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 4.5, 284.5, -60 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/w_models/weapons/w_eq_defibrillator.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "prop_defib"
					updatechildren = "0"
					origin = Vector( -0.710238, -5.12559, 7.22255 )
				}
			}
			defib1 = 
			{
				SpawnInfo =
				{
					classname = "weapon_defibrillator_spawn"
					angles = Vector( 4.5, 284.5, -60 )
					body = "0"
					disableshadows = "0"
					model = "models/w_models/weapons/w_eq_defibrillator.mdl"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "defib"
					origin = Vector( -0.710238, -5.12559, 7.22255 )
				}
			}
			template_defib = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "2"
					targetname = "template_defib"
					Template02 = "defib"
					origin = Vector( 16, 16, 6 )
				}
			}
			relay_defib_restock = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "relay_defib_restock"
					origin = Vector( 16, -16, 6 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "template_defibForceSpawn0-1"
							cmd2 = "prop_defibKill0-1"
							cmd3 = "cabinetSetAnimationOpen01"
							cmd4 = "template_defibKill0.1-1"
							cmd5 = "buttonKill01"
						}
					}
				}
			}
			useTarget = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "button"
					origin = Vector( 8, 0, 6 )
					targetname = "useTarget"
					vscripts = "usetargets/defib_cabinet"
					connections =
					{
						OnUser1 =
						{
							cmd1 = "relay_defib_restockTrigger0-1"
						}
					}
				}
			}
			button = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "121 202 0"
					glowrange = "120"
					glowrangemin = "0"
					glowstate = "3"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/buildable_button.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "button"
					updatechildren = "0"
					origin = Vector( 2, 0, -13 )
				}
			}
			cabinet = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/small_cabinet_firstaid.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "cabinet"
					updatechildren = "0"
					origin = Vector( 0, 0, 0 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // DefibCabinet

RegisterEntityGroup( "DefibCabinet", DefibCabinet )
