//-------------------------------------------------------
// Autogenerated from 'empty256.vmf'
//-------------------------------------------------------
Empty256 <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.attrib,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			attrib = 
			{
				SpawnInfo =
				{
					classname = "point_nav_attribute_region"
					maxs = "128 128 16"
					mins = "-128 -128 -16"
					spawnflags = "8194"
					targetname = "attrib"
					origin = Vector( 0, 0, 16 )
				}
			}
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "logic_auto"
					spawnflags = "1"
					origin = Vector( 0, 0, 48 )
					connections =
					{
						OnMapSpawn =
						{
							cmd1 = "attribKill2-1"
						}
					}
				}
			}
		} // SpawnTables
	} // EntityGroup
} // Empty256

RegisterEntityGroup( "Empty256", Empty256 )
