//-------------------------------------------------------
// Autogenerated from 'firework_launcher.vmf'
//-------------------------------------------------------
FireworkLauncher <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.unnamed1,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.firework_3_rl,
			EntityGroup.SpawnTables.unnamed1,
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.custom_relay,
			EntityGroup.SpawnTables.firework_1,
			EntityGroup.SpawnTables.firework_1_launch_sound,
			EntityGroup.SpawnTables.firework_1_rl,
			EntityGroup.SpawnTables.firework_2,
			EntityGroup.SpawnTables.firework_1_fire_sound,
			EntityGroup.SpawnTables.firework_3,
			EntityGroup.SpawnTables.firework_1_burst_sound,
			EntityGroup.SpawnTables.firework_2_rl,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			firework_1_launch_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "c2m5.fireworks_launch"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "firework_1_launch_sound"
					origin = Vector( 4, 26.8696, 8.00002 )
				}
			}
			firework_1_rl = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					targetname = "firework_1_rl"
					origin = Vector( -12, 10.8696, 8.00002 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "firework_1_launch_soundPlaySound0.1-1"
							cmd2 = "firework_1_fire_soundPlaySound0-1"
							cmd3 = "firework_1_burst_soundPlaySound2.2-1"
							cmd4 = "firework_1Start0-1"
							cmd5 = "firework_1Stop3-1"
						}
					}
				}
			}
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 0, 90, 0 )
					body = "0"
					disablereceiveshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "1250"
					fademindist = "1200"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_fairgrounds/mortar_rack.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					updatechildren = "0"
					origin = Vector( 0, 16, 0 )
				}
			}
			firework_3 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 1, 90, -4 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "fireworks_03"
					start_active = "0"
					targetname = "firework_3"
					origin = Vector( 0.601563, 30.0283, 23 )
				}
			}
			firework_2 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( -7, 90, -15 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "fireworks_03"
					start_active = "0"
					targetname = "firework_2"
					origin = Vector( 0.601563, 16.0283, 23 )
				}
			}
			firework_1 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( -15, 90, -4 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "fireworks_03"
					start_active = "0"
					targetname = "firework_1"
					origin = Vector( 0.601563, 1.02828, 23.001 )
				}
			}
			firework_1_fire_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "GrenadeLauncher.Fire"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "firework_1_fire_sound"
					origin = Vector( 4, 10.8696, 8.00002 )
				}
			}
			firework_1_burst_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "c2m5.fireworks_burst"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "6000"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "firework_1_burst_sound"
					volstart = "0"
					origin = Vector( 4, 10.8696, 32 )
				}
			}
			firework_2_rl = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					targetname = "firework_2_rl"
					origin = Vector( -12, 18.8696, 8.00002 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "firework_1_launch_soundPlaySound0.1-1"
							cmd2 = "firework_1_fire_soundPlaySound0-1"
							cmd3 = "firework_1_burst_soundPlaySound2.2-1"
							cmd4 = "firework_2Start0-1"
							cmd5 = "firework_2Stop3-1"
						}
					}
				}
			}
			firework_3_rl = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					targetname = "firework_3_rl"
					origin = Vector( -12, 26.8696, 8.00002 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "firework_1_launch_soundPlaySound0.1-1"
							cmd2 = "firework_1_fire_soundPlaySound0-1"
							cmd3 = "firework_1_burst_soundPlaySound2.2-1"
							cmd4 = "firework_3Start0-1"
							cmd5 = "firework_3Stop3-1"
						}
					}
				}
			}
			custom_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					targetname = "custom_relay"
					origin = Vector( 4, 8, 8.00002 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "firework_1_rlTrigger0-1"
							cmd2 = "firework_2_rlTrigger0.5-1"
							cmd3 = "firework_3_rlTrigger1-1"
						}
					}
				}
			}
			unnamed1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 35.3559, 289.067, -48.9496 )
					fademaxdist = "1250"
					fademindist = "1200"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/deadbodies/dead_male_civilian_radio.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					origin = Vector( -6.32354, 3, 13 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // FireworkLauncher

RegisterEntityGroup( "FireworkLauncher", FireworkLauncher )
