//-------------------------------------------------------
// Autogenerated from 'firewall_trap.vmf'
//-------------------------------------------------------
FirewallTrap <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.unnamed1,
			EntityGroup.SpawnTables.flametrap_nozzle,
			EntityGroup.SpawnTables.flametrap_target_model,
			EntityGroup.SpawnTables.unnamed2,
			EntityGroup.SpawnTables.unnamed3,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.flametrap_fire_ignitor,
			EntityGroup.SpawnTables.flametrap_pour_target,
			EntityGroup.SpawnTables.flametrap_target_model,
			EntityGroup.SpawnTables.hint_branch,
			EntityGroup.SpawnTables.flametrap_target_arm,
			EntityGroup.SpawnTables.flametrap_ignite_sound_1,
			EntityGroup.SpawnTables.filter_tank,
			EntityGroup.SpawnTables.flametrap_ignite_sound_2,
			EntityGroup.SpawnTables.flametrap_fuel_gauge_needle,
			EntityGroup.SpawnTables.flametrap_ignitor_flames,
			EntityGroup.SpawnTables.flametrap_nozzle,
			EntityGroup.SpawnTables.flametrap_lever_open_sound_11,
			EntityGroup.SpawnTables.flametrap_lever_open_sound_1,
			EntityGroup.SpawnTables.unnamed4,
			EntityGroup.SpawnTables.unnamed3,
			EntityGroup.SpawnTables.unnamed2,
			EntityGroup.SpawnTables.unnamed1,
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.flametrap_spark_sound_1,
			EntityGroup.SpawnTables.flametrap_pipe_point,
			EntityGroup.SpawnTables.flametrap_ignitor_sparks,
			EntityGroup.SpawnTables.hint,
			EntityGroup.SpawnTables.flametrap_lever_close_sound_11,
			EntityGroup.SpawnTables.flametrap_lever_close_sound_1,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props/cs_militia/furnace01.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					updatechildren = "0"
					origin = Vector( -0.999939, 0, 0 )
				}
			}
			unnamed1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_buildables/fuel_gauge.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					updatechildren = "0"
					origin = Vector( 0, 0, 21 )
				}
			}
			flametrap_nozzle = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 270, -113.5 )
					body = "0"
					disablereceiveshadows = "1"
					disableshadows = "1"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "2200"
					fademindist = "2000"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "255 128 64"
					glowrange = "180"
					glowstate = "3"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_vehicles/radio_generator_fillup.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "flametrap_nozzle"
					updatechildren = "0"
					origin = Vector( -45, 20, 42 )
				}
			}
			flametrap_pour_target = 
			{
				SpawnInfo =
				{
					classname = "point_prop_use_target"
					nozzle = "flametrap_nozzle"
					origin = Vector( 22, 2, 60 )
					spawnflags = "1"
					targetname = "flametrap_pour_target"
					thinkfunction = "FireTrapThink"
					vscripts = "usetargets/holdout_gas_firewall"
					connections =
					{
						OnUser1 =
						{
							cmd1 = "0-1"
						}
					}
				}
			}
			flametrap_target_arm = 
			{
				SpawnInfo =
				{
					classname = "func_door_rotating"
					angles = Vector( 0, 0, 0 )
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					distance = "180"
					dmg = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forceclosed = "0"
					health = "0"
					ignoredebris = "0"
					lip = "0"
					locked_sentence = "0"
					loopmovesound = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					origin = Vector( -17, 10.5, 110 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					solidbsp = "0"
					spawnflags = "4788"
					spawnpos = "0"
					speed = "1000"
					targetname = "flametrap_target_arm"
					unlocked_sentence = "0"
					wait = "4"
					connections =
					{
						OnFullyOpen =
						{
							cmd1 = "hintShowHint01"
						}
						OnOpen =
						{
							cmd1 = "flametrap_lever_open_sound_1PlaySound0-1"
						}
						OnClose =
						{
							cmd1 = "flametrap_ignitor_flamesStart0.4-1"
							cmd2 = "flametrap_ignitor_sparksStart0-1"
							cmd3 = "flametrap_ignitor_sparksStop1-1"
							cmd4 = "flametrap_ignitor_flamesStop1.2-1"
							cmd5 = "flametrap_ignite_sound_1PlaySound0.3-1"
							cmd6 = "flametrap_spark_sound_1PlaySound0-1"
							cmd7 = "flametrap_lever_close_sound_1PlaySound0-1"
							cmd8 = "flametrap_fire_ignitorEnable0-1"
							cmd9 = "flametrap_fire_largeEnable0-1"
							cmd10 = "flametrap_fireEnable0-1"
							cmd11 = "hintFireUser401"
						}
					}
				}
			}
			flametrap_fire_ignitor = 
			{
				SpawnInfo =
				{
					classname = "env_fire"
					damagescale = "1.0"
					fireattack = ".1"
					firesize = "16"
					health = "6"
					ignitionpoint = "1"
					spawnflags = "258"
					StartDisabled = "1"
					targetname = "flametrap_fire_ignitor"
					origin = Vector( -1.99994, 39, 31 )
					connections =
					{
						OnExtinguished =
						{
							cmd1 = "flametrap_ignite_sound_2StopSound0-1"
						}
						OnIgnited =
						{
							cmd1 = "flametrap_ignite_sound_2PlaySound1-1"
							cmd2 = "!selfDisable6-1"
						}
					}
				}
			}
			flametrap_ignitor_sparks = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( -30, 90, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "fireworks_sparkshower_01"
					render_in_front = "0"
					start_active = "0"
					targetname = "flametrap_ignitor_sparks"
					origin = Vector( -1.99994, 25, 27 )
				}
			}
			flametrap_ignitor_flames = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( -90, 90, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "fire_jet_01"
					render_in_front = "0"
					start_active = "0"
					targetname = "flametrap_ignitor_flames"
					origin = Vector( -5.99994, 11, 110 )
				}
			}
			flametrap_ignite_sound_1 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "Inferno.Fire.Ignite"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "flametrap_ignite_sound_1"
					origin = Vector( -2.99994, 37, 52 )
				}
			}
			flametrap_ignite_sound_2 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "airport.crashfire"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "16"
					targetname = "flametrap_ignite_sound_2"
					origin = Vector( -2.99994, 33, 42 )
				}
			}
			flametrap_spark_sound_1 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "ambient.electrical_zap_6"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "flametrap_spark_sound_1"
					origin = Vector( -2.99994, 33, 68 )
				}
			}
			flametrap_lever_close_sound_1 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "WAM.StartUp"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "flametrap_lever_close_sound_1"
					origin = Vector( -5.99994, -9.99997, 101.237 )
				}
			}
			flametrap_lever_close_sound_11 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "Metal_Barrel.BulletImpact"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "flametrap_lever_close_sound_1"
					origin = Vector( -5.99994, -9.99997, 85 )
				}
			}
			flametrap_lever_open_sound_1 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "Metal.SawbladeStick"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "flametrap_lever_open_sound_1"
					origin = Vector( -5.99994, 1, 93 )
				}
			}
			flametrap_lever_open_sound_11 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "Buttons.snd37"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "flametrap_lever_open_sound_1"
					origin = Vector( -5.99994, 1, 107 )
				}
			}
			filter_tank = 
			{
				SpawnInfo =
				{
					classname = "filter_activator_infected_class"
					filterinfectedclass = "8"
					Negated = "Allow entities that match criteria"
					targetname = "@filter_tank"
					origin = Vector( -4.42093, 35, 83.2417 )
				}
			}
			flametrap_fuel_gauge_needle = 
			{
				SpawnInfo =
				{
					classname = "momentary_rot_button"
					angles = Vector( 0, 0, 0 )
					disablereceiveshadows = "0"
					disableX360 = "0"
					distance = "-180"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					origin = Vector( 23.5, 0, 70 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					returnspeed = "0"
					solidbsp = "0"
					sounds = "0"
					spawnflags = "97"
					speed = "50"
					startdirection = "-1"
					startposition = "0"
					targetname = "flametrap_fuel_gauge_needle"
				}
			}
			flametrap_target_model = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 180, 180 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_buildables/trigger_arm.mdl"
					parentname = "flametrap_target_arm"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "flametrap_target_model"
					origin = Vector( -17, 11, 110 )
					connections =
					{
						OnTakeDamage =
						{
							cmd1 = "flametrap_pour_targetRunScriptCodeStartFireTrap()0-1"
						}
					}
				}
			}
			unnamed2 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					health = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_buildables/needle.mdl"
					parentname = "flametrap_fuel_gauge_needle"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					origin = Vector( 24, 0, 70 )
				}
			}
			unnamed3 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( -90, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_buildables/bracket.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					origin = Vector( -17, 11, 110 )
					connections =
					{
						OnTakeDamage =
						{
							cmd1 = "flametrap_pour_targetRunScriptCodeStartFireTrap()0-1"
						}
					}
				}
			}
			flametrap_pipe_point = 
			{
				SpawnInfo =
				{
					classname = "info_target"
					angles = Vector( 0, 90, 0 )
					targetname = "flametrap_pipe_point"
					origin = Vector( -2, 32, 32 )
					connections =
					{
						OnUser1 =
						{
							cmd1 = "flametrap_fire_ignitorStartFire0.3-1"
						}
					}
				}
			}
			hint = 
			{
				SpawnInfo =
				{
					classname = "env_instructor_hint"
					hint_allow_nodraw_target = "1"
					hint_alphaoption = "0"
					hint_auto_start = "0"
					hint_caption = "Shoot to activate!"
					hint_color = "255 255 255"
					hint_display_limit = "2"
					hint_forcecaption = "0"
					hint_icon_offscreen = "icon_info"
					hint_icon_offset = "0"
					hint_icon_onscreen = "icon_alert_red"
					hint_instance_type = "2"
					hint_name = "firewall_trap_lesson"
					hint_nooffscreen = "1"
					hint_pulseoption = "0"
					hint_range = "500"
					hint_shakeoption = "0"
					hint_static = "0"
					hint_suppress_rest = "1"
					hint_target = "flametrap_target_model"
					hint_timeout = "0"
					targetname = "hint"
					origin = Vector( -6, 14, 128.292 )
					connections =
					{
						OnUser4 =
						{
							cmd1 = "!selfEndHint0-1"
							cmd2 = "!selfKill0.01-1"
						}
					}
				}
			}
			hint_branch = 
			{
				SpawnInfo =
				{
					classname = "logic_branch"
					InitialValue = "$show_hint"
					targetname = "hint_branch"
					origin = Vector( -6, 14, 128.292 )
					connections =
					{
						OnFalse =
						{
							cmd1 = "!selfKill0-1"
							cmd2 = "hintFireUser40-1"
						}
						OnTrue =
						{
							cmd1 = "!selfKill0.1-1"
						}
					}
				}
			}
			unnamed4 = 
			{
				SpawnInfo =
				{
					classname = "logic_auto"
					spawnflags = "1"
					origin = Vector( -6, 14, 128.292 )
					connections =
					{
						OnMapSpawn =
						{
							cmd1 = "hint_branchTest0-1"
						}
					}
				}
			}
		} // SpawnTables

		ReplaceParmDefaults =
		{
			"$show_hint" : "0"
		}
	} // EntityGroup
} // FirewallTrap

RegisterEntityGroup( "FirewallTrap", FirewallTrap )
