//-------------------------------------------------------
// Autogenerated from 'firewall_pipe.vmf'
//-------------------------------------------------------
FirewallPipe <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.sprinkler,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.flametrap_fire4,
			EntityGroup.SpawnTables.flametrap_fire3,
			EntityGroup.SpawnTables.flametrap_fire2,
			EntityGroup.SpawnTables.flametrap_fire1,
			EntityGroup.SpawnTables.flametrap_fire,
			EntityGroup.SpawnTables.sprinkler,
			EntityGroup.SpawnTables.flametrap_pipe_point,
			EntityGroup.SpawnTables.flametrap_tank_ignite_trigger,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			flametrap_fire = 
			{
				SpawnInfo =
				{
					classname = "env_fire"
					damagescale = "1.0"
					fireattack = ".1"
					firesize = "64"
					health = "6"
					ignitionpoint = ".1"
					spawnflags = "258"
					StartDisabled = "1"
					targetname = "flametrap_fire"
					origin = Vector( -27, -7.15256e-007, 19 )
					connections =
					{
						OnIgnited =
						{
							cmd1 = "!selfDisable6-1"
						}
					}
				}
			}
			flametrap_fire1 = 
			{
				SpawnInfo =
				{
					classname = "env_fire"
					damagescale = "1.0"
					fireattack = ".1"
					firesize = "64"
					health = "6"
					ignitionpoint = ".1"
					spawnflags = "258"
					StartDisabled = "1"
					targetname = "flametrap_fire"
					origin = Vector( 25, -3.03984e-006, 19 )
					connections =
					{
						OnIgnited =
						{
							cmd1 = "!selfDisable6-1"
						}
					}
				}
			}
			flametrap_fire2 = 
			{
				SpawnInfo =
				{
					classname = "env_fire"
					damagescale = "1.0"
					fireattack = ".1"
					firesize = "64"
					health = "6"
					ignitionpoint = ".1"
					spawnflags = "258"
					StartDisabled = "1"
					targetname = "flametrap_fire"
					origin = Vector( 53, 2.563e-005, 19 )
					connections =
					{
						OnIgnited =
						{
							cmd1 = "!selfDisable6-1"
						}
					}
				}
			}
			flametrap_fire3 = 
			{
				SpawnInfo =
				{
					classname = "env_fire"
					damagescale = "1.0"
					fireattack = ".1"
					firesize = "128"
					health = "6"
					ignitionpoint = ".1"
					spawnflags = "256"
					StartDisabled = "1"
					targetname = "flametrap_fire"
					origin = Vector( 0, 0, 19 )
					connections =
					{
						OnExtinguished =
						{
							cmd1 = "flametrap_tank_ignite_triggerDisable0-1"
						}
						OnIgnited =
						{
							cmd1 = "!selfDisable6-1"
							cmd2 = "flametrap_tank_ignite_triggerEnable0-1"
						}
					}
				}
			}
			sprinkler = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 180, 0 )
					body = "0"
					disablereceiveshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_buildables/firetrap_pipe.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "sprinkler"
					updatechildren = "0"
					origin = Vector( 0, 0.195035, 0.3509 )
				}
			}
			flametrap_fire4 = 
			{
				SpawnInfo =
				{
					classname = "env_fire"
					damagescale = "1.0"
					fireattack = ".1"
					firesize = "64"
					health = "6"
					ignitionpoint = ".1"
					spawnflags = "258"
					StartDisabled = "1"
					targetname = "flametrap_fire"
					origin = Vector( -50, 2.38419e-007, 19 )
					connections =
					{
						OnIgnited =
						{
							cmd1 = "!selfDisable6-1"
						}
					}
				}
			}
			flametrap_pipe_point = 
			{
				SpawnInfo =
				{
					classname = "info_target"
					angles = Vector( 0, 90, 0 )
					spawnflags = "0"
					targetname = "flametrap_pipe_point"
					origin = Vector( 0, 0, 40 )
					connections =
					{
						OnUser1 =
						{
							cmd1 = "flametrap_fireStartFire0.3-1"
							cmd2 = "flametrap_fireEnable0-1"
						}
					}
				}
			}
			flametrap_tank_ignite_trigger = 
			{
				SpawnInfo =
				{
					classname = "script_trigger_multiple"
					allowghost = "0"
					allowincap = "0"
					entireteam = "0"
					filtername = "@filter_tank"
					origin = Vector( 0, 0, 42 )
					spawnflags = "1"
					StartDisabled = "1"
					targetname = "flametrap_tank_ignite_trigger"
					wait = "1"
					extent = Vector( 65, 16, 32 )
					connections =
					{
						OnStartTouch =
						{
							cmd1 = "!activatorignite0-1"
						}
					}
				}
			}
		} // SpawnTables
	} // EntityGroup
} // FirewallPipe

RegisterEntityGroup( "FirewallPipe", FirewallPipe )
