//-------------------------------------------------------
// Autogenerated from 'health_cabinet.vmf'
//-------------------------------------------------------
HealthCabinet <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.item,
			EntityGroup.SpawnTables.prop_item,
			EntityGroup.SpawnTables.prop_item1,
			EntityGroup.SpawnTables.item1,
			EntityGroup.SpawnTables.sign,
			EntityGroup.SpawnTables.health_cabinet,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.hint_branch,
			EntityGroup.SpawnTables.health_cabinet,
			EntityGroup.SpawnTables.relay_item_restock,
			EntityGroup.SpawnTables.use_target_cabinet,
			EntityGroup.SpawnTables.template_item,
			EntityGroup.SpawnTables.hint,
			EntityGroup.SpawnTables.prop_item1,
			EntityGroup.SpawnTables.prop_item,
			EntityGroup.SpawnTables.sign,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			item = 
			{
				SpawnInfo =
				{
					classname = "weapon_first_aid_kit_spawn"
					angles = Vector( 0, 180, -90 )
					body = "0"
					disableshadows = "0"
					model = "models/w_models/weapons/w_eq_defibrillator.mdl"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "item"
					origin = Vector( 1.12061, -1, -0.173374 )
				}
			}
			prop_item = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 180, -90 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/w_models/weapons/w_eq_medkit.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "prop_item"
					updatechildren = "0"
					origin = Vector( 1.12061, -1, -0.173374 )
				}
			}
			prop_item1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 180, -90 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/w_models/weapons/w_eq_medkit.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "prop_item"
					updatechildren = "0"
					origin = Vector( 1.12061, 9, -0.173374 )
				}
			}
			item1 = 
			{
				SpawnInfo =
				{
					classname = "weapon_first_aid_kit_spawn"
					angles = Vector( 0, 180, -90 )
					body = "0"
					disableshadows = "0"
					model = "models/w_models/weapons/w_eq_defibrillator.mdl"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "item"
					origin = Vector( 1.12061, 9, -0.173374 )
				}
			}
			template_item = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "2"
					targetname = "template_item"
					Template02 = "item"
					origin = Vector( 19.1206, 16, -0.736574 )
				}
			}
			relay_item_restock = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "1"
					StartDisabled = "0"
					targetname = "relay_item_restock"
					origin = Vector( 19.1206, -16, -0.736574 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "template_itemForceSpawn0-1"
							cmd2 = "prop_itemKill0-1"
							cmd3 = "health_cabinetSetAnimationOpen01"
							cmd4 = "template_itemKill0.1-1"
							cmd5 = "signKill0.1-1"
							cmd6 = "hintFireUser401"
						}
					}
				}
			}
			sign = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "78 184 41"
					glowrange = "240"
					glowrangemin = "0"
					glowstate = "3"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/buildable_button.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "sign"
					updatechildren = "0"
					origin = Vector( 1.12061, 1.6687e-007, -21.7366 )
				}
			}
			use_target_cabinet = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "sign"
					origin = Vector( 19.12, 0, -0.74 )
					targetname = "use_target_cabinet"
					vscripts = "usetargets/health_cabinet"
					connections =
					{
						OnUser1 =
						{
							cmd1 = "relay_item_restockTrigger0-1"
						}
					}
				}
			}
			health_cabinet = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/small_cabinet_firstaid.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "health_cabinet"
					updatechildren = "0"
					origin = Vector( 0.12061, 0, -8.73657 )
				}
			}
			hint = 
			{
				SpawnInfo =
				{
					classname = "env_instructor_hint"
					hint_allow_nodraw_target = "1"
					hint_alphaoption = "0"
					hint_auto_start = "1"
					hint_binding = "+use"
					hint_caption = "These healthkits are free!"
					hint_color = "255 255 255"
					hint_display_limit = "2"
					hint_forcecaption = "1"
					hint_icon_offscreen = "icon_tip"
					hint_icon_offset = "0"
					hint_icon_onscreen = "use_binding"
					hint_instance_type = "2"
					hint_name = "health_cabinet_lesson"
					hint_nooffscreen = "0"
					hint_pulseoption = "0"
					hint_range = "130"
					hint_shakeoption = "0"
					hint_static = "0"
					hint_suppress_rest = "1"
					hint_target = "cabinet"
					hint_timeout = "5"
					targetname = "hint"
					origin = Vector( -0.572197, -1.08785, 17.2634 )
					connections =
					{
						OnUser4 =
						{
							cmd1 = "!selfEndHint0-1"
							cmd2 = "!selfKill0.01-1"
						}
					}
				}
			}
			hint_branch = 
			{
				SpawnInfo =
				{
					classname = "logic_branch"
					InitialValue = "$show_hint"
					targetname = "hint_branch"
					origin = Vector( -0.572197, -1.08785, 17.2634 )
					connections =
					{
						OnFalse =
						{
							cmd1 = "!selfKill0-1"
							cmd2 = "hintFireUser40-1"
						}
						OnTrue =
						{
							cmd1 = "!selfKill0.1-1"
						}
					}
				}
			}
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "logic_auto"
					spawnflags = "1"
					origin = Vector( -0.572197, -1.08785, 17.2634 )
					connections =
					{
						OnMapSpawn =
						{
							cmd1 = "hint_branchTest0-1"
						}
					}
				}
			}
		} // SpawnTables

		ReplaceParmDefaults =
		{
			"$show_hint" : "0"
		}
	} // EntityGroup
} // HealthCabinet

RegisterEntityGroup( "HealthCabinet", HealthCabinet )
