//-------------------------------------------------------
// Autogenerated from 'ladder.vmf'
//-------------------------------------------------------
Ladder <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.ladder_1_model,
			EntityGroup.SpawnTables.ladder_1_rungs,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.ladder_128_target,
			EntityGroup.SpawnTables.ladder_1_nav_blocker,
			EntityGroup.SpawnTables.ladder_1_spawn_trigger,
			EntityGroup.SpawnTables.filter_survivor,
			EntityGroup.SpawnTables.ladder_1_model,
			EntityGroup.SpawnTables.ladder_1_spawn_timer,
			EntityGroup.SpawnTables.ladder_1_spawn_relay,
			EntityGroup.SpawnTables.ladder_1_rungs,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			ladder_1_model = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					disableshadows = "1"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_vehicles/train_ladder.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "0"
					StartDisabled = "1"
					targetname = "ladder_1_model"
					origin = Vector( 6.00815e-005, 4.76837e-007, 0 )
				}
			}
			ladder_1_nav_blocker = 
			{
				SpawnInfo =
				{
					classname = "script_nav_blocker"
					affectsFlow = "1"
					StartDisabled = "0"
					targetname = "ladder_1_nav_blocker"
					teamToBlock = "-1"
					extent = Vector( 13.5, 10, 66 )
					origin = Vector( 0.5, -5, 66 )
				}
			}
			ladder_1_spawn_trigger = 
			{
				SpawnInfo =
				{
					classname = "script_trigger_multiple"
					allowghost = "0"
					allowincap = "0"
					entireteam = "0"
					filtername = "survivor_filter"
					origin = Vector( 0.5, -23.75, 65.35 )
					spawnflags = "1"
					StartDisabled = "0"
					targetname = "ladder_1_spawn_trigger"
					wait = "0"
					extent = Vector( 13.5, 10, 65 )
					connections =
					{
						OnNotTouching =
						{
							cmd1 = "ladder_1_spawn_timerEnable01"
							cmd2 = "ladder_1_spawn_timerKill01"
							cmd3 = "ladder_1_nav_blockerUnblockNav0.11"
							cmd4 = "ladder_1_modelEnable01"
							cmd5 = "ladder_1_rungsEnableCollision01"
						}
					}
				}
			}
			ladder_1_spawn_timer = 
			{
				SpawnInfo =
				{
					classname = "logic_timer"
					RefireTime = ".3"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "ladder_1_spawn_timer"
					origin = Vector( -4.76837e-007, -21, 8 )
					connections =
					{
						OnTimer =
						{
							cmd1 = "ladder_1_spawn_triggerTouchTest0-1"
						}
					}
				}
			}
			filter_survivor = 
			{
				SpawnInfo =
				{
					classname = "filter_activator_team"
					filterteam = "2"
					Negated = "Allow entities that match criteria"
					targetname = "filter_survivor"
					origin = Vector( -4.76837e-007, -21, 24 )
				}
			}
			ladder_128_target = 
			{
				SpawnInfo =
				{
					classname = "info_target"
					angles = Vector( 0, 0, 0 )
					targetname = "ladder_128_target"
					origin = Vector( -4.76837e-007, -21, 42 )
					connections =
					{
						OnUser1 =
						{
							cmd1 = "ladder_1_spawn_timerEnable0-1"
						}
					}
				}
			}
			ladder_1_spawn_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					targetname = "ladder_1_spawn_relay"
					origin = Vector( -4.76837e-007, -21, 59 )
					connections =
					{
						OnSpawn =
						{
							cmd1 = "ladder_1_rungsDisableCollision0-1"
						}
					}
				}
			}
			ladder_1_rungs = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_buildables/ladder.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "ladder_1_rungs"
					origin = Vector( 0, -1.6406, -1.3203 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // Ladder

RegisterEntityGroup( "Ladder", Ladder )
