//-------------------------------------------------------
// Autogenerated from 'life_preserver.vmf'
//-------------------------------------------------------
LifePreserver <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.button,
			EntityGroup.SpawnTables.life_preserver_train_model,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.life_preserver_pathtrack_template,
			EntityGroup.SpawnTables.life_preserver_water_splash_sound_2,
			EntityGroup.SpawnTables.life_preserver_throw_sound_1,
			EntityGroup.SpawnTables.life_preserver_waterparticles_maker_1,
			EntityGroup.SpawnTables.life_preserver_special_spawner,
			EntityGroup.SpawnTables.life_preserver_waterparticles_template,
			EntityGroup.SpawnTables.life_preserver_water_splash_sound_1,
			EntityGroup.SpawnTables.life_preserver_usetarget,
			EntityGroup.SpawnTables.preserver_throw_relay,
			EntityGroup.SpawnTables.life_preserver_waterparticles_maker_2,
			EntityGroup.SpawnTables.button,
			EntityGroup.SpawnTables.life_preserver_train_template,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			button = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowstate = "3"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_urban/life_ring001.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					targetname = "button"
					origin = Vector( 0, 0, 2 )
				}
			}
			life_preserver_usetarget = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "button"
					origin = Vector( 0, 0, 8 )
					targetname = "life_preserver_usetarget"
					vscripts = "usetargets/life_preserver_usetarget"
					connections =
					{
						OnUser1 =
						{
							cmd1 = "!selfRunScriptCodeSetUnAvailable()0-1"
							cmd2 = "preserver_throw_relayTrigger0-1"
						}
						OnUser3 =
						{
							cmd1 = "life_preserver_special_spawnerSpawnZombiejockey0-1"
						}
					}
				}
			}
			preserver_throw_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "preserver_throw_relay"
					origin = Vector( 0, 0, 24 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "life_preserver_pathtrack_templateForceSpawn0-1"
							cmd2 = "life_preserver_throw_sound_1PlaySound0-1"
						}
					}
				}
			}
			life_preserver_train = 
			{
				SpawnInfo =
				{
					classname = "func_tracktrain"
					bank = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					dmg = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					height = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					MoveSoundMaxPitch = "200"
					MoveSoundMaxTime = "0"
					MoveSoundMinPitch = "60"
					MoveSoundMinTime = "0"
					orientationtype = "1"
					origin = Vector( 0, 0, 4 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					spawnflags = "522"
					speed = "0"
					startspeed = "600"
					target = "life_preserver_train_path_1"
					targetname = "life_preserver_train"
					velocitytype = "0"
					volume = "10"
					wheels = "50"
				}
			}
			life_preserver_train_model = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowstate = "3"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_urban/life_ring001.mdl"
					parentname = "life_preserver_train_model_rotator"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					targetname = "life_preserver_train_model"
					origin = Vector( 0, 0, 4 )
				}
			}
			life_preserver_train_path_1 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					target = "life_preserver_train_path_3"
					targetname = "life_preserver_train_path_1"
					origin = Vector( 0, 0, 4 )
				}
			}
			life_preserver_train_path_3 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					spawnflags = "0"
					target = "life_preserver_train_path_6"
					targetname = "life_preserver_train_path_3"
					origin = Vector( 245, 0, 9 )
				}
			}
			life_preserver_train_path_6 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					target = "life_preserver_train_path_7"
					targetname = "life_preserver_train_path_6"
					origin = Vector( 464, 0, -21 )
				}
			}
			life_preserver_train_path_7 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					speed = "100"
					target = "life_preserver_train_path_8"
					targetname = "life_preserver_train_path_7"
					origin = Vector( 573, 0, -45 )
					connections =
					{
						OnPass =
						{
							cmd1 = "life_preserver_waterparticles_maker_1ForceSpawn0-1"
							cmd2 = "life_preserver_water_splash_sound_1PlaySound0-1"
						}
					}
				}
			}
			life_preserver_train_path_8 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					spawnflags = "0"
					speed = "50"
					target = "life_preserver_train_path_10"
					targetname = "life_preserver_train_path_8"
					origin = Vector( 613, 0, -61 )
					connections =
					{
						OnPass =
						{
							cmd1 = "life_preserver_train_model_rotatorStopAtStartPos0.1-1"
						}
					}
				}
			}
			life_preserver_train_path_10 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					spawnflags = "0"
					speed = "100"
					target = "life_preserver_train_path_14"
					targetname = "life_preserver_train_path_10"
					origin = Vector( 648, 0, -45 )
				}
			}
			life_preserver_train_path_14 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					target = "life_preserver_train_path_15"
					targetname = "life_preserver_train_path_14"
					origin = Vector( 64, 0, -45 )
				}
			}
			life_preserver_train_path_15 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					spawnflags = "0"
					target = "life_preserver_train_path_16"
					targetname = "life_preserver_train_path_15"
					origin = Vector( 55, 0, 3 )
				}
			}
			life_preserver_train_path_16 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					target = "life_preserver_train_path_17"
					targetname = "life_preserver_train_path_16"
					origin = Vector( 0, 0, 4 )
					connections =
					{
						OnPass =
						{
							cmd1 = "life_preserver_usetargetRunScriptCodePreserverPulledFromWater()0-1"
							cmd2 = "life_preserver_train_destructor_relayTrigger0-1"
							cmd3 = "life_preserver_waterparticles_maker_2ForceSpawn0-1"
							cmd4 = "life_preserver_water_splash_sound_2PlaySound0-1"
						}
					}
				}
			}
			life_preserver_train_template = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "2"
					targetname = "life_preserver_train_template"
					Template01 = "life_preserver_train"
					Template03 = "life_preserver_train_model"
					Template04 = "life_preserver_train_destructor_relay"
					Template05 = "life_preserver_train_model_rotator"
					Template06 = "life_preserver_rope_1"
					Template07 = "life_preserver_rope_2"
					origin = Vector( 0, 0, 56 )
					connections =
					{
						OnEntitySpawned =
						{
							cmd1 = "life_preserver_trainStartForward0.1-1"
							cmd2 = "life_preserver_train_model_rotatorStart0.1-1"
						}
					}
				}
			}
			life_preserver_train_path_17 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					targetname = "life_preserver_train_path_17"
					origin = Vector( -16, 0, 4 )
				}
			}
			life_preserver_train_destructor_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "life_preserver_train_destructor_relay"
					origin = Vector( 0, 0, 40 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "!selfKill0-1"
							cmd2 = "life_preserver_trainKill0-1"
							cmd3 = "life_preserver_train_modelKill0-1"
							cmd4 = "life_preserver_train_path*Kill0-1"
							cmd5 = "life_preserver_rope_*Kill0-1"
						}
					}
				}
			}
			life_preserver_train_model_rotator = 
			{
				SpawnInfo =
				{
					classname = "func_rotating"
					angles = Vector( 0, 0, 0 )
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					dmg = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					fanfriction = "1"
					maxcpulevel = "0"
					maxgpulevel = "0"
					maxspeed = "100"
					mincpulevel = "0"
					mingpulevel = "0"
					origin = Vector( 0, 0, 4 )
					parentname = "life_preserver_train"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					solidbsp = "0"
					spawnflags = "64"
					targetname = "life_preserver_train_model_rotator"
					volume = "10"
				}
			}
			life_preserver_pathtrack_template = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "2"
					targetname = "life_preserver_pathtrack_template"
					Template01 = "life_preserver_train_path_1"
					Template02 = "life_preserver_train_path_3"
					Template03 = "life_preserver_train_path_6"
					Template04 = "life_preserver_train_path_7"
					Template05 = "life_preserver_train_path_8"
					Template06 = "life_preserver_train_path_10"
					Template07 = "life_preserver_train_path_15"
					Template08 = "life_preserver_train_path_16"
					Template09 = "life_preserver_train_path_17"
					Template10 = "life_preserver_train_path_14"
					origin = Vector( 16, 0, 56 )
					connections =
					{
						OnEntitySpawned =
						{
							cmd1 = "life_preserver_train_templateForceSpawn0-1"
						}
					}
				}
			}
			life_preserver_rope_1 = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 0, 0 )
					MoveSpeed = "64"
					NextKey = "life_preserver_rope_2"
					PositionInterpolator = "2"
					RopeMaterial = "cable/rope"
					Slack = "25"
					spawnflags = "1"
					Subdiv = "2"
					targetname = "life_preserver_rope_1"
					TextureScale = "1"
					Width = "2"
					origin = Vector( 6, 0, -8 )
				}
			}
			life_preserver_rope_2 = 
			{
				SpawnInfo =
				{
					classname = "keyframe_rope"
					angles = Vector( 0, 0, 0 )
					MoveSpeed = "64"
					parentname = "life_preserver_train_model"
					RopeMaterial = "cable/rope"
					Slack = "25"
					spawnflags = "1"
					Subdiv = "2"
					targetname = "life_preserver_rope_2"
					TextureScale = "1"
					Width = "2"
					origin = Vector( 16, 0, 4 )
				}
			}
			life_preserver_water_splash_1 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1 = "life_preserver_water_splash_1_target"
					cpoint2 = "life_preserver_water_splash_2_target"
					cpoint3 = "life_preserver_water_splash_3_target"
					cpoint4 = "life_preserver_water_splash_4_target"
					cpoint5 = "life_preserver_water_splash_5_target"
					effect_name = "large_water_splash"
					start_active = "1"
					targetname = "life_preserver_water_splash_1"
					origin = Vector( 620, 0, -8 )
				}
			}
			life_preserver_water_splash_3_target = 
			{
				SpawnInfo =
				{
					classname = "info_particle_target"
					angles = Vector( 0, 0, 0 )
					targetname = "life_preserver_water_splash_3_target"
					origin = Vector( 572, 0, -196 )
				}
			}
			life_preserver_water_splash_4_target = 
			{
				SpawnInfo =
				{
					classname = "info_particle_target"
					angles = Vector( 0, 0, 0 )
					targetname = "life_preserver_water_splash_4_target"
					origin = Vector( 572, 0, -176 )
				}
			}
			life_preserver_water_splash_1_target = 
			{
				SpawnInfo =
				{
					classname = "info_particle_target"
					angles = Vector( 0, 0, 0 )
					targetname = "life_preserver_water_splash_1_target"
					origin = Vector( 572, 0, -44 )
				}
			}
			life_preserver_water_splash_2_target = 
			{
				SpawnInfo =
				{
					classname = "info_particle_target"
					angles = Vector( 0, 0, 0 )
					targetname = "life_preserver_water_splash_2_target"
					origin = Vector( 572, 0, -216 )
				}
			}
			life_preserver_water_splash_5_target = 
			{
				SpawnInfo =
				{
					classname = "info_particle_target"
					angles = Vector( 0, 0, 0 )
					targetname = "life_preserver_water_splash_5_target"
					origin = Vector( 572, 0, -156 )
				}
			}
			life_preserver_waterparticles_template = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "0"
					targetname = "life_preserver_waterparticles_template"
					Template01 = "life_preserver_water_splash_relay"
					Template08 = "life_preserver_water_splash_1"
					Template09 = "life_preserver_water_splash_1_target"
					Template10 = "life_preserver_water_splash_2_target"
					Template11 = "life_preserver_water_splash_3_target"
					Template12 = "life_preserver_water_splash_4_target"
					Template13 = "life_preserver_water_splash_5_target"
					origin = Vector( 572, 0, -44 )
				}
			}
			life_preserver_waterparticles_maker_1 = 
			{
				SpawnInfo =
				{
					classname = "env_entity_maker"
					angles = Vector( 0, 0, 0 )
					EntityTemplate = "life_preserver_waterparticles_template"
					PostSpawnDirection = "0 0 0"
					PostSpawnDirectionVariance = "0"
					PostSpawnInheritAngles = "0"
					PostSpawnSpeed = "0"
					spawnflags = "0"
					targetname = "life_preserver_waterparticles_maker_1"
					origin = Vector( 572, 0, -44 )
				}
			}
			life_preserver_waterparticles_maker_2 = 
			{
				SpawnInfo =
				{
					classname = "env_entity_maker"
					angles = Vector( 0, 0, 0 )
					EntityTemplate = "life_preserver_waterparticles_template"
					PostSpawnDirection = "0 0 0"
					PostSpawnDirectionVariance = "0"
					PostSpawnInheritAngles = "0"
					PostSpawnSpeed = "0"
					spawnflags = "0"
					targetname = "life_preserver_waterparticles_maker_2"
					origin = Vector( 0, 0, 4 )
				}
			}
			life_preserver_water_splash_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "1"
					targetname = "life_preserver_water_splash_relay"
					origin = Vector( 572, 0, -24 )
					connections =
					{
						OnSpawn =
						{
							cmd1 = "life_preserver_water_splash_1Kill3-1"
							cmd2 = "life_preserver_water_splash_5_targetKill3-1"
							cmd3 = "life_preserver_water_splash_4_targetKill3-1"
							cmd4 = "life_preserver_water_splash_3_targetKill3-1"
							cmd5 = "life_preserver_water_splash_2_targetKill3-1"
							cmd6 = "life_preserver_water_splash_1_targetKill3-1"
							cmd7 = "life_preserver_water_splash_soundKill3-1"
						}
					}
				}
			}
			life_preserver_water_splash_sound_1 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "Physics.WaterSplash"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "life_preserver_water_splash_sound_1"
					origin = Vector( 104, 0, 32 )
				}
			}
			life_preserver_water_splash_sound_2 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "Physics.WaterSplash"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "life_preserver_water_splash_sound_2"
					origin = Vector( 12.4306, -0.331052, 14 )
				}
			}
			life_preserver_throw_sound_1 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "Claw.Swing"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "life_preserver_throw_sound_1"
					origin = Vector( 20.4306, -0.331052, 46 )
				}
			}
			life_preserver_special_spawner = 
			{
				SpawnInfo =
				{
					classname = "commentary_zombie_spawner"
					angles = Vector( 0, 0, 0 )
					targetname = "life_preserver_special_spawner"
					origin = Vector( 0, 0, 0 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // LifePreserver

RegisterEntityGroup( "LifePreserver", LifePreserver )
