//-------------------------------------------------------
// Autogenerated from 'rescue_helicopter.vmf'
//-------------------------------------------------------
RescueHelicopter <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.rescue_chopper_model,
			EntityGroup.SpawnTables.chopper_gun,
			EntityGroup.SpawnTables.chopper_gun1,
			EntityGroup.SpawnTables.finale_trigger,
			EntityGroup.SpawnTables.finale_box,
			EntityGroup.SpawnTables.ladder_1_model,
			EntityGroup.SpawnTables.ladder_1_rungs,
			EntityGroup.SpawnTables.ladder_1_model1,
			EntityGroup.SpawnTables.ladder_1_rungs1,
			EntityGroup.SpawnTables.ladder_1_rungs2,
			EntityGroup.SpawnTables.ladder_1_rungs3,
			EntityGroup.SpawnTables.ladder_1_rungs4,
			EntityGroup.SpawnTables.ladder_1_rungs5,
			EntityGroup.SpawnTables.ladder_1_rungs6,
			EntityGroup.SpawnTables.ladder_1_rungs7,
			EntityGroup.SpawnTables.ladder_1_rungs8,
			EntityGroup.SpawnTables.ladder_1_rungs9,
			EntityGroup.SpawnTables.ladder_1_rungs10,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.cleanup_chopper_basket_relay,
			EntityGroup.SpawnTables.rescue_chopper_train_path_5,
			EntityGroup.SpawnTables.rescue_chopper_train_path_7,
			EntityGroup.SpawnTables.rescue_chopper_lower_basket_relay,
			EntityGroup.SpawnTables.rescue_chopper_train_path_3,
			EntityGroup.SpawnTables.rescue_chopper_template,
			EntityGroup.SpawnTables.rescue_chopper_maker,
			EntityGroup.SpawnTables.rescue_chopper_hover_sound,
			EntityGroup.SpawnTables.rescue_chopper_train_path_4,
			EntityGroup.SpawnTables.train_camera,
			EntityGroup.SpawnTables.finale_ents_template,
			EntityGroup.SpawnTables.spawn_finale_ents_relay,
			EntityGroup.SpawnTables.rescue_chopper_script,
			EntityGroup.SpawnTables.ladder_1_push_trigger,
			EntityGroup.SpawnTables.rescue_chopper_destructor_relay,
			EntityGroup.SpawnTables.rescue_chopper_start_relay,
			EntityGroup.SpawnTables.rescue_chopper_train_path_6,
			EntityGroup.SpawnTables.rescue_chopper_sound,
			EntityGroup.SpawnTables.rescue_chopper_train_path_1,
			EntityGroup.SpawnTables.rescue_chopper_train_path_2,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			rescue_chopper_model = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					DefaultAnim = "hover"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_vehicles/chopper_generic.mdl"
					parentname = "rescue_chopper_train"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "rescue_chopper_model"
					origin = Vector( -6, 43, 235 )
				}
			}
			rescue_chopper_train_path_1 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					target = "rescue_chopper_train_path_2"
					targetname = "rescue_chopper_train_path_1"
					origin = Vector( -3020, 42.996, 420 )
				}
			}
			rescue_chopper_train_path_2 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					target = "rescue_chopper_train_path_3"
					targetname = "rescue_chopper_train_path_2"
					origin = Vector( -2400, 42.996, 420 )
				}
			}
			rescue_chopper_train_path_3 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					target = "rescue_chopper_train_path_4"
					targetname = "rescue_chopper_train_path_3"
					origin = Vector( -928, 42.996, 420 )
				}
			}
			rescue_chopper_train_path_4 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					spawnflags = "0"
					target = "rescue_chopper_train_path_5"
					targetname = "rescue_chopper_train_path_4"
					origin = Vector( -32, 42.996, 420 )
					connections =
					{
						OnPass =
						{
							cmd1 = "!activatorStop0-1"
							cmd2 = "rescue_chopper_lower_basket_relayTrigger0-1"
							cmd3 = "rescue_chopper_hover_soundPlaySound0-1"
						}
					}
				}
			}
			rescue_chopper_train_path_5 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					target = "rescue_chopper_train_path_6"
					targetname = "rescue_chopper_train_path_5"
					origin = Vector( -8, 42.996, 420 )
					connections =
					{
						OnPass =
						{
							cmd1 = "rescue_chopper_hover_soundStopSound01"
							cmd2 = "rescue_chopper_soundPlaySound01"
						}
					}
				}
			}
			rescue_chopper_train_path_6 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					target = "rescue_chopper_train_path_7"
					targetname = "rescue_chopper_train_path_6"
					origin = Vector( 3264, 42.996, 420 )
					connections =
					{
						OnPass =
						{
							cmd1 = "!activatorKill0.05-1"
						}
					}
				}
			}
			rescue_chopper_start_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "rescue_chopper_start_relay"
					origin = Vector( -32, 42.996, 480 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "rescue_chopper_trainStartForward0.2-1"
							cmd2 = "rescue_chopper_soundPlaySound0-1"
							cmd3 = "rescue_chopper_makerForceSpawn0-1"
						}
					}
				}
			}
			rescue_chopper_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "c2.outro.chopperleave"
					pitch = "100"
					pitchstart = "100"
					radius = "4779"
					spawnflags = "48"
					targetname = "rescue_chopper_sound"
					origin = Vector( -32, 42.996, 438.75 )
				}
			}
			rescue_chopper_train_path_7 = 
			{
				SpawnInfo =
				{
					classname = "path_track"
					angles = Vector( 0, 0, 0 )
					orientationtype = "1"
					targetname = "rescue_chopper_train_path_7"
					origin = Vector( 3312, 42.996, 420 )
				}
			}
			rescue_chopper_train = 
			{
				SpawnInfo =
				{
					classname = "func_tracktrain"
					bank = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					dmg = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					height = "4"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					MoveSoundMaxPitch = "200"
					MoveSoundMaxTime = "0"
					MoveSoundMinPitch = "60"
					MoveSoundMinTime = "0"
					orientationtype = "1"
					origin = Vector( -32, 43, 420 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					spawnflags = "523"
					speed = "0"
					startspeed = "500"
					target = "rescue_chopper_train_path_1"
					targetname = "rescue_chopper_train"
					velocitytype = "0"
					volume = "10"
					wheels = "50"
				}
			}
			rescue_chopper_script = 
			{
				SpawnInfo =
				{
					classname = "logic_script"
					Group00 = "rescue_chopper_start_relay"
					Group01 = "rescue_chopper_destructor_relay"
					Group02 = "rescue_chopper_team_trigger"
					Group03 = "spawn_finale_ents_relay"
					Group04 = "cleanup_chopper_basket_relay"
					targetname = "rescue_chopper_script"
					vscripts = "rescue_helicopter"
					origin = Vector( -32, 43, 521 )
				}
			}
			rescue_chopper_template = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "2"
					targetname = "rescue_chopper_template"
					Template01 = "rescue_chopper_model"
					Template02 = "rescue_chopper_train"
					Template03 = "ladder_1_spawn_trigger"
					Template04 = "ladder_1_spawn_timer"
					Template05 = "filter_survivor"
					Template06 = "ladder_1_spawn_relay"
					Template07 = "ladder_1_rungs"
					Template08 = "ladder_1_model"
					Template13 = "chopper_gun"
					Template14 = "rescue_chopper_team_trigger"
					origin = Vector( -32, 42.996, 498 )
				}
			}
			rescue_chopper_maker = 
			{
				SpawnInfo =
				{
					classname = "env_entity_maker"
					angles = Vector( 0, 0, 0 )
					EntityTemplate = "rescue_chopper_template"
					PostSpawnDirection = "0 0 0"
					PostSpawnDirectionVariance = "0"
					PostSpawnInheritAngles = "0"
					PostSpawnSpeed = "0"
					spawnflags = "0"
					targetname = "rescue_chopper_maker"
					origin = Vector( -3020, 42.996, 474 )
				}
			}
			rescue_chopper_lower_basket_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					targetname = "rescue_chopper_lower_basket_relay"
					origin = Vector( -49, 42, 214 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "ladder_1_spawn_timerEnable0-1"
							cmd2 = "chopper_gunEnable0-1"
							cmd3 = "ladder_1_modelEnable0-1"
							cmd4 = "ladder_1_push_triggerEnable0-1"
							cmd5 = "rescue_chopper_team_triggerEnable0-1"
						}
					}
				}
			}
			rescue_chopper_hover_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "c2m3.chopper_sounds"
					pitch = "100"
					pitchstart = "100"
					radius = "4779"
					spawnflags = "48"
					targetname = "rescue_chopper_hover_sound"
					origin = Vector( -48, 42.996, 438.75 )
				}
			}
			chopper_gun = 
			{
				SpawnInfo =
				{
					classname = "prop_minigun_l4d1"
					angles = Vector( 0, 43, 0 )
					disableshadows = "1"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "1536"
					fademindist = "1280"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MaxPitch = "60"
					MaxYaw = "90"
					MinAnimTime = "5"
					MinPitch = "-30"
					model = "models/w_models/weapons/w_minigun.mdl"
					parentname = "rescue_chopper_train"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "chopper_gun"
					origin = Vector( -4, 86, 271.434 )
				}
			}
			chopper_gun1 = 
			{
				SpawnInfo =
				{
					classname = "prop_minigun_l4d1"
					angles = Vector( 0, 223, 0 )
					disableshadows = "1"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "1536"
					fademindist = "1280"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MaxPitch = "60"
					MaxYaw = "90"
					MinAnimTime = "5"
					MinPitch = "-30"
					model = "models/w_models/weapons/w_minigun.mdl"
					parentname = "rescue_chopper_train"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "chopper_gun"
					origin = Vector( -24, 3, 272.434 )
				}
			}
			survivor_pos4 = 
			{
				SpawnInfo =
				{
					classname = "info_survivor_position"
					angles = Vector( 0, 0, 0 )
					Order = "4"
					targetname = "survivor_pos4"
					origin = Vector( -3346.05, 23, 440 )
				}
			}
			survivor_pos3 = 
			{
				SpawnInfo =
				{
					classname = "info_survivor_position"
					angles = Vector( 0, 0, 0 )
					Order = "3"
					targetname = "survivor_pos3"
					origin = Vector( -3342.05, 99, 440 )
				}
			}
			survivor_pos1 = 
			{
				SpawnInfo =
				{
					classname = "info_survivor_position"
					angles = Vector( 0, 0, 0 )
					Order = "1"
					targetname = "survivor_pos1"
					origin = Vector( -3290.05, 83, 440 )
				}
			}
			survivor_pos2 = 
			{
				SpawnInfo =
				{
					classname = "info_survivor_position"
					angles = Vector( 0, 0, 0 )
					Order = "2"
					targetname = "survivor_pos2"
					origin = Vector( -3288, 10.99, 440 )
				}
			}
			finale_ents_template = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "2"
					targetname = "finale_ents_template"
					Template01 = "finale_trigger"
					Template02 = "survivor_pos1"
					Template03 = "survivor_pos2"
					Template04 = "survivor_pos3"
					Template05 = "survivor_pos4"
					Template06 = "gameinstructor_disable"
					Template07 = "outtro"
					Template08 = "escape_relay"
					Template09 = "fade_outro_1"
					Template10 = "fade_outro_2"
					Template11 = "fade_outro_3"
					Template12 = "finale_box"
					origin = Vector( -3360, -21, 433 )
					connections =
					{
						OnEntitySpawned =
						{
							cmd1 = "escape_relayTrigger0-1"
						}
					}
				}
			}
			finale_trigger = 
			{
				SpawnInfo =
				{
					classname = "trigger_finale"
					angles = Vector( 0, 0, 0 )
					disableshadows = "1"
					model = "models/props/terror/hamradio.mdl"
					skin = "0"
					targetname = "finale_trigger"
					VersusTravelCompletion = "0.2"
					origin = Vector( -3328, -37, 425 )
				}
			}
			gameinstructor_disable = 
			{
				SpawnInfo =
				{
					classname = "info_game_event_proxy"
					event_name = "gameinstructor_nodraw"
					range = "150"
					spawnflags = "0"
					targetname = "gameinstructor_disable"
					origin = Vector( -3248, -13, 432 )
				}
			}
			outtro = 
			{
				SpawnInfo =
				{
					classname = "env_outtro_stats"
					targetname = "outtro"
					origin = Vector( -3248, -37, 432 )
				}
			}
			escape_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "escape_relay"
					origin = Vector( -3272, -21, 456 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "finale_triggerFinaleEscapeFinished01"
							cmd2 = "gameinstructor_disableGenerateGameEvent01"
							cmd3 = "outtroRollStatsCrawl71"
							cmd4 = "fade_outro_3Fade51"
							cmd5 = "train_cameraEnable0.31"
							cmd6 = "fade_outro_1Fade01"
							cmd7 = "rescue_chopper_trainStartForward0.31"
							cmd8 = "finale_triggerFinaleEscapeForceSurvivorPositions01"
						}
					}
				}
			}
			fade_outro_1 = 
			{
				SpawnInfo =
				{
					classname = "env_fade"
					duration = "0.2"
					holdtime = "0.3"
					renderamt = "255"
					rendercolor = "0 0 0"
					spawnflags = "0"
					targetname = "fade_outro_1"
					origin = Vector( -3304, -45, 434.214 )
					connections =
					{
						OnBeginFade =
						{
							cmd1 = "fade_outro_2Fade0.3-1"
						}
					}
				}
			}
			fade_outro_3 = 
			{
				SpawnInfo =
				{
					classname = "env_fade"
					duration = "0.3"
					renderamt = "255"
					rendercolor = "0 0 0"
					spawnflags = "8"
					targetname = "fade_outro_3"
					origin = Vector( -3272, -45, 434.214 )
				}
			}
			fade_outro_2 = 
			{
				SpawnInfo =
				{
					classname = "env_fade"
					duration = "0.2"
					renderamt = "255"
					rendercolor = "0 0 0"
					spawnflags = "1"
					targetname = "fade_outro_2"
					origin = Vector( -3288, -45, 434.214 )
				}
			}
			rescue_chopper_team_trigger = 
			{
				SpawnInfo =
				{
					classname = "script_trigger_multiple"
					allowghost = "0"
					allowincap = "0"
					entireteam = "2"
					origin = Vector( 0, 44.97, 304.04 )
					parentname = "rescue_chopper_train"
					spawnflags = "1"
					StartDisabled = "1"
					targetname = "rescue_chopper_team_trigger"
					wait = "1"
					extent = Vector( 72, 50, 28.041 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "rescue_chopper_scriptRunScriptCodeSurvivorInChopper()0-1"
						}
					}
				}
			}
			finale_box = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_placeable/entity_box.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					targetname = "finale_box"
					origin = Vector( -3299, 33, 370 )
				}
			}
			rescue_chopper_destructor_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "rescue_chopper_destructor_relay"
					origin = Vector( -32, 42.996, 464 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "*Kill0-1"
						}
					}
				}
			}
			spawn_finale_ents_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "spawn_finale_ents_relay"
					origin = Vector( -3288, -21, 456 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "finale_ents_templateForceSpawn0-1"
						}
					}
				}
			}
			cleanup_chopper_basket_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "cleanup_chopper_basket_relay"
					origin = Vector( -16, 42, 216 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "ladder_1_rungsKill0-1"
							cmd2 = "ladder_1_modelKill0-1"
						}
					}
				}
			}
			train_camera = 
			{
				SpawnInfo =
				{
					classname = "point_viewcontrol_multiplayer"
					angles = Vector( 0.00737499, 0, -1.31919 )
					fov = "70"
					fov_rate = "0"
					interp_time = "1.0"
					spawnflags = "1"
					targetname = "train_camera"
					origin = Vector( -925.749, 42.4439, 432.054 )
				}
			}
			ladder_1_model = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					disableshadows = "1"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_vehicles/train_ladder.mdl"
					parentname = "rescue_chopper_train"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "0"
					StartDisabled = "1"
					targetname = "ladder_1_model"
					origin = Vector( 32.0001, -54, -2 )
				}
			}
			ladder_1_spawn_trigger = 
			{
				SpawnInfo =
				{
					classname = "script_trigger_multiple"
					allowghost = "0"
					allowincap = "0"
					entireteam = "0"
					filtername = "survivor_filter"
					origin = Vector( 32.5, -77.75, 117.7 )
					parentname = "rescue_chopper_train"
					spawnflags = "1"
					StartDisabled = "0"
					targetname = "ladder_1_spawn_trigger"
					wait = "0"
					extent = Vector( 13.5, 10, 129 )
					connections =
					{
						OnNotTouching =
						{
							cmd1 = "ladder_1_spawn_timerKill01"
							cmd2 = "ladder_1_rungsEnableCollision01"
							cmd3 = "ladder_1_push_triggerKill01"
						}
					}
				}
			}
			ladder_1_spawn_timer = 
			{
				SpawnInfo =
				{
					classname = "logic_timer"
					RefireTime = ".3"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "ladder_1_spawn_timer"
					origin = Vector( 32, -27, 6 )
					connections =
					{
						OnTimer =
						{
							cmd1 = "ladder_1_spawn_triggerTouchTest0-1"
						}
					}
				}
			}
			filter_survivor = 
			{
				SpawnInfo =
				{
					classname = "filter_activator_team"
					filterteam = "2"
					Negated = "Allow entities that match criteria"
					targetname = "filter_survivor"
					origin = Vector( 32, -27, 22 )
				}
			}
			ladder_1_spawn_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "ladder_1_spawn_relay"
					origin = Vector( 32, -27, 57 )
					connections =
					{
						OnSpawn =
						{
							cmd1 = "ladder_1_rungsDisableCollision0-1"
						}
					}
				}
			}
			ladder_1_rungs = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 2 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_buildables/ladder.mdl"
					parentname = "rescue_chopper_train"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "ladder_1_rungs"
					origin = Vector( 32, -52.6406, -3.3203 )
				}
			}
			ladder_1_model1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, -11 )
					disableshadows = "1"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_vehicles/train_ladder.mdl"
					parentname = "rescue_chopper_train"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "0"
					StartDisabled = "1"
					targetname = "ladder_1_model"
					origin = Vector( 32.0001, -54, 126 )
				}
			}
			ladder_1_rungs1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_buildables/ladder.mdl"
					parentname = "rescue_chopper_train"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "ladder_1_rungs"
					origin = Vector( 32, -43.6406, 124.68 )
				}
			}
			ladder_1_rungs2 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/ladder_rung.mdl"
					parentname = "rescue_chopper_train"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "ladder_1_rungs"
					updatechildren = "0"
					origin = Vector( 26.9454, -34, 252 )
				}
			}
			ladder_1_rungs3 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/ladder_rung.mdl"
					parentname = "rescue_chopper_train"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "ladder_1_rungs"
					updatechildren = "0"
					origin = Vector( 26.9454, -26, 259 )
				}
			}
			ladder_1_rungs4 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/ladder_rung.mdl"
					parentname = "rescue_chopper_train"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "ladder_1_rungs"
					updatechildren = "0"
					origin = Vector( 26.9454, -18, 265 )
				}
			}
			ladder_1_rungs5 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/ladder_rung.mdl"
					parentname = "rescue_chopper_train"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "ladder_1_rungs"
					updatechildren = "0"
					origin = Vector( 26.9454, -12, 272 )
				}
			}
			ladder_1_rungs6 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/ladder_rung.mdl"
					parentname = "rescue_chopper_train"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "ladder_1_rungs"
					updatechildren = "0"
					origin = Vector( -13.0546, -34, 252 )
				}
			}
			ladder_1_rungs7 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/ladder_rung.mdl"
					parentname = "rescue_chopper_train"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "ladder_1_rungs"
					updatechildren = "0"
					origin = Vector( -13.0546, -26, 259 )
				}
			}
			ladder_1_rungs8 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/ladder_rung.mdl"
					parentname = "rescue_chopper_train"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "ladder_1_rungs"
					updatechildren = "0"
					origin = Vector( -13.0546, -18, 265 )
				}
			}
			ladder_1_rungs9 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/ladder_rung.mdl"
					parentname = "rescue_chopper_train"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "ladder_1_rungs"
					updatechildren = "0"
					origin = Vector( -13.0546, -12, 272 )
				}
			}
			ladder_1_rungs10 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 2 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_buildables/ladder_rung.mdl"
					parentname = "rescue_chopper_train"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "ladder_1_rungs"
					origin = Vector( 32, -65.6406, -11.3203 )
				}
			}
			ladder_1_push_trigger = 
			{
				SpawnInfo =
				{
					classname = "script_trigger_push"
					alternateticksfix = "0"
					filtername = "survivor_filter"
					origin = Vector( 32.5, -77.75, 119.21 )
					parentname = "rescue_chopper_train"
					pushdir = Vector( 0, 270, 0 )
					spawnflags = "1"
					speed = "100"
					StartDisabled = "1"
					targetname = "ladder_1_push_trigger"
					triggeronstarttouch = "0"
					extent = Vector( 13.5, 10, 130.5 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // RescueHelicopter

RegisterEntityGroup( "RescueHelicopter", RescueHelicopter )
