//-------------------------------------------------------
// Autogenerated from 'resupply_helicopter_button.vmf'
//-------------------------------------------------------
ResupplyHelicopterButton <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.button_resupply_drop,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.chopper_last_pilot_wav,
			EntityGroup.SpawnTables.chopper_supplies_wav,
			EntityGroup.SpawnTables.usetarget_resupply_drop,
			EntityGroup.SpawnTables.chopper_radio_supplydrop_relay,
			EntityGroup.SpawnTables.button_resupply_drop,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			button_resupply_drop = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "1200"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "78 184 41"
					glowrange = "240"
					glowrangemin = "0"
					glowstate = "3"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/buildable_button.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "button_resupply_drop"
					updatechildren = "0"
					origin = Vector( 0, 0, 0 )
				}
			}
			usetarget_resupply_drop = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "button_resupply_drop"
					origin = Vector( 0, 0, 0 )
					targetname = "usetarget_resupply_drop"
					vscripts = "usetargets/resupply_drop_usetarget"
					connections =
					{
						OnUser1 =
						{
							cmd1 = "!selfRunScriptCodeSummonRandomResupplyChopper()0-1"
							cmd2 = "chopper_radio_supplydrop_relayTrigger0-1"
						}
					}
				}
			}
			chopper_radio_supplydrop_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					targetname = "chopper_radio_supplydrop_relay"
					origin = Vector( 0, 0, 0 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "chopper_last_pilot_wavPlaySound0-1"
							cmd2 = "chopper_supplies_wavPlaySound9-1"
						}
					}
				}
			}
			chopper_supplies_wav = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "npc.ChopperPilot_hospital_intro_heli_12"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "chopper_supplies_wav"
					origin = Vector( 0, 0, 0 )
				}
			}
			chopper_last_pilot_wav = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "npc.ChopperPilot_hospital_intro_heli_08"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "chopper_last_pilot_wav"
					origin = Vector( 0, 0, 0 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // ResupplyHelicopterButton

RegisterEntityGroup( "ResupplyHelicopterButton", ResupplyHelicopterButton )
