//-------------------------------------------------------
// Autogenerated from 'resupply_balloon.vmf'
//-------------------------------------------------------
ResupplyBalloon <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.balloon,
			EntityGroup.SpawnTables.chair,
			EntityGroup.SpawnTables.anchor_rope_link,
			EntityGroup.SpawnTables.chair_medkit_proxy,
			EntityGroup.SpawnTables.supply_box,
			EntityGroup.SpawnTables.chair_grenade_launcher_proxy,
			EntityGroup.SpawnTables.explode_1,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.chair_medkit_maker,
			EntityGroup.SpawnTables.chair,
			EntityGroup.SpawnTables.supply_box_spring,
			EntityGroup.SpawnTables.chair_medkit_proxy,
			EntityGroup.SpawnTables.supply_box_rope_bottom,
			EntityGroup.SpawnTables.balloon_1_rope_top_3,
			EntityGroup.SpawnTables.explode_1,
			EntityGroup.SpawnTables.balloon_thrust_rl,
			EntityGroup.SpawnTables.chair_grenade_launcher_maker,
			EntityGroup.SpawnTables.anchor_break_rl,
			EntityGroup.SpawnTables.balloon,
			EntityGroup.SpawnTables.balloon_1_spring_bottom_3,
			EntityGroup.SpawnTables.explode_1_gib_shooter5,
			EntityGroup.SpawnTables.explode_1_gib_shooter4,
			EntityGroup.SpawnTables.explode_1_gib_shooter3,
			EntityGroup.SpawnTables.explode_1_gib_shooter2,
			EntityGroup.SpawnTables.explode_1_gib_shooter1,
			EntityGroup.SpawnTables.explode_1_gib_shooter,
			EntityGroup.SpawnTables.balloon_1_rope_top_1,
			EntityGroup.SpawnTables.balloon_1_rope_bottom_4,
			EntityGroup.SpawnTables.bottom_link_spring,
			EntityGroup.SpawnTables.link_rope_top,
			EntityGroup.SpawnTables.balloon_explode_1_sound,
			EntityGroup.SpawnTables.chair_medkit_template,
			EntityGroup.SpawnTables.balloon_1_rope_top_2,
			EntityGroup.SpawnTables.explode_1_particles,
			EntityGroup.SpawnTables.balloon_1_rope_bottom_3,
			EntityGroup.SpawnTables.supply_box_rope_top,
			EntityGroup.SpawnTables.chair_grenade_launcher_proxy,
			EntityGroup.SpawnTables.balloon_1_spring_bottom_4,
			EntityGroup.SpawnTables.balloon_1_rope_bottom_2,
			EntityGroup.SpawnTables.balloon_thruster_up,
			EntityGroup.SpawnTables.anchor_rope_link,
			EntityGroup.SpawnTables.supply_box_template,
			EntityGroup.SpawnTables.supply_box,
			EntityGroup.SpawnTables.top_link_spring,
			EntityGroup.SpawnTables.chair_rope,
			EntityGroup.SpawnTables.anchor_rope_top,
			EntityGroup.SpawnTables.anchor_rope_bottom,
			EntityGroup.SpawnTables.balloon_1_spring_bottom_1,
			EntityGroup.SpawnTables.balloon_1_rope_top_4,
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.balloon_thruster_side,
			EntityGroup.SpawnTables.chair_grenade_launcher_template,
			EntityGroup.SpawnTables.balloon_1_rope_bottom_1,
			EntityGroup.SpawnTables.supply_box_template_maker,
			EntityGroup.SpawnTables.balloon_1_spring_bottom_2,
			EntityGroup.SpawnTables.balloon_1_dynamic_light,
			EntityGroup.SpawnTables.balloon_1_explode_rl,
			EntityGroup.SpawnTables.balloon_thrust_timer,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			balloon_1_rope_top_1 = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 0, 0 )
					MoveSpeed = "64"
					NextKey = "balloon_1_rope_bottom_1"
					parentname = "balloon"
					PositionInterpolator = "2"
					RopeMaterial = "cable/cable.vmt"
					Slack = "25"
					Subdiv = "2"
					targetname = "balloon_1_rope_top_1"
					TextureScale = "1"
					Width = "2"
					origin = Vector( -26, -27, 236 )
				}
			}
			balloon_1_rope_bottom_1 = 
			{
				SpawnInfo =
				{
					classname = "keyframe_rope"
					angles = Vector( 0, 0, 0 )
					MoveSpeed = "64"
					parentname = "chair"
					RopeMaterial = "cable/cable.vmt"
					Slack = "25"
					Subdiv = "2"
					targetname = "balloon_1_rope_bottom_1"
					TextureScale = "1"
					Width = "2"
					origin = Vector( -29, -9, 177 )
				}
			}
			balloon_1_rope_top_4 = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 90, 0 )
					MoveSpeed = "64"
					NextKey = "balloon_1_rope_bottom_4"
					parentname = "balloon"
					PositionInterpolator = "2"
					RopeMaterial = "cable/cable.vmt"
					Slack = "25"
					Subdiv = "2"
					targetname = "balloon_1_rope_top_4"
					TextureScale = "1"
					Width = "2"
					origin = Vector( 21, -37, 236 )
				}
			}
			balloon_1_rope_bottom_4 = 
			{
				SpawnInfo =
				{
					classname = "keyframe_rope"
					angles = Vector( 0, 90, 0 )
					MoveSpeed = "64"
					parentname = "chair"
					RopeMaterial = "cable/cable.vmt"
					Slack = "25"
					Subdiv = "2"
					targetname = "balloon_1_rope_bottom_4"
					TextureScale = "1"
					Width = "2"
					origin = Vector( 4, -13, 175 )
				}
			}
			balloon_1_rope_top_3 = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 180, 0 )
					MoveSpeed = "64"
					NextKey = "balloon_1_rope_bottom_3"
					parentname = "balloon"
					PositionInterpolator = "2"
					RopeMaterial = "cable/cable.vmt"
					Slack = "25"
					Subdiv = "2"
					targetname = "balloon_1_rope_top_3"
					TextureScale = "1"
					Width = "2"
					origin = Vector( 21, 36, 236 )
				}
			}
			balloon_1_rope_bottom_3 = 
			{
				SpawnInfo =
				{
					classname = "keyframe_rope"
					angles = Vector( 0, 180, 0 )
					MoveSpeed = "64"
					NextKey = "balloon_1_rope_bottom_5"
					parentname = "chair"
					RopeMaterial = "cable/cable.vmt"
					Slack = "25"
					Subdiv = "2"
					targetname = "balloon_1_rope_bottom_3"
					TextureScale = "1"
					Width = "2"
					origin = Vector( 1, 12, 179 )
				}
			}
			balloon_1_rope_top_2 = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 270, 0 )
					MoveSpeed = "64"
					NextKey = "balloon_1_rope_bottom_2"
					parentname = "balloon"
					PositionInterpolator = "2"
					RopeMaterial = "cable/cable.vmt"
					Slack = "25"
					Subdiv = "2"
					targetname = "balloon_1_rope_top_2"
					TextureScale = "1"
					Width = "2"
					origin = Vector( -26, 28, 236 )
				}
			}
			balloon_1_rope_bottom_2 = 
			{
				SpawnInfo =
				{
					classname = "keyframe_rope"
					angles = Vector( 0, 270, 0 )
					MoveSpeed = "64"
					parentname = "chair"
					RopeMaterial = "cable/cable.vmt"
					Slack = "25"
					Subdiv = "2"
					targetname = "balloon_1_rope_bottom_2"
					TextureScale = "1"
					Width = "2"
					origin = Vector( -29, 9, 179 )
				}
			}
			explode_1_gib_shooter = 
			{
				SpawnInfo =
				{
					classname = "env_shooter"
					angles = Vector( 0, 180, 0 )
					fademindist = "-1"
					fadescale = "1"
					gibangles = "0 0 0"
					gibanglevelocity = "25"
					gibgravityscale = "1"
					m_flGibLife = "6"
					m_flVariance = "0.15"
					m_flVelocity = "300"
					m_iGibs = "1"
					parentname = "chair"
					renderamt = "255"
					rendercolor = "255 255 255"
					shootmodel = "models/infected/limbs/common_infected_w_torso_gib1.mdl"
					shootsounds = "-1"
					simulation = "2"
					spawnflags = "4"
					targetname = "explode_1_gib_shooter"
					origin = Vector( -30, 0, 200 )
				}
			}
			explode_1_gib_shooter1 = 
			{
				SpawnInfo =
				{
					classname = "env_shooter"
					angles = Vector( 0, 270, 0 )
					fademindist = "-1"
					fadescale = "1"
					gibangles = "0 0 0"
					gibanglevelocity = "25"
					gibgravityscale = "1"
					m_flGibLife = "6"
					m_flVariance = "0.15"
					m_flVelocity = "300"
					m_iGibs = "1"
					parentname = "chair"
					renderamt = "255"
					rendercolor = "255 255 255"
					shootmodel = "models/infected/limbs/common_infected_w_l_arm_upper_gib.mdl"
					shootsounds = "-1"
					simulation = "2"
					spawnflags = "4"
					targetname = "explode_1_gib_shooter"
					origin = Vector( -11, -21, 174 )
				}
			}
			explode_1_gib_shooter2 = 
			{
				SpawnInfo =
				{
					classname = "env_shooter"
					angles = Vector( 0, 90, 0 )
					fademindist = "-1"
					fadescale = "1"
					gibangles = "0 0 0"
					gibanglevelocity = "25"
					gibgravityscale = "1"
					m_flGibLife = "6"
					m_flVariance = "0.15"
					m_flVelocity = "300"
					m_iGibs = "1"
					parentname = "chair"
					renderamt = "255"
					rendercolor = "255 255 255"
					shootmodel = "models/infected/limbs/common_infected_w_l_arm_upper_gib.mdl"
					shootsounds = "-1"
					simulation = "2"
					spawnflags = "4"
					targetname = "explode_1_gib_shooter"
					origin = Vector( -5, 27, 174 )
				}
			}
			explode_1_gib_shooter3 = 
			{
				SpawnInfo =
				{
					classname = "env_shooter"
					angles = Vector( 90, 0, 0 )
					delay = "0"
					disablereceiveshadows = "0"
					disableX360 = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					gibangles = "0 0 0"
					gibanglevelocity = "0"
					gibgravityscale = "1"
					m_flGibLife = "6"
					m_flVariance = "0"
					m_flVelocity = "0"
					m_iGibs = "1"
					massoverride = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					nogibshadows = "0"
					parentname = "chair"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shootmodel = "models/props/cs_office/chair_office.mdl"
					shootsounds = "-1"
					simulation = "1"
					skin = "0"
					spawnflags = "6"
					targetname = "explode_1_gib_shooter"
					origin = Vector( 15, 3, 153 )
				}
			}
			explode_1_gib_shooter4 = 
			{
				SpawnInfo =
				{
					classname = "env_shooter"
					angles = Vector( 0, 90, 0 )
					fademindist = "-1"
					fadescale = "1"
					gibangles = "0 0 0"
					gibanglevelocity = "25"
					gibgravityscale = "1"
					m_flGibLife = "6"
					m_flVariance = "0.15"
					m_flVelocity = "300"
					m_iGibs = "1"
					parentname = "chair"
					renderamt = "255"
					rendercolor = "255 255 255"
					shootmodel = "models/infected/limbs/common_infected_w_l_leg_upper_gib.mdl"
					shootsounds = "-1"
					simulation = "2"
					spawnflags = "4"
					targetname = "explode_1_gib_shooter"
					origin = Vector( 47, 25, 158 )
				}
			}
			explode_1_gib_shooter5 = 
			{
				SpawnInfo =
				{
					classname = "env_shooter"
					angles = Vector( 0, 270, 0 )
					fademindist = "-1"
					fadescale = "1"
					gibangles = "0 0 0"
					gibanglevelocity = "25"
					gibgravityscale = "1"
					m_flGibLife = "6"
					m_flVariance = "0.15"
					m_flVelocity = "300"
					m_iGibs = "1"
					parentname = "chair"
					renderamt = "255"
					rendercolor = "255 255 255"
					shootmodel = "models/infected/limbs/common_infected_w_l_leg_upper_gib.mdl"
					shootsounds = "-1"
					simulation = "2"
					spawnflags = "4"
					targetname = "explode_1_gib_shooter"
					origin = Vector( 41, -23, 158 )
				}
			}
			balloon = 
			{
				SpawnInfo =
				{
					classname = "prop_physics_multiplayer"
					angles = Vector( 0, 0, 0 )
					BreakableType = "0"
					damagetoenablemotion = "0"
					Damagetype = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					massScale = "0"
					minhealthdmg = "0"
					model = "models/props_unique/airport/atlas_break_ball.mdl"
					nodamageforces = "0"
					overridescript = "mass,10"
					physdamagescale = "0.1"
					physicsmode = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "258"
					targetname = "balloon"
					origin = Vector( 1, 0, 106 )
					connections =
					{
						OnTakeDamage =
						{
							cmd1 = "balloon_1_explode_rlTrigger01"
							cmd2 = "chair_medkit_makerForceSpawn01"
							cmd3 = "supply_box_template_makerForceSpawn01"
							cmd4 = "chair_grenade_launcher_makerForceSpawn01"
						}
					}
				}
			}
			balloon_thruster_up = 
			{
				SpawnInfo =
				{
					classname = "phys_thruster"
					angles = Vector( -90, 0, 0 )
					attach1 = "balloon"
					force = "2250"
					spawnflags = "51"
					targetname = "balloon_thruster_up"
					origin = Vector( 0, 0, 351 )
				}
			}
			balloon_thruster_side = 
			{
				SpawnInfo =
				{
					classname = "phys_thruster"
					angles = Vector( 0, 0, 0 )
					attach1 = "balloon"
					force = "600"
					spawnflags = "50"
					targetname = "balloon_thruster_side"
					origin = Vector( 0, 0, 332 )
				}
			}
			chair = 
			{
				SpawnInfo =
				{
					classname = "prop_physics_multiplayer"
					angles = Vector( -44.5744, 353.052, 9.85082 )
					BreakableType = "0"
					damagetoenablemotion = "0"
					Damagetype = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					minhealthdmg = "0"
					model = "models/deadbodies/dead_male_sittingchair.mdl"
					nodamageforces = "0"
					overridescript = "mass,10"
					physdamagescale = "0.1"
					physicsmode = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "256"
					targetname = "chair"
					origin = Vector( 17, 3, 151 )
				}
			}
			balloon_1_spring_bottom_1 = 
			{
				SpawnInfo =
				{
					classname = "phys_spring"
					attach1 = "balloon"
					attach2 = "chair"
					breaklength = "0"
					constant = "50"
					damping = "6"
					length = "0"
					relativedamping = "0.1"
					spawnflags = "0"
					springaxis = Vector( -26, -27, 236 )
					targetname = "balloon_1_spring_bottom_1"
					origin = Vector( -29, -9, 177 )
				}
			}
			balloon_1_spring_bottom_4 = 
			{
				SpawnInfo =
				{
					classname = "phys_spring"
					attach1 = "balloon"
					attach2 = "chair"
					breaklength = "0"
					constant = "50"
					damping = "6"
					length = "0"
					relativedamping = "0.1"
					springaxis = Vector( 21, -37, 236 )
					targetname = "balloon_1_spring_bottom_4"
					origin = Vector( 4, -13, 175 )
				}
			}
			balloon_1_spring_bottom_3 = 
			{
				SpawnInfo =
				{
					classname = "phys_spring"
					attach1 = "balloon"
					attach2 = "chair"
					breaklength = "0"
					constant = "50"
					damping = "6"
					length = "0"
					relativedamping = "0.1"
					spawnflags = "0"
					springaxis = Vector( 21, 36, 236 )
					targetname = "balloon_1_spring_bottom_3"
					origin = Vector( 1, 12, 179 )
				}
			}
			balloon_1_spring_bottom_2 = 
			{
				SpawnInfo =
				{
					classname = "phys_spring"
					attach1 = "balloon"
					attach2 = "chair"
					breaklength = "0"
					constant = "50"
					damping = "6"
					length = "0"
					relativedamping = "0.1"
					springaxis = Vector( -26, 28, 236 )
					targetname = "balloon_1_spring_bottom_2"
					origin = Vector( -29, 9, 179 )
				}
			}
			bottom_link_spring = 
			{
				SpawnInfo =
				{
					classname = "phys_spring"
					attach1 = "anchor_rope_link"
					constant = "50"
					damping = "2.0"
					relativedamping = "0.1"
					spawnflags = "0"
					springaxis = Vector( -2, 2, 59 )
					targetname = "bottom_link_spring"
					origin = Vector( 0, 0, 1 )
				}
			}
			anchor_rope_link = 
			{
				SpawnInfo =
				{
					classname = "prop_physics_multiplayer"
					angles = Vector( 0, 0, 0 )
					BreakableType = "0"
					damagetoenablemotion = "0"
					Damagetype = "0"
					disablereceiveshadows = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					massScale = "0"
					minhealthdmg = "0"
					model = "models/props_debris/wood_board04a.mdl"
					nodamageforces = "0"
					overridescript = "mass,3"
					physdamagescale = "0.1"
					physicsmode = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "8450"
					targetname = "anchor_rope_link"
					origin = Vector( 16, 2, 91 )
					connections =
					{
						OnTakeDamage =
						{
							cmd1 = "anchor_break_rlTrigger01"
						}
						OnBreak =
						{
							cmd1 = "anchor_break_rlTrigger01"
						}
					}
				}
			}
			top_link_spring = 
			{
				SpawnInfo =
				{
					classname = "phys_spring"
					attach1 = "chair"
					attach2 = "anchor_rope_link"
					constant = "5000"
					damping = "2.0"
					relativedamping = "0.1"
					spawnflags = "0"
					springaxis = Vector( 16, 2, 154 )
					targetname = "top_link_spring"
					origin = Vector( 16, 2, 123 )
				}
			}
			anchor_rope_top = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 180, 0 )
					Breakable = "1"
					MoveSpeed = "64"
					NextKey = "anchor_rope_bottom"
					parentname = "anchor_rope_link"
					PositionInterpolator = "2"
					RopeMaterial = "cable/rope"
					Slack = "100"
					spawnflags = "0"
					Subdiv = "2"
					targetname = "anchor_rope_top"
					TextureScale = "1"
					Width = "2"
					origin = Vector( 16, 2, 59 )
				}
			}
			anchor_rope_bottom = 
			{
				SpawnInfo =
				{
					classname = "keyframe_rope"
					angles = Vector( 0, 180, 0 )
					MoveSpeed = "64"
					RopeMaterial = "cable/rope"
					Slack = "25"
					spawnflags = "0"
					Subdiv = "2"
					targetname = "anchor_rope_bottom"
					TextureScale = "1"
					Width = "2"
					origin = Vector( 0, 0, 1 )
				}
			}
			chair_rope = 
			{
				SpawnInfo =
				{
					classname = "keyframe_rope"
					angles = Vector( 0, 0, -180 )
					Breakable = "1"
					MoveSpeed = "64"
					parentname = "chair"
					RopeMaterial = "cable/rope"
					Slack = "25"
					spawnflags = "0"
					Subdiv = "2"
					targetname = "chair_rope"
					TextureScale = "1"
					Width = "2"
					origin = Vector( 16, 2, 154 )
				}
			}
			link_rope_top = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 0, -180 )
					Breakable = "1"
					MoveSpeed = "64"
					NextKey = "chair_rope"
					parentname = "anchor_rope_link"
					PositionInterpolator = "2"
					RopeMaterial = "cable/rope"
					Slack = "100"
					spawnflags = "0"
					Subdiv = "2"
					targetname = "link_rope_top"
					TextureScale = "1"
					Width = "2"
					origin = Vector( 16, 2, 123 )
				}
			}
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "1"
					origin = Vector( 5, 2, 91 )
					connections =
					{
						OnSpawn =
						{
							cmd1 = "anchor_rope_linkSetHealth99990-1"
							cmd2 = "supply_boxSetHealth99990-1"
							cmd3 = "balloonSetHealth99990-1"
							cmd4 = "anchor_rope_linkBreak5-1"
						}
					}
				}
			}
			chair_medkit = 
			{
				SpawnInfo =
				{
					classname = "weapon_first_aid_kit_spawn"
					angles = Vector( 0, 270, 0 )
					solid = "6"
					spawnflags = "1"
					targetname = "chair_medkit"
					origin = Vector( -3, -13, 157 )
				}
			}
			chair_medkit_proxy = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( -7.43547, 256.936, -29.1474 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/w_models/weapons/w_eq_medkit.mdl"
					parentname = "chair"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "chair_medkit_proxy"
					updatechildren = "0"
					origin = Vector( -3, -13, 156 )
					connections =
					{
						OnTakeDamage =
						{
							cmd1 = "chair_medkit_makerForceSpawn01"
							cmd2 = "!selfKill01"
						}
					}
				}
			}
			chair_medkit_template = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "2"
					targetname = "chair_medkit_template"
					Template01 = "chair_medkit"
					origin = Vector( -1, -27, 159 )
				}
			}
			chair_medkit_maker = 
			{
				SpawnInfo =
				{
					classname = "env_entity_maker"
					angles = Vector( -7.43547, 256.936, -29.1474 )
					EntityTemplate = "chair_medkit_template"
					parentname = "chair"
					PostSpawnDirection = "0 0 0"
					PostSpawnDirectionVariance = "0"
					PostSpawnInheritAngles = "0"
					PostSpawnSpeed = "0"
					spawnflags = "0"
					targetname = "chair_medkit_maker"
					origin = Vector( -3, -13, 156 )
					connections =
					{
						OnEntitySpawned =
						{
							cmd1 = "!selfKill01"
							cmd2 = "chair_medkit_templateKill01"
						}
					}
				}
			}
			balloon_thrust_rl = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "balloon_thrust_rl"
					origin = Vector( 0.394012, 16, 351.027 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "balloon_thruster_sideActivate0-1"
							cmd2 = "balloon_thrust_timerEnable1-1"
							cmd3 = "!selfKill0-1"
						}
					}
				}
			}
			balloon_thrust_timer = 
			{
				SpawnInfo =
				{
					classname = "logic_timer"
					LowerRandomBound = "3"
					spawnflags = "1"
					StartDisabled = "1"
					targetname = "balloon_thrust_timer"
					UpperRandomBound = "4"
					UseRandomTime = "1"
					origin = Vector( 5, -19, 343 )
					connections =
					{
						OnTimerLow =
						{
							cmd1 = "balloon_thruster_upScale.900-1"
						}
						OnTimerHigh =
						{
							cmd1 = "balloon_thruster_upScale.70-1"
						}
					}
				}
			}
			supply_box_rope_top = 
			{
				SpawnInfo =
				{
					classname = "keyframe_rope"
					angles = Vector( 0, 0, 0 )
					Breakable = "1"
					MoveSpeed = "64"
					parentname = "supply_box"
					RopeMaterial = "cable/rope"
					Slack = "25"
					spawnflags = "0"
					Subdiv = "2"
					targetname = "supply_box_rope_top"
					TextureScale = "1"
					Width = "2"
					origin = Vector( 14, 17, 145 )
				}
			}
			supply_box_rope_bottom = 
			{
				SpawnInfo =
				{
					classname = "move_rope"
					angles = Vector( 0, 0, 0 )
					Breakable = "0"
					MoveSpeed = "64"
					NextKey = "supply_box_rope_top"
					parentname = "chair"
					PositionInterpolator = "2"
					RopeMaterial = "cable/rope"
					Slack = "100"
					spawnflags = "0"
					Subdiv = "2"
					targetname = "supply_box_rope_bottom"
					TextureScale = "1"
					Width = "2"
					origin = Vector( 14, 17, 152 )
				}
			}
			supply_box_spring = 
			{
				SpawnInfo =
				{
					classname = "phys_spring"
					attach1 = "supply_box"
					attach2 = "chair"
					constant = "100"
					damping = "10"
					relativedamping = "0.1"
					spawnflags = "0"
					springaxis = Vector( 14, 17, 152 )
					targetname = "supply_box_spring"
					origin = Vector( 14, 17, 143.441 )
				}
			}
			supply_box = 
			{
				SpawnInfo =
				{
					classname = "prop_physics_multiplayer"
					angles = Vector( 30, 0, 75 )
					BreakableType = "0"
					disablereceiveshadows = "0"
					fademindist = "-1"
					fadescale = "1"
					glowcolor = "0 0 0"
					inertiaScale = "1.0"
					model = "models/props_crates/supply_crate01.mdl"
					overridescript = "mass,1"
					physdamagescale = "0.1"
					physicsmode = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					skin = "0"
					spawnflags = "8194"
					targetname = "supply_box"
					origin = Vector( 16, 19, 127.441 )
					connections =
					{
						OnTakeDamage =
						{
							cmd1 = "supply_box_rope_topClearParent01"
							cmd2 = "supply_box_rope_topBreak01"
							cmd3 = "supply_box_springKill01"
							cmd4 = "!selfBreak0.11"
							cmd5 = "supply_box_template_makerForceSpawn01"
						}
					}
				}
			}
			supply_box_template = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "2"
					targetname = "supply_box_template"
					Template01 = "supply_box_item"
					origin = Vector( 18, 32, 120 )
				}
			}
			supply_box_template_maker = 
			{
				SpawnInfo =
				{
					classname = "env_entity_maker"
					angles = Vector( -7.43547, 256.936, -29.1474 )
					EntityTemplate = "supply_box_template"
					parentname = "supply_box"
					PostSpawnDirection = "0 0 0"
					PostSpawnDirectionVariance = "0"
					PostSpawnInheritAngles = "0"
					PostSpawnSpeed = "0"
					spawnflags = "0"
					targetname = "supply_box_template_maker"
					origin = Vector( 18, 21, 127.307 )
					connections =
					{
						OnEntitySpawned =
						{
							cmd1 = "!selfKill01"
							cmd2 = "supply_box_templateKill01"
						}
					}
				}
			}
			supply_box_item = 
			{
				SpawnInfo =
				{
					classname = "weapon_pipe_bomb_spawn"
					angles = Vector( 0, 0, 0 )
					count = "1"
					solid = "6"
					spawnflags = "1"
					targetname = "supply_box_item"
					origin = Vector( 11, 19, 129 )
				}
			}
			supply_box_item1 = 
			{
				SpawnInfo =
				{
					classname = "weapon_adrenaline_spawn"
					angles = Vector( 0, 0, 90 )
					solid = "6"
					spawnflags = "1"
					targetname = "supply_box_item"
					origin = Vector( 23, 16, 128 )
				}
			}
			chair_grenade_launcher = 
			{
				SpawnInfo =
				{
					classname = "weapon_grenade_launcher_spawn"
					angles = Vector( 10.7299, 280.544, -135.007 )
					count = "1"
					solid = "6"
					spawnflags = "1"
					targetname = "chair_grenade_launcher"
					origin = Vector( 0.309998, -2.646, 194.09 )
				}
			}
			chair_grenade_launcher_proxy = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 10.7299, 280.544, -135.007 )
					disablereceiveshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/w_models/weapons/w_grenade_launcher.mdl"
					parentname = "chair"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "chair_grenade_launcher_proxy"
					updatechildren = "0"
					origin = Vector( 0.309998, -2.646, 186.09 )
					connections =
					{
						OnTakeDamage =
						{
							cmd1 = "!selfKill01"
							cmd2 = "chair_grenade_launcher_makerForceSpawn01"
						}
					}
				}
			}
			chair_grenade_launcher_maker = 
			{
				SpawnInfo =
				{
					classname = "env_entity_maker"
					angles = Vector( 0, 0, 0 )
					EntityTemplate = "chair_grenade_launcher_template"
					parentname = "chair"
					PostSpawnDirection = "0 0 0"
					PostSpawnDirectionVariance = "0"
					spawnflags = "0"
					targetname = "chair_grenade_launcher_maker"
					origin = Vector( 6, -4, 184 )
					connections =
					{
						OnEntitySpawned =
						{
							cmd1 = "!selfKill0-1"
						}
					}
				}
			}
			chair_grenade_launcher_template = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "2"
					targetname = "chair_grenade_launcher_template"
					Template01 = "chair_grenade_launcher"
					origin = Vector( -6, -4, 188 )
				}
			}
			explode_1 = 
			{
				SpawnInfo =
				{
					classname = "env_explosion"
					fireballsprite = "sprites/zerogxplode.spr"
					iMagnitude = "100"
					parentname = "balloon"
					rendermode = "5"
					spawnflags = "1"
					targetname = "explode_1"
					origin = Vector( 2, 0, 211 )
				}
			}
			balloon_1_explode_rl = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "1"
					targetname = "balloon_1_explode_rl"
					origin = Vector( -22, 0, 208 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "balloonKill0.1-1"
							cmd2 = "explode_1Explode0-1"
							cmd3 = "chair_grenade_launcher_proxyKill0-1"
							cmd4 = "supply_box_rope_topBreak0-1"
							cmd5 = "supply_boxBreak0.1-1"
							cmd6 = "explode_1_gib_shooterShoot0.1-1"
							cmd7 = "chairKill0.1-1"
							cmd8 = "chair_ropeBreak0-1"
							cmd9 = "explode_1ClearParent0-1"
							cmd10 = "explode_1_particlesClearParent0-1"
							cmd11 = "explode_1_particlesStart0-1"
							cmd12 = "explode_1_gib_shooterClearParent0-1"
							cmd13 = "balloon_1_spring_bottom_1Kill0.1-1"
							cmd14 = "balloon_1_spring_bottom_2Kill0.1-1"
							cmd15 = "balloon_1_spring_bottom_4Kill0.1-1"
							cmd16 = "balloon_1_spring_bottom_3Kill0.1-1"
							cmd17 = "supply_box_springKill0.1-1"
							cmd18 = "bottom_link_springKill0.1-1"
							cmd19 = "top_link_springKill0.1-1"
							cmd20 = "balloon_thruster_sideKill0.1-1"
							cmd21 = "balloon_thruster_upKill0.1-1"
							cmd22 = "balloon_thrust_timerKill0.1-1"
							cmd23 = "balloon_thrust_rlKill0.1-1"
							cmd24 = "anchor_rope_linkBreak0.1-1"
							cmd25 = "balloon_explode_1_soundPlaySound0-1"
							cmd26 = "balloon_explode_1_soundKill5-1"
							cmd27 = "anchor_rope_bottomKill3-1"
							cmd28 = "chair_medkit_templateKill0.11"
							cmd29 = "supply_box_templateKill0.11"
							cmd30 = "chair_grenade_launcher_templateKill0.11"
							cmd31 = "explode_1_particlesKill5-1"
						}
					}
				}
			}
			explode_1_particles = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "weapon_grenadelauncher_dirt"
					parentname = "balloon"
					render_in_front = "0"
					start_active = "0"
					targetname = "explode_1_particles"
					origin = Vector( 2.14899, -1.01001, 202.934 )
				}
			}
			balloon_explode_1_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "GrenadeLauncher.Explode"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					SourceEntityName = "balloon"
					spawnflags = "48"
					targetname = "balloon_explode_1_sound"
					origin = Vector( 2.14899, -1.01001, 213.934 )
				}
			}
			balloon_1_dynamic_light = 
			{
				SpawnInfo =
				{
					classname = "light_dynamic"
					_cone = "45"
					_inner_cone = "30"
					_light = "255 255 255 1500"
					angles = Vector( -353, 31, 0 )
					brightness = "5"
					distance = "105"
					parentname = "chair"
					pitch = "-353"
					spawnflags = "1"
					spotlight_radius = "80"
					targetname = "balloon_1_dynamic_light"
					origin = Vector( -38, -34, 151 )
				}
			}
			anchor_break_rl = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "1"
					targetname = "anchor_break_rl"
					origin = Vector( 20, -1, 89 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "link_rope_topKill3-1"
							cmd2 = "anchor_rope_topKill3-1"
							cmd3 = "anchor_rope_bottomKill3-1"
							cmd4 = "anchor_rope_linkBreak0.1-1"
							cmd5 = "balloon_thrust_rlTrigger0-1"
							cmd6 = "bottom_link_springKill0-1"
							cmd7 = "link_rope_topClearParent0-1"
							cmd8 = "link_rope_topBreak0-1"
							cmd9 = "anchor_rope_topClearParent0-1"
							cmd10 = "anchor_rope_topBreak0-1"
							cmd11 = "top_link_springKill0-1"
						}
					}
				}
			}
		} // SpawnTables
	} // EntityGroup
} // ResupplyBalloon

RegisterEntityGroup( "ResupplyBalloon", ResupplyBalloon )
