//-------------------------------------------------------
// Autogenerated from 'shootzone_trigger.vmf'
//-------------------------------------------------------
ShootzoneTrigger <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.shootzone_model,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.shootzone_center,
			EntityGroup.SpawnTables.shootzone_trigger,
			EntityGroup.SpawnTables.shootzone_script,
			EntityGroup.SpawnTables.shootzone_model,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			shootzone_model = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "128 255 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_cemetery/grave_07.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "shootzone_model"
					updatechildren = "0"
					origin = Vector( 0, 0, 0 )
				}
			}
			shootzone_trigger = 
			{
				SpawnInfo =
				{
					classname = "script_trigger_multiple"
					allowghost = "0"
					allowincap = "0"
					entireteam = "2"
					origin = Vector( 0, 0, 0 )
					spawnflags = "1"
					StartDisabled = "1"
					targetname = "shootzone_trigger"
					wait = "1"
					extent = Vector( 96, 96, 64 )
					connections =
					{
						OnStartTouch =
						{
							cmd1 = "shootzone_scriptRunScriptCodeOnEnterShootzone()0-1"
						}
						OnEndTouch =
						{
							cmd1 = "shootzone_scriptRunScriptCodeOnExitShootzone()0-1"
						}
					}
				}
			}
			shootzone_script = 
			{
				SpawnInfo =
				{
					classname = "logic_script"
					Group00 = "shootzone_trigger"
					Group01 = "shootzone_model"
					Group02 = "shootzone_center"
					targetname = "shootzone_script"
					thinkfunction = "Think"
					vscripts = "shootzone_logic_script"
					origin = Vector( 0, -36.684, 64 )
				}
			}
			shootzone_center = 
			{
				SpawnInfo =
				{
					classname = "info_item_position"
					angles = Vector( 0, 0, 0 )
					targetname = "shootzone_center"
					origin = Vector( 0, 0, 0 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // ShootzoneTrigger

RegisterEntityGroup( "ShootzoneTrigger", ShootzoneTrigger )
