//-------------------------------------------------------
// Autogenerated from 'shootzone_sound.vmf'
//-------------------------------------------------------
ShootzoneSound <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.shootzone_sound,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			shootzone_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "c2m4.BadMan1"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "16"
					targetname = "shootzone_sound"
					origin = Vector( 0, 0, 0 )
				}
			}
		} // SpawnTables
	} // EntityGroup
} // ShootzoneSound

RegisterEntityGroup( "ShootzoneSound", ShootzoneSound )
