//-------------------------------------------------------
// Autogenerated from 'tank_manhole.vmf'
//-------------------------------------------------------
TankManhole <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.manhole_model,
			EntityGroup.SpawnTables.manhole_cover_model,
			EntityGroup.SpawnTables.manhole_boards,
			EntityGroup.SpawnTables.manhole_boards1,
			EntityGroup.SpawnTables.manhole_boards2,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.hint_tank_barricaded,
			EntityGroup.SpawnTables.manhole_tank_sound2,
			EntityGroup.SpawnTables.manhole_tank_start_rattle_rl,
			EntityGroup.SpawnTables.manhole_tank_sound5,
			EntityGroup.SpawnTables.manhole_boards_filter,
			EntityGroup.SpawnTables.hint_branch,
			EntityGroup.SpawnTables.manhole_cover_shooter,
			EntityGroup.SpawnTables.hint_tank_spawn,
			EntityGroup.SpawnTables.manhole_cover_rattle_timer,
			EntityGroup.SpawnTables.manhole_cover_rattle_case,
			EntityGroup.SpawnTables.manhole_cover_door_2,
			EntityGroup.SpawnTables.manhole_tank_stop_rattle_rl,
			EntityGroup.SpawnTables.manhole_tank_shake,
			EntityGroup.SpawnTables.manhole_cover_dust,
			EntityGroup.SpawnTables.manhole_tank_sound_timer,
			EntityGroup.SpawnTables.manhole_tank_spawn_particles,
			EntityGroup.SpawnTables.manhole_boards_template,
			EntityGroup.SpawnTables.manhole_tank,
			EntityGroup.SpawnTables.hint,
			EntityGroup.SpawnTables.manhole_model,
			EntityGroup.SpawnTables.manhole_cover_shake,
			EntityGroup.SpawnTables.manhole_cover_door_1_open_sound,
			EntityGroup.SpawnTables.manhole_tank_release_rl,
			EntityGroup.SpawnTables.manhole_tank_sound6,
			EntityGroup.SpawnTables.manhole_cover_door_3,
			EntityGroup.SpawnTables.manhole_cover_door_1_break_sound,
			EntityGroup.SpawnTables.manhole_tank_sound4,
			EntityGroup.SpawnTables.manhole_tank_board_break_rl,
			EntityGroup.SpawnTables.manhole_tank_cleanup_relay,
			EntityGroup.SpawnTables.manhole_tank_sound_picker,
			EntityGroup.SpawnTables.manhole_tank_script,
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.manhole_cover_door_flush,
			EntityGroup.SpawnTables.manhole_tank_sound3,
			EntityGroup.SpawnTables.manhole_cover_door_1,
			EntityGroup.SpawnTables.manhole_tank_sound7,
			EntityGroup.SpawnTables.usetarget_tank_manhole,
			EntityGroup.SpawnTables.manhole_tank_sound9,
			EntityGroup.SpawnTables.manhole_cover_model,
			EntityGroup.SpawnTables.manhole_tank_sound1,
			EntityGroup.SpawnTables.manhole_tank_sound8,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			manhole_tank_sound1 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "HulkZombie.Breathe"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "0"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "manhole_tank_sound1"
					volstart = "0"
					origin = Vector( -8, 16, 32 )
				}
			}
			manhole_tank_sound2 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "HulkZombie.Growl"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "0"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "manhole_tank_sound2"
					volstart = "0"
					origin = Vector( 8, 16, 32 )
				}
			}
			manhole_tank_sound3 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "HulkZombie.StartLedgeClimb"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "0"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "manhole_tank_sound3"
					volstart = "0"
					origin = Vector( 24, 16, 32 )
				}
			}
			manhole_tank_sound4 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "HulkZombie.Alert"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "0"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "manhole_tank_sound4"
					volstart = "0"
					origin = Vector( -8, 0, 32 )
				}
			}
			manhole_tank_sound5 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "HulkZombie.Thud"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "0"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "manhole_tank_sound5"
					volstart = "0"
					origin = Vector( 8, 0, 32 )
				}
			}
			manhole_tank_sound6 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "HulkZombie.Voice"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "0"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "manhole_tank_sound6"
					volstart = "0"
					origin = Vector( 24, 0, 32 )
				}
			}
			manhole_tank_sound7 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "HulkZombie.Yell"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "0"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "manhole_tank_sound7"
					volstart = "0"
					origin = Vector( -8, -16, 32 )
				}
			}
			manhole_tank_sound8 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "HulkZombie.Attack"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "0"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "manhole_tank_sound8"
					volstart = "0"
					origin = Vector( 8, -16, 32 )
				}
			}
			manhole_tank_sound9 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "HulkZombie.Thud"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "0"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "manhole_tank_sound9"
					volstart = "0"
					origin = Vector( 24, -16, 32 )
				}
			}
			manhole_tank_sound_picker = 
			{
				SpawnInfo =
				{
					classname = "logic_case"
					targetname = "manhole_tank_sound_picker"
					origin = Vector( -24, 0, 32 )
					connections =
					{
						OnCase09 =
						{
							cmd1 = "manhole_tank_sound9PlaySound0-1"
						}
						OnCase06 =
						{
							cmd1 = "manhole_tank_sound6PlaySound0-1"
						}
						OnCase02 =
						{
							cmd1 = "manhole_tank_sound2PlaySound0-1"
						}
						OnCase08 =
						{
							cmd1 = "manhole_tank_sound8PlaySound0-1"
						}
						OnCase01 =
						{
							cmd1 = "manhole_tank_sound1PlaySound0-1"
						}
						OnCase03 =
						{
							cmd1 = "manhole_tank_sound3PlaySound0-1"
						}
						OnCase07 =
						{
							cmd1 = "manhole_tank_sound7PlaySound0-1"
						}
						OnCase04 =
						{
							cmd1 = "manhole_tank_sound4PlaySound0-1"
						}
						OnCase05 =
						{
							cmd1 = "manhole_tank_sound5PlaySound0-1"
						}
					}
				}
			}
			manhole_tank_sound_timer = 
			{
				SpawnInfo =
				{
					classname = "logic_timer"
					LowerRandomBound = "1"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "manhole_tank_sound_timer"
					UpperRandomBound = "4"
					UseRandomTime = "1"
					origin = Vector( -24, 16, 32 )
					connections =
					{
						OnTimer =
						{
							cmd1 = "manhole_tank_sound_pickerPickRandom0-1"
						}
					}
				}
			}
			manhole_model = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					disableshadows = "1"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_placeable/manhole_helper.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					targetname = "manhole_model"
					origin = Vector( 0, 0, 0 )
				}
			}
			manhole_cover_model = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					disableshadows = "1"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "78 184 41"
					glowrange = "200"
					glowstate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_street/manhole_cover.mdl"
					parentname = "manhole_cover_door_1"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "manhole_cover_model"
					origin = Vector( 0, 0, -3 )
				}
			}
			manhole_tank = 
			{
				SpawnInfo =
				{
					classname = "info_zombie_spawn"
					angles = Vector( 0, 0, 0 )
					AttackOnSpawn = "1"
					offer_tank = "1"
					population = "tank"
					targetname = "manhole_tank"
					origin = Vector( 0, 0, -1 )
				}
			}
			manhole_tank_spawn_particles = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "boomer_explode"
					render_in_front = "0"
					start_active = "0"
					targetname = "manhole_tank_spawn_particles"
					origin = Vector( 0, 0, -1 )
				}
			}
			manhole_tank_release_rl = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "manhole_tank_release_rl"
					origin = Vector( 32, -32, 7 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "manhole_tank_spawn_particlesStart0-1"
							cmd2 = "manhole_tankSpawnZombie0.3-1"
							cmd3 = "manhole_cover_door_flushOpen0-1"
							cmd4 = "manhole_cover_shooterShoot0-1"
							cmd5 = "manhole_tank_shakeStartShake0-1"
							cmd6 = "manhole_tank_spawn_particlesStop4-1"
							cmd7 = "manhole_cover_rattle_timerDisable0-1"
							cmd8 = "manhole_tank_sound_timerDisable0-1"
							cmd9 = "manhole_tank_sound8PlaySound0-1"
							cmd10 = "manhole_cover_door_1_break_soundPlaySound0-1"
							cmd11 = "manhole_tank_cleanup_relayTrigger0-1"
							cmd12 = "hint_tank_spawnFireUser40-1"
						}
					}
				}
			}
			manhole_cover_rattle_timer = 
			{
				SpawnInfo =
				{
					classname = "logic_timer"
					LowerRandomBound = "1"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "manhole_cover_rattle_timer"
					UpperRandomBound = "3"
					UseRandomTime = "1"
					origin = Vector( 27, 18, 7 )
					connections =
					{
						OnTimer =
						{
							cmd1 = "manhole_cover_rattle_casePickRandom0-1"
							cmd2 = "manhole_cover_dustStart0-1"
							cmd3 = "manhole_cover_dustStop1.5-1"
							cmd4 = "manhole_cover_shakeStartShake0-1"
						}
					}
				}
			}
			manhole_cover_door_1 = 
			{
				SpawnInfo =
				{
					classname = "func_door_rotating"
					always_fire_blocked_outputs = "0"
					angles = Vector( 0, 0, 0 )
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					distance = "3"
					dmg = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forceclosed = "0"
					health = "0"
					ignoredebris = "0"
					lip = "0"
					locked_sentence = "0"
					loopmovesound = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					origin = Vector( 0, 0, 4.5 )
					parentname = "manhole_cover_door_2"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					solidbsp = "0"
					spawnflags = "397934"
					spawnpos = "0"
					speed = "250"
					targetname = "manhole_cover_door_1"
					unlocked_sentence = "0"
					wait = "4"
					connections =
					{
						OnOpen =
						{
							cmd1 = "manhole_cover_door_1_open_soundPlaySound0-1"
						}
						OnFullyOpen =
						{
							cmd1 = "!selfClose0-1"
						}
					}
				}
			}
			manhole_cover_door_1_open_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "Doors.Metal.Pound1"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "0"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "manhole_cover_door_1_open_sound"
					volstart = "0"
					origin = Vector( -9.36902, 19.491, 7.2557 )
				}
			}
			manhole_cover_door_2 = 
			{
				SpawnInfo =
				{
					classname = "func_door_rotating"
					always_fire_blocked_outputs = "0"
					angles = Vector( 0, 0, 0 )
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					distance = "3"
					dmg = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forceclosed = "0"
					health = "0"
					ignoredebris = "0"
					lip = "0"
					locked_sentence = "0"
					loopmovesound = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					origin = Vector( 0, 0, 8.5 )
					parentname = "manhole_cover_door_3"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					solidbsp = "0"
					spawnflags = "397996"
					spawnpos = "0"
					speed = "250"
					targetname = "manhole_cover_door_2"
					unlocked_sentence = "0"
					wait = "4"
					connections =
					{
						OnOpen =
						{
							cmd1 = "manhole_cover_door_1_open_soundPlaySound0-1"
						}
						OnFullyOpen =
						{
							cmd1 = "!selfClose0-1"
						}
					}
				}
			}
			manhole_cover_rattle_case = 
			{
				SpawnInfo =
				{
					classname = "logic_case"
					targetname = "manhole_cover_rattle_case"
					origin = Vector( 27, -1, 8.2557 )
					connections =
					{
						OnCase02 =
						{
							cmd1 = "manhole_cover_door_2Open0-1"
						}
						OnCase01 =
						{
							cmd1 = "manhole_cover_door_1Open0-1"
						}
						OnCase03 =
						{
							cmd1 = "manhole_cover_door_3Open0-1"
						}
					}
				}
			}
			manhole_cover_door_3 = 
			{
				SpawnInfo =
				{
					classname = "func_door"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					dmg = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forceclosed = "0"
					health = "0"
					ignoredebris = "0"
					lip = "0"
					locked_sentence = "0"
					loopmovesound = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					movedir = "90 0 0"
					origin = Vector( 0, 0, 13 )
					parentname = "manhole_cover_door_flush"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					spawnflags = "397868"
					spawnpos = "0"
					speed = "250"
					targetname = "manhole_cover_door_3"
					unlocked_sentence = "0"
					wait = "4"
					connections =
					{
						OnOpen =
						{
							cmd1 = "manhole_cover_door_1_open_soundPlaySound0-1"
						}
						OnFullyOpen =
						{
							cmd1 = "!selfClose0-1"
						}
					}
				}
			}
			manhole_cover_door_flush = 
			{
				SpawnInfo =
				{
					classname = "func_door"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					dmg = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forceclosed = "0"
					health = "0"
					ignoredebris = "0"
					lip = "0"
					locked_sentence = "0"
					loopmovesound = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					movedir = "-90 0 0"
					origin = Vector( -29, 0, 13 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					spawnflags = "397868"
					spawnpos = "0"
					speed = "250"
					targetname = "manhole_cover_door_flush"
					unlocked_sentence = "0"
					wait = "4"
					connections =
					{
						OnOpen =
						{
							cmd1 = "manhole_cover_door_1_open_soundPlaySound0-1"
						}
					}
				}
			}
			manhole_tank_start_rattle_rl = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "manhole_tank_start_rattle_rl"
					origin = Vector( 0, -32, 7 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "manhole_cover_rattle_timerEnable0.1-1"
							cmd2 = "manhole_cover_door_flushOpen0-1"
							cmd3 = "manhole_cover_modelEnable0-1"
							cmd4 = "manhole_cover_modelStartGlowing0.05-1"
							cmd5 = "manhole_tank_sound_timerEnable0.1-1"
							cmd6 = "usetarget_tank_manholeRunScriptCodeEnableBuildPanel()0-1"
							cmd7 = "hintFireUser401"
							cmd8 = "hint_tank_spawnShowHint0.2-1"
						}
					}
				}
			}
			manhole_tank_stop_rattle_rl = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "manhole_tank_stop_rattle_rl"
					origin = Vector( 16, -32, 7 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "manhole_cover_rattle_timerDisable0-1"
							cmd2 = "manhole_cover_door_flushClose0-1"
							cmd3 = "manhole_cover_modelStopGlowing0-1"
							cmd4 = "manhole_tank_sound_timerDisable0-1"
						}
					}
				}
			}
			manhole_cover_dust = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( -90, 270, 0 )
					effect_name = "awning_collapse_dust"
					targetname = "manhole_cover_dust"
					origin = Vector( 0, 0, 2 )
				}
			}
			usetarget_tank_manhole = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "manhole_cover_model"
					origin = Vector( -32, 32, 6 )
					targetname = "usetarget_tank_manhole"
					vscripts = "usetargets/tank_barricade"
					connections =
					{
						OnUser1 =
						{
							cmd1 = "manhole_tank_scriptRunScriptCodeSetTankBarnBarricaded()0-1"
							cmd2 = "manhole_boards_templateForceSpawn0-1"
							cmd3 = "!selfRunScriptCodeDisableBuildPanel()0-1"
							cmd4 = "hint_tank_spawnEndHint0-1"
							cmd5 = "hint_tank_barricadedShowHint01"
						}
					}
				}
			}
			manhole_cover_shooter = 
			{
				SpawnInfo =
				{
					classname = "env_shooter"
					angles = Vector( -90, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					gibangles = "0 0 0"
					gibanglevelocity = "100"
					gibgravityscale = "1"
					m_flGibLife = "6"
					m_flVariance = "0"
					m_flVelocity = "1000"
					m_iGibs = "1"
					renderamt = "255"
					rendercolor = "255 255 255"
					shootmodel = "models/props_street/manhole_cover.mdl"
					shootsounds = "-1"
					simulation = "1"
					spawnflags = "4"
					targetname = "manhole_cover_shooter"
					origin = Vector( 0, 0, -2 )
				}
			}
			manhole_tank_shake = 
			{
				SpawnInfo =
				{
					classname = "env_shake"
					amplitude = "4"
					duration = "1"
					frequency = "100"
					radius = "1320"
					spawnflags = "0"
					targetname = "manhole_tank_shake"
					origin = Vector( -32, 16, 6 )
				}
			}
			manhole_boards = 
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( -90, 7.5, 0 )
					body = "0"
					BreakableType = "0"
					damagefilter = "manhole_boards_filter"
					damagetoenablemotion = "0"
					Damagetype = "0"
					disablereceiveshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					inertiaScale = "1.0"
					massScale = "0"
					minhealthdmg = "0"
					model = "models/props_debris/wood_board04a.mdl"
					nodamageforces = "0"
					PerformanceMode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "1294"
					targetname = "manhole_boards"
					origin = Vector( -2, 20, 1 )
				}
			}
			manhole_boards1 = 
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( -90, 17.5, 0 )
					body = "0"
					BreakableType = "0"
					damagefilter = "manhole_boards_filter"
					damagetoenablemotion = "0"
					Damagetype = "0"
					disablereceiveshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					inertiaScale = "1.0"
					massScale = "0"
					minhealthdmg = "0"
					model = "models/props_debris/wood_board04a.mdl"
					nodamageforces = "0"
					PerformanceMode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "1294"
					targetname = "manhole_boards"
					origin = Vector( 3, -24, 1 )
				}
			}
			manhole_boards2 = 
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( -90, 120, 0 )
					body = "0"
					BreakableType = "0"
					damagefilter = "manhole_boards_filter"
					damagetoenablemotion = "0"
					Damagetype = "0"
					disablereceiveshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					inertiaScale = "1.0"
					massScale = "0"
					minhealthdmg = "0"
					model = "models/props_debris/wood_board04a.mdl"
					nodamageforces = "0"
					PerformanceMode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "1294"
					targetname = "manhole_boards"
					origin = Vector( 4.00006, -2.28882e-005, 0 )
				}
			}
			manhole_boards_template = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "2"
					targetname = "manhole_boards_template"
					Template01 = "manhole_boards"
					Template02 = "manhole_tank_quiet_sound"
					origin = Vector( -15.445, -12.2686, 7.25576 )
					connections =
					{
						OnEntitySpawned =
						{
							cmd1 = "manhole_tank_quiet_soundPlaySound0-1"
						}
					}
				}
			}
			manhole_boards_filter = 
			{
				SpawnInfo =
				{
					classname = "filter_activator_name"
					filtername = "null"
					Negated = "Allow entities that match criteria"
					targetname = "manhole_boards_filter"
					origin = Vector( -24, -13, 7 )
				}
			}
			manhole_tank_script = 
			{
				SpawnInfo =
				{
					classname = "logic_script"
					Group00 = "manhole_tank_start_rattle_rl"
					Group01 = "manhole_tank_stop_rattle_rl"
					Group02 = "manhole_tank_release_rl"
					Group03 = "manhole_tank_board_break_rl"
					Group04 = "usetarget_tank_manhole"
					targetname = "manhole_tank_script"
					vscripts = "tank_spawn_manager"
					origin = Vector( -31, -30, 7 )
				}
			}
			manhole_tank_board_break_rl = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "manhole_tank_board_break_rl"
					origin = Vector( -16, -32, 7 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "manhole_boardsBreak0-1"
						}
					}
				}
			}
			manhole_cover_shake = 
			{
				SpawnInfo =
				{
					classname = "env_shake"
					amplitude = "4"
					duration = ".7"
					frequency = "50"
					radius = "400"
					spawnflags = "0"
					targetname = "manhole_cover_shake"
					origin = Vector( -24, 8, 6 )
				}
			}
			manhole_cover_door_1_break_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "MetalGrate.ImpactHard"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "0"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "manhole_cover_door_1_break_sound"
					volstart = "0"
					origin = Vector( 16, 16, 7.2557 )
				}
			}
			manhole_tank_cleanup_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "1"
					targetname = "manhole_tank_cleanup_relay"
					origin = Vector( 32, -16, 7 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "manhole_cover_modelKill0-1"
							cmd2 = "manhole_tank_sound_pickerKill0-1"
							cmd3 = "manhole_tank_sound_timerKill0-1"
							cmd4 = "manhole_tank_sound1Kill0.2-1"
							cmd5 = "manhole_tank_sound2Kill0.2-1"
							cmd6 = "manhole_tank_sound3Kill0.2-1"
							cmd7 = "manhole_tank_sound4Kill0.2-1"
							cmd8 = "manhole_tank_sound5Kill0.2-1"
							cmd9 = "manhole_tank_sound6Kill0.2-1"
							cmd10 = "manhole_tank_sound7Kill0.2-1"
							cmd11 = "manhole_tank_sound8Kill0.2-1"
							cmd12 = "manhole_tank_sound9Kill0.2-1"
							cmd13 = "manhole_tankKill1-1"
							cmd14 = "manhole_cover_door_1_open_soundKill0-1"
							cmd15 = "manhole_cover_door_1_break_soundKill0-1"
							cmd16 = "manhole_cover_door_flushKill0-1"
							cmd17 = "manhole_cover_dustKill2-1"
							cmd18 = "manhole_tank_spawn_particlesKill5-1"
							cmd19 = "manhole_cover_rattle_timerKill0-1"
							cmd20 = "manhole_cover_rattle_caseKill0-1"
							cmd21 = "manhole_tank_shakeKill2-1"
							cmd22 = "manhole_cover_shakeKill2-1"
							cmd23 = "manhole_boards_templateKill0-1"
							cmd24 = "manhole_tank_board_break_rlKill0-1"
							cmd25 = "manhole_tank_start_rattle_rlKill0-1"
							cmd26 = "manhole_tank_stop_rattle_rlKill0-1"
							cmd27 = "manhole_boards_filterKill0-1"
							cmd28 = "manhole_tank_release_rlKill1-1"
							cmd29 = "manhole_tank_quiet_soundKill0-1"
						}
					}
				}
			}
			manhole_tank_quiet_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "HulkZombie.Breathe"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "0"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "manhole_tank_quiet_sound"
					volstart = "0"
					origin = Vector( 0, -24, 23 )
				}
			}
			hint = 
			{
				SpawnInfo =
				{
					classname = "env_instructor_hint"
					hint_allow_nodraw_target = "1"
					hint_alphaoption = "0"
					hint_auto_start = "1"
					hint_caption = "This looks suspicious..."
					hint_color = "255 255 255"
					hint_display_limit = "1"
					hint_forcecaption = "1"
					hint_icon_offscreen = "icon_tip"
					hint_icon_offset = "0"
					hint_icon_onscreen = "icon_skull"
					hint_instance_type = "2"
					hint_name = "tank_manhole_lesson"
					hint_nooffscreen = "1"
					hint_pulseoption = "0"
					hint_range = "80"
					hint_shakeoption = "0"
					hint_static = "0"
					hint_suppress_rest = "1"
					hint_target = "manhole_model"
					hint_timeout = "5"
					targetname = "hint"
					origin = Vector( 0, 0, 32.64 )
					connections =
					{
						OnUser4 =
						{
							cmd1 = "!selfEndHint0-1"
							cmd2 = "!selfKill0.01-1"
						}
					}
				}
			}
			hint_branch = 
			{
				SpawnInfo =
				{
					classname = "logic_branch"
					InitialValue = "$show_hint"
					targetname = "hint_branch"
					origin = Vector( 24, 0, 16.64 )
					connections =
					{
						OnFalse =
						{
							cmd1 = "!selfKill0-1"
							cmd2 = "hintFireUser40-1"
							cmd3 = "hint_tank_spawnFireUser40-1"
							cmd4 = "hint_tank_barricadedFireUser40-1"
						}
						OnTrue =
						{
							cmd1 = "!selfKill0.1-1"
						}
					}
				}
			}
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "logic_auto"
					spawnflags = "1"
					origin = Vector( 24, 0, 16.64 )
					connections =
					{
						OnMapSpawn =
						{
							cmd1 = "hint_branchTest0-1"
						}
					}
				}
			}
			hint_tank_spawn = 
			{
				SpawnInfo =
				{
					classname = "env_instructor_hint"
					hint_allow_nodraw_target = "1"
					hint_alphaoption = "0"
					hint_auto_start = "0"
					hint_caption = "Something is escaping! Spend supplies prevent it!"
					hint_color = "255 255 255"
					hint_display_limit = "2"
					hint_forcecaption = "1"
					hint_icon_offscreen = "icon_skull"
					hint_icon_offset = "0"
					hint_icon_onscreen = "icon_interact"
					hint_instance_type = "2"
					hint_name = "tank_manhole_lesson"
					hint_nooffscreen = "0"
					hint_pulseoption = "0"
					hint_range = "0"
					hint_shakeoption = "0"
					hint_static = "0"
					hint_suppress_rest = "1"
					hint_target = "manhole_model"
					hint_timeout = "0"
					targetname = "hint_tank_spawn"
					origin = Vector( 0, 0, 16.64 )
					connections =
					{
						OnUser4 =
						{
							cmd1 = "!selfEndHint0-1"
							cmd2 = "!selfKill0.01-1"
						}
					}
				}
			}
			hint_tank_barricaded = 
			{
				SpawnInfo =
				{
					classname = "env_instructor_hint"
					hint_allow_nodraw_target = "1"
					hint_alphaoption = "0"
					hint_auto_start = "0"
					hint_caption = "Manhole barricaded! Whatever it was it will try again next wave.  Prepare!"
					hint_color = "255 255 255"
					hint_display_limit = "1"
					hint_forcecaption = "1"
					hint_icon_offscreen = "icon_info"
					hint_icon_offset = "0"
					hint_icon_onscreen = "icon_tip"
					hint_instance_type = "2"
					hint_name = "tank_manhole_lesson"
					hint_nooffscreen = "0"
					hint_pulseoption = "0"
					hint_range = "350"
					hint_shakeoption = "0"
					hint_static = "1"
					hint_suppress_rest = "1"
					hint_target = "manhole_model"
					hint_timeout = "15"
					targetname = "hint_tank_barricaded"
					origin = Vector( -24, 0, 16.64 )
					connections =
					{
						OnUser4 =
						{
							cmd1 = "!selfEndHint0-1"
							cmd2 = "!selfKill0.01-1"
						}
					}
				}
			}
		} // SpawnTables

		ReplaceParmDefaults =
		{
			"$show_hint" : "0"
		}
	} // EntityGroup
} // TankManhole

RegisterEntityGroup( "TankManhole", TankManhole )
