//-------------------------------------------------------
// Autogenerated from 'tier1_weapon_cabinet.vmf'
//-------------------------------------------------------
Tier1WeaponCabinet <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.static_tier1_weapon,
			EntityGroup.SpawnTables.static_tier1_weapon1,
			EntityGroup.SpawnTables.static_tier1_weapon2,
			EntityGroup.SpawnTables.static_tier1_weapon3,
			EntityGroup.SpawnTables.ammo_cabinet,
			EntityGroup.SpawnTables.gun_cabinet_door,
			EntityGroup.SpawnTables.static_tier1_weapon4,
			EntityGroup.SpawnTables.gun_cabinet_door1,
			EntityGroup.SpawnTables.unnamed1,
			EntityGroup.SpawnTables.unnamed3,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.unnamed3,
			EntityGroup.SpawnTables.unnamed2,
			EntityGroup.SpawnTables.unnamed1,
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.template_tier_1,
			EntityGroup.SpawnTables.static_tier1_weapon4,
			EntityGroup.SpawnTables.static_tier1_weapon3,
			EntityGroup.SpawnTables.static_tier1_weapon2,
			EntityGroup.SpawnTables.static_tier1_weapon1,
			EntityGroup.SpawnTables.static_tier1_weapon,
			EntityGroup.SpawnTables.hint_branch,
			EntityGroup.SpawnTables.use_target_cabinet,
			EntityGroup.SpawnTables.hint,
			EntityGroup.SpawnTables.gun_cabinet_door_rotator,
			EntityGroup.SpawnTables.relay_restock_tier_1,
			EntityGroup.SpawnTables.ammo_cabinet,
			EntityGroup.SpawnTables.gun_cabinet_door1,
			EntityGroup.SpawnTables.gun_cabinet_door,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			static_tier1_weapon = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( -84, 161, 180 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/w_models/weapons/w_pumpshotgun_a.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "static_tier1_weapon"
					updatechildren = "0"
					origin = Vector( -4.73548, -8.37084, 28 )
				}
			}
			pump_shotgun = 
			{
				SpawnInfo =
				{
					classname = "weapon_pumpshotgun_spawn"
					angles = Vector( -84, 161, 180 )
					body = "0"
					count = "1"
					disableshadows = "1"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "pump_shotgun"
					origin = Vector( -4.73548, -8.37084, 28 )
				}
			}
			smg = 
			{
				SpawnInfo =
				{
					classname = "weapon_smg_spawn"
					angles = Vector( -84, 163.5, -180 )
					body = "0"
					count = "1"
					disableshadows = "1"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "smg"
					origin = Vector( -6.83591, -12.5589, 47.592 )
				}
			}
			static_tier1_weapon1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( -84, 163.5, -180 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/w_models/weapons/w_smg_uzi.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "static_tier1_weapon"
					updatechildren = "0"
					origin = Vector( -6.83591, -12.5589, 47.592 )
				}
			}
			chrome_shotgun = 
			{
				SpawnInfo =
				{
					classname = "weapon_shotgun_chrome_spawn"
					angles = Vector( -84, 191, 180 )
					body = "0"
					count = "1"
					disableshadows = "1"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "chrome_shotgun"
					origin = Vector( -4.05299, 6.93572, 28 )
				}
			}
			static_tier1_weapon2 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( -84, 191, 180 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/w_models/weapons/w_pumpshotgun_a.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "static_tier1_weapon"
					updatechildren = "0"
					origin = Vector( -4.05299, 6.93572, 28 )
				}
			}
			static_tier1_weapon3 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( -84, 168.5, -180 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/w_models/weapons/w_smg_a.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "static_tier1_weapon"
					updatechildren = "0"
					origin = Vector( -6.00673, 12.0069, 48.592 )
				}
			}
			silenced_smg = 
			{
				SpawnInfo =
				{
					classname = "weapon_smg_silenced_spawn"
					angles = Vector( -84, 168.5, -180 )
					body = "0"
					count = "1"
					disableshadows = "1"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "silenced_smg"
					origin = Vector( -6.00673, 12.0069, 48.592 )
				}
			}
			use_target_cabinet = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "gun_cabinet_door"
					origin = Vector( 1, 0, 27 )
					targetname = "use_target_cabinet"
					vscripts = "usetargets/ammo_cabinet_tier_1"
					connections =
					{
						OnUser1 =
						{
							cmd1 = "relay_restock_tier_1Trigger0-1"
							cmd2 = "gun_cabinet_door_rotatorOpen0-1"
							cmd3 = "!selfKill0-1"
							cmd4 = "hintFireUser401"
						}
					}
				}
			}
			template_tier_1 = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "2"
					targetname = "template_tier_1"
					Template01 = "smg"
					Template02 = "pump_shotgun"
					Template03 = "chrome_shotgun"
					Template04 = "silenced_smg"
					Template05 = "pistol"
					origin = Vector( -6, 1, 47 )
				}
			}
			relay_restock_tier_1 = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "relay_restock_tier_1"
					origin = Vector( -6, 1, 27 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "template_tier_1ForceSpawn0.01-1"
							cmd2 = "static_tier1_weaponKill01"
						}
					}
				}
			}
			ammo_cabinet = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "0"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_unique/guncabinet_no_door.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "ammo_cabinet"
					updatechildren = "0"
					origin = Vector( 0.352388, 0, 0 )
				}
			}
			pistol = 
			{
				SpawnInfo =
				{
					classname = "weapon_pistol_spawn"
					angles = Vector( 45, 270, 0 )
					body = "0"
					count = "1"
					disableshadows = "1"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "pistol"
					origin = Vector( -13, 13, 71 )
				}
			}
			gun_cabinet_door = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "800"
					fademindist = "537"
					fadescale = "1"
					glowbackfacemult = ".1"
					glowcolor = "0 0 0"
					glowrange = "240"
					glowrangemin = "0"
					glowstate = "3"
					LagCompensate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_unique/guncabinet_door.mdl"
					parentname = "gun_cabinet_door_rotator"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "gun_cabinet_door"
					updatechildren = "0"
					origin = Vector( 0.352388, 0, 0 )
				}
			}
			gun_cabinet_door_rotator = 
			{
				SpawnInfo =
				{
					classname = "func_door_rotating"
					always_fire_blocked_outputs = "0"
					angles = Vector( 0, 0, 0 )
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					distance = "200"
					dmg = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forceclosed = "0"
					health = "0"
					ignoredebris = "0"
					lip = "0"
					locked_sentence = "0"
					loopmovesound = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					origin = Vector( 0.5, 14.5, 40.01 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					solidbsp = "0"
					spawnflags = "60"
					spawnpos = "0"
					speed = "300"
					targetname = "gun_cabinet_door_rotator"
					unlocked_sentence = "0"
					wait = "4"
					connections =
					{
						OnFullyOpen =
						{
							cmd1 = "gun_cabinet_doorKill0-1"
							cmd2 = "!selfKill0-1"
						}
						OnOpen =
						{
							cmd1 = "gun_cabinet_doorDisableCollision0-1"
							cmd2 = "gun_cabinet_doorStopGlowing0-1"
						}
					}
				}
			}
			static_tier1_weapon4 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 45, 270, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					health = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/w_models/weapons/w_pistol_a.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "static_tier1_weapon"
					updatechildren = "0"
					origin = Vector( -13, 13, 71 )
				}
			}
			hint = 
			{
				SpawnInfo =
				{
					classname = "env_instructor_hint"
					hint_allow_nodraw_target = "1"
					hint_alphaoption = "0"
					hint_auto_start = "1"
					hint_binding = "+use"
					hint_caption = "These guns are free!"
					hint_color = "255 255 255"
					hint_display_limit = "2"
					hint_forcecaption = "1"
					hint_icon_offscreen = "icon_tip"
					hint_icon_offset = "0"
					hint_icon_onscreen = "use_binding"
					hint_instance_type = "2"
					hint_name = "tier1_weapon_cabinet_lesson"
					hint_nooffscreen = "1"
					hint_pulseoption = "0"
					hint_range = "200"
					hint_shakeoption = "0"
					hint_static = "0"
					hint_suppress_rest = "1"
					hint_target = "gun_cabinet_door"
					hint_timeout = "10"
					targetname = "hint"
					origin = Vector( 9, 0.461926, 64.2918 )
					connections =
					{
						OnUser4 =
						{
							cmd1 = "!selfEndHint0-1"
							cmd2 = "!selfKill0.01-1"
						}
					}
				}
			}
			hint_branch = 
			{
				SpawnInfo =
				{
					classname = "logic_branch"
					InitialValue = "$show_hint"
					targetname = "hint_branch"
					origin = Vector( 9, 0.461926, 64.2918 )
					connections =
					{
						OnFalse =
						{
							cmd1 = "!selfKill0-1"
							cmd2 = "hintFireUser40-1"
						}
						OnTrue =
						{
							cmd1 = "!selfKill0.1-1"
						}
					}
				}
			}
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "logic_auto"
					spawnflags = "1"
					origin = Vector( 9, 0.461926, 64.2918 )
					connections =
					{
						OnMapSpawn =
						{
							cmd1 = "hint_branchTest0-1"
						}
					}
				}
			}
			gun_cabinet_door1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "800"
					fademindist = "537"
					fadescale = "1"
					glowbackfacemult = ".1"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_unique/guncabinet_door_bars.mdl"
					parentname = "gun_cabinet_door_rotator"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "gun_cabinet_door"
					updatechildren = "0"
					origin = Vector( 0.352388, 0, 0 )
				}
			}
			unnamed1 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props/cs_office/light_inset.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					updatechildren = "0"
					origin = Vector( -7, 0, 79 )
				}
			}
			unnamed2 = 
			{
				SpawnInfo =
				{
					classname = "logic_auto"
					spawnflags = "1"
					origin = Vector( -8, 0, 10 )
					connections =
					{
						OnMapSpawn =
						{
							cmd1 = "ammo_cabinetSkin10-1"
						}
					}
				}
			}
			unnamed3 = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic"
					angles = Vector( 0, 0, 0 )
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "0 0 0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_placeable/tier1_guns_trophy.mdl"
					renderamt = "255"
					rendercolor = "255 255 255"
					skin = "0"
					solid = "6"
					origin = Vector( -8, 0, 79 )
				}
			}
		} // SpawnTables

		ReplaceParmDefaults =
		{
			"$show_hint" : "0"
		}
	} // EntityGroup
} // Tier1WeaponCabinet

RegisterEntityGroup( "Tier1WeaponCabinet", Tier1WeaponCabinet )
