//-------------------------------------------------------
// Autogenerated from 'wall_barricade.vmf'
//-------------------------------------------------------
WallBarricade <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.boards,
			EntityGroup.SpawnTables.boards1,
			EntityGroup.SpawnTables.button,
			EntityGroup.SpawnTables.top_board,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.boards_build_snd_2,
			EntityGroup.SpawnTables.unnamed2,
			EntityGroup.SpawnTables.unnamed1,
			EntityGroup.SpawnTables.unnamed,
			EntityGroup.SpawnTables.boards_build_snd_1,
			EntityGroup.SpawnTables.template_boards_window,
			EntityGroup.SpawnTables.blocker_wall,
			EntityGroup.SpawnTables.hint_branch,
			EntityGroup.SpawnTables.relay_clean_and_spawn_window,
			EntityGroup.SpawnTables.useTarget,
			EntityGroup.SpawnTables.relay_build_sounds,
			EntityGroup.SpawnTables.hint,
			EntityGroup.SpawnTables.timer_navblocker,
			EntityGroup.SpawnTables.button,
			EntityGroup.SpawnTables.trigger_reset_relay,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			template_boards_window = 
			{
				SpawnInfo =
				{
					classname = "point_script_template"
					spawnflags = "2"
					targetname = "template_boards_window"
					Template01 = "boards"
					Template02 = "top_board"
					origin = Vector( 4, 0, 33 )
					connections =
					{
						OnEntitySpawned =
						{
							cmd1 = "boardsSethealth25000-1"
						}
					}
				}
			}
			timer_navblocker = 
			{
				SpawnInfo =
				{
					classname = "logic_timer"
					LowerRandomBound = "15"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "timer_navblocker"
					UpperRandomBound = "30"
					UseRandomTime = "1"
					origin = Vector( 4, -52, 16 )
					connections =
					{
						OnTimer =
						{
							cmd1 = "blocker_wallUnblockNav0-1"
							cmd2 = "timer_navblockerDisable0.1-1"
						}
					}
				}
			}
			boards = 
			{
				SpawnInfo =
				{
					classname = "prop_door_rotating"
					ajarangles = "0 0 0"
					angles = Vector( 0, 0, 0 )
					axis = "1 -32 8.62, 1 -32 8.62"
					body = "0"
					disableshadows = "1"
					distance = "90"
					dmg = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forceclosed = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					hardware = "1"
					health = "0"
					model = "models/props_doors/shackwall01.mdl"
					opendir = "0"
					rendercolor = "255 255 255"
					returndelay = "-1"
					skin = "0"
					spawnflags = "22528"
					spawnpos = "0"
					speed = "200"
					targetname = "boards"
					origin = Vector( 1, -32, 8.6167 )
					connections =
					{
						OnBreak =
						{
							cmd1 = "useTargetRunScriptCodeNeedsRepairs()0-1"
						}
					}
				}
			}
			boards1 = 
			{
				SpawnInfo =
				{
					classname = "prop_door_rotating"
					ajarangles = "0 0 0"
					angles = Vector( 0, 0, 0 )
					axis = "1 32 8.62, 1 32 8.62"
					body = "0"
					disableshadows = "1"
					distance = "90"
					dmg = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forceclosed = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					hardware = "1"
					health = "0"
					model = "models/props_doors/shackwall01.mdl"
					opendir = "0"
					rendercolor = "255 255 255"
					returndelay = "-1"
					skin = "0"
					spawnflags = "22528"
					spawnpos = "0"
					speed = "200"
					targetname = "boards"
					origin = Vector( 1, 32, 8.6167 )
					connections =
					{
						OnBreak =
						{
							cmd1 = "useTargetRunScriptCodeNeedsRepairs()0-1"
						}
					}
				}
			}
			relay_clean_and_spawn_window = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					StartDisabled = "0"
					targetname = "relay_clean_and_spawn_window"
					origin = Vector( 4, 40, 29 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "boardsKill0-1"
							cmd2 = "template_boards_windowForceSpawn0.1-1"
							cmd3 = "blocker_wallBlockNav0-1"
							cmd4 = "timer_navblockerEnable0-1"
							cmd5 = "relay_build_soundsTrigger0-1"
							cmd6 = "hintFireUser401"
						}
					}
				}
			}
			useTarget = 
			{
				SpawnInfo =
				{
					classname = "point_script_use_target"
					model = "button"
					origin = Vector( 4, -16, 16 )
					targetname = "useTarget"
					vscripts = "usetargets/wall"
					connections =
					{
						OnUser1 =
						{
							cmd1 = "relay_clean_and_spawn_windowTrigger0-1"
						}
					}
				}
			}
			blocker_wall = 
			{
				SpawnInfo =
				{
					classname = "script_nav_blocker"
					affectsFlow = "1"
					StartDisabled = "0"
					targetname = "blocker_wall"
					teamToBlock = "-1"
					extent = Vector( 12, 64, 64 )
					origin = Vector( 0, 0, 64 )
				}
			}
			button = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 0, 0, 0 )
					body = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "0.5"
					glowcolor = "103 146 14"
					glowrange = "160"
					glowrangemin = "0"
					glowstate = "3"
					health = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					maxcpulevel = "0"
					maxgpulevel = "0"
					MinAnimTime = "5"
					mincpulevel = "0"
					mingpulevel = "0"
					model = "models/props_buildables/wall_barricade_button.mdl"
					PerformanceMode = "0"
					pressuredelay = "0"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "6"
					spawnflags = "0"
					targetname = "button"
					updatechildren = "0"
					origin = Vector( 0, 0, -1 )
				}
			}
			top_board = 
			{
				SpawnInfo =
				{
					classname = "prop_physics"
					angles = Vector( 0, 0, -90 )
					body = "0"
					BreakableType = "0"
					damagetoenablemotion = "0"
					Damagetype = "0"
					disablereceiveshadows = "0"
					disableshadows = "1"
					disableX360 = "0"
					ExplodeDamage = "0"
					ExplodeRadius = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forcetoenablemotion = "0"
					glowcolor = "0 0 0"
					glowrange = "0"
					glowrangemin = "0"
					glowstate = "0"
					inertiaScale = "1.0"
					massScale = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					minhealthdmg = "0"
					model = "models/props_debris/wood_board05a.mdl"
					nodamageforces = "0"
					PerformanceMode = "0"
					physdamagescale = "0.1"
					pressuredelay = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shadowcastdist = "0"
					skin = "0"
					spawnflags = "264"
					targetname = "top_board"
					origin = Vector( 0, 1, 119 )
				}
			}
			unnamed = 
			{
				SpawnInfo =
				{
					classname = "script_trigger_multiple"
					allowghost = "0"
					allowincap = "0"
					entireteam = "0"
					origin = Vector( 0, 0, 64 )
					spawnflags = "2"
					StartDisabled = "0"
					wait = "1"
					extent = Vector( 12, 64, 64 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "useTargetRunScriptCodeWindowBlocked()0-1"
							cmd2 = "trigger_reset_relayTrigger0-1"
						}
						OnEndTouchAll =
						{
							cmd1 = "useTargetRunScriptCodeWindowUnblocked()0-1"
							cmd2 = "trigger_reset_relayCancelPending0-1"
						}
					}
				}
			}
			unnamed1 = 
			{
				SpawnInfo =
				{
					classname = "logic_auto"
					spawnflags = "1"
					origin = Vector( 4, -16, 88 )
					connections =
					{
						OnMapSpawn =
						{
							cmd1 = "relay_build_soundsEnable1-1"
						}
					}
				}
			}
			boards_build_snd_1 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "Wood.ImpactHard"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "boards_build_snd_1"
					origin = Vector( 4, 0, 72 )
				}
			}
			boards_build_snd_2 = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "Wood.Bullet1Impact"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "boards_build_snd_2"
					origin = Vector( 4, 0, 56 )
				}
			}
			relay_build_sounds = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					StartDisabled = "1"
					targetname = "relay_build_sounds"
					origin = Vector( 4, 40, 74 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "boards_build_snd_2PlaySound0.1-1"
							cmd2 = "boards_build_snd_2PlaySound0.4-1"
							cmd3 = "boards_build_snd_2PlaySound0.7-1"
							cmd4 = "boards_build_snd_1PlaySound0-1"
						}
					}
				}
			}
			hint = 
			{
				SpawnInfo =
				{
					classname = "env_instructor_hint"
					hint_allow_nodraw_target = "1"
					hint_alphaoption = "0"
					hint_auto_start = "1"
					hint_binding = "+use"
					hint_caption = "Build barricades to block infected"
					hint_color = "255 255 255"
					hint_display_limit = "2"
					hint_forcecaption = "1"
					hint_icon_offscreen = "icon_tip"
					hint_icon_offset = "0"
					hint_icon_onscreen = "use_binding"
					hint_instance_type = "3"
					hint_name = "wall_barricade_lesson"
					hint_nooffscreen = "1"
					hint_pulseoption = "0"
					hint_range = "120"
					hint_shakeoption = "0"
					hint_static = "0"
					hint_suppress_rest = "1"
					hint_target = "button"
					hint_timeout = "5"
					targetname = "hint"
					origin = Vector( 4, -56, 108 )
					connections =
					{
						OnUser4 =
						{
							cmd1 = "!selfEndHint0-1"
							cmd2 = "!selfKill0.01-1"
						}
					}
				}
			}
			hint_branch = 
			{
				SpawnInfo =
				{
					classname = "logic_branch"
					InitialValue = "$show_hint"
					targetname = "hint_branch"
					origin = Vector( -4, -54, 92.1019 )
					connections =
					{
						OnFalse =
						{
							cmd1 = "!selfKill0-1"
							cmd2 = "hintFireUser40-1"
						}
						OnTrue =
						{
							cmd1 = "!selfKill0.1-1"
						}
					}
				}
			}
			unnamed2 = 
			{
				SpawnInfo =
				{
					classname = "logic_auto"
					spawnflags = "1"
					origin = Vector( -4, -54, 92.1019 )
					connections =
					{
						OnMapSpawn =
						{
							cmd1 = "hint_branchTest0-1"
						}
					}
				}
			}
			trigger_reset_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "trigger_reset_relay"
					origin = Vector( 4, 20, 72.3646 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "useTargetRunScriptCodeWindowUnblocked()5-1"
						}
					}
				}
			}
		} // SpawnTables

		ReplaceParmDefaults =
		{
			"$barricade_start_on" : "0"
			"$button_start_off" : "0"
			"$show_hint" : "0"
		}
	} // EntityGroup
} // WallBarricade

RegisterEntityGroup( "WallBarricade", WallBarricade )
