//-------------------------------------------------------
// Autogenerated from 'witch_tombstone.vmf'
//-------------------------------------------------------
WitchTombstone <-
{
	//-------------------------------------------------------
	// Required Interface functions
	//-------------------------------------------------------
	function GetPrecacheList()
	{
		local precacheModels =
		[
			EntityGroup.SpawnTables.tombstone_style_1_basemodel,
			EntityGroup.SpawnTables.tombstone_style_1_lid,
			EntityGroup.SpawnTables.tombstone_witch_model,
		]
		return precacheModels
	}

	//-------------------------------------------------------
	function GetSpawnList()
	{
		local spawnEnts =
		[
			EntityGroup.SpawnTables.tombstone_start_glowing_relay,
			EntityGroup.SpawnTables.tombstone_branch_listener,
			EntityGroup.SpawnTables.tombstone_shake,
			EntityGroup.SpawnTables.tombstone_witch_mover,
			EntityGroup.SpawnTables.tombstone_witch_spawn_gibs3,
			EntityGroup.SpawnTables.tombstone_witch_spawn_gibs2,
			EntityGroup.SpawnTables.tombstone_witch_spawn_gibs1,
			EntityGroup.SpawnTables.tombstone_witch_spawn_gibs,
			EntityGroup.SpawnTables.tombstone_spawn_witch_relay,
			EntityGroup.SpawnTables.tombstone_style_1_lid,
			EntityGroup.SpawnTables.tombstone_glowing_branch,
			EntityGroup.SpawnTables.tombstone_witch_script,
			EntityGroup.SpawnTables.tombstone_witch,
			EntityGroup.SpawnTables.tombstone_witch_alert_sound,
			EntityGroup.SpawnTables.tombstone_hatch_break_sound,
			EntityGroup.SpawnTables.tombstone_hatch_dust,
			EntityGroup.SpawnTables.tombstone_style_1_basemodel,
			EntityGroup.SpawnTables.tombstone_witch_style_case_start_relay,
			EntityGroup.SpawnTables.tombstone_broken_branch,
			EntityGroup.SpawnTables.tombstone_hatch_pound_sound,
			EntityGroup.SpawnTables.tombstone_witch_model,
			EntityGroup.SpawnTables.tombstone_witch_spawn_particles1,
			EntityGroup.SpawnTables.tombstone_witch_spawn_particles,
			EntityGroup.SpawnTables.tombstone_witch_alert_timer,
			EntityGroup.SpawnTables.tombstone_hatch_timer,
			EntityGroup.SpawnTables.tombstone_witch_hatch_mover,
			EntityGroup.SpawnTables.tombstone_cleanup_relay,
			EntityGroup.SpawnTables.tombstone_witch_emerge_particles,
			EntityGroup.SpawnTables.tombstone_filter,
		]
		return spawnEnts
	}

	//-------------------------------------------------------
	function GetEntityGroup()
	{
		return EntityGroup
	}

	//-------------------------------------------------------
	// Table of entities that make up this group
	//-------------------------------------------------------
	EntityGroup =
	{
		SpawnTables =
		{
			tombstone_witch = 
			{
				SpawnInfo =
				{
					classname = "info_zombie_spawn"
					angles = Vector( 0, 0, 0 )
					offer_tank = "0"
					population = "witch"
					targetname = "tombstone_witch"
					origin = Vector( 0, -3.57628e-007, 18 )
				}
			}
			tombstone_style_1_basemodel = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 0, 180, 0 )
					disablereceiveshadows = "0"
					disableshadows = "1"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "255 128 0"
					glowstate = "0"
					health = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_placeable/witch_hatch_base.mdl"
					parentname = "tombstone_witch_mover"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					targetname = "tombstone_style_1_basemodel"
					updatechildren = "0"
					origin = Vector( 0, 2.14577e-006, 0 )
				}
			}
			tombstone_witch_style_case_start_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "tombstone_witch_style_case_start_relay"
					origin = Vector( 0, 16, 96 )
					connections =
					{
						OnSpawn =
						{
							cmd1 = "tombstone_witch_moverOpen0.5-1"
							cmd2 = "!selfKill0.5-1"
							cmd3 = "tombstone_witch_modelTurnOff0-1"
						}
					}
				}
			}
			tombstone_start_glowing_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "tombstone_start_glowing_relay"
					origin = Vector( 0, 2.14577e-006, 112 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "tombstone_style_1_lidStartGlowing0-1"
							cmd2 = "tombstone_glowing_branchSetValue10-1"
							cmd3 = "tombstone_witch_moverClose0-1"
							cmd4 = "tombstone_hatch_timerEnable0-1"
						}
					}
				}
			}
			tombstone_glowing_branch = 
			{
				SpawnInfo =
				{
					classname = "logic_branch"
					targetname = "tombstone_glowing_branch"
					origin = Vector( 0, 16, 80 )
				}
			}
			tombstone_broken_branch = 
			{
				SpawnInfo =
				{
					classname = "logic_branch"
					targetname = "tombstone_broken_branch"
					origin = Vector( 0, -16, 80 )
				}
			}
			tombstone_branch_listener = 
			{
				SpawnInfo =
				{
					classname = "logic_branch_listener"
					Branch01 = "tombstone_broken_branch"
					Branch02 = "tombstone_glowing_branch"
					targetname = "tombstone_branch_listener"
					origin = Vector( 0, 2.14577e-006, 80 )
					connections =
					{
						OnAllTrue =
						{
							cmd1 = "tombstone_style_*TurnOn0-1"
							cmd2 = "tombstone_broken_branchKill0-1"
							cmd3 = "tombstone_glowing_branchKill0-1"
							cmd4 = "tombstone_branch_listenerKill0-1"
						}
					}
				}
			}
			tombstone_spawn_witch_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "0"
					targetname = "tombstone_spawn_witch_relay"
					origin = Vector( 0, -16, 112 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "tombstone_witchSpawnZombie0.1-1"
							cmd2 = "tombstone_cleanup_relayTrigger0-1"
							cmd3 = "tombstone_witch_spawn_particlesStart0-1"
							cmd4 = "tombstone_witch_spawn_particlesStop2-1"
							cmd5 = "tombstone_witch_spawn_gibsShoot0-1"
							cmd6 = "tombstone_witch_spawn_particlesKill3-1"
							cmd7 = "tombstone_style_1_lidBreak0-1"
							cmd8 = "tombstone_hatch_break_soundPlaySound0-1"
							cmd9 = "tombstone_witch_modelKill0-1"
						}
					}
				}
			}
			tombstone_cleanup_relay = 
			{
				SpawnInfo =
				{
					classname = "logic_relay"
					spawnflags = "1"
					targetname = "tombstone_cleanup_relay"
					origin = Vector( 0, -16, 96 )
					connections =
					{
						OnTrigger =
						{
							cmd1 = "tombstone_start_glowing_relayKill0-1"
							cmd2 = "tombstone_branch_listenerKill0-1"
							cmd3 = "tombstone_glowing_branchKill0-1"
							cmd4 = "tombstone_broken_branchKill0-1"
							cmd5 = "tombstone_spawn_witch_relayKill0-1"
							cmd6 = "tombstone_style_1_lidKill0-1"
							cmd7 = "tombstone_witchKill0.2-1"
							cmd8 = "tombstone_shakeKill0-1"
							cmd9 = "tombstone_witch_spawn_gibsKill0.2-1"
							cmd10 = "tombstone_witch_emerge_particlesKill4-1"
							cmd11 = "tombstone_witch_spawn_particlesKill4-1"
							cmd12 = "tombstone_witch_scriptKill1-1"
							cmd13 = "tombstone_witch_moverKill0.1-1"
							cmd14 = "tombstone_filterKill0-1"
							cmd15 = "tombstone_style_1_basemodelKill6-1"
							cmd16 = "tombstone_hatch_timerKill0-1"
							cmd17 = "tombstone_hatch_dustStop1.5-1"
							cmd18 = "tombstone_hatch_dustKill3-1"
							cmd19 = "tombstone_hatch_pound_soundKill1-1"
							cmd20 = "tombstone_witch_hatch_moverKill0-1"
							cmd21 = "tombstone_hatch_break_soundKill2-1"
							cmd22 = "tombstone_witch_alert_timerKill0-1"
							cmd23 = "tombstone_witch_alert_soundKill4-1"
						}
					}
				}
			}
			tombstone_witch_script = 
			{
				SpawnInfo =
				{
					classname = "logic_script"
					Group00 = "tombstone_start_glowing_relay"
					Group01 = "tombstone_spawn_witch_relay"
					Group02 = "tombstone_witch"
					Group03 = "tombstone_cleanup_relay"
					targetname = "tombstone_witch_script"
					vscripts = "witch_spawn_manager"
					origin = Vector( 0, 16, 112 )
				}
			}
			tombstone_witch_spawn_particles = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 180, 0 )
					cpoint1_parent = "0"
					cpoint2_parent = "0"
					cpoint3_parent = "0"
					cpoint4_parent = "0"
					cpoint5_parent = "0"
					cpoint6_parent = "0"
					cpoint7_parent = "0"
					effect_name = "boomer_explode"
					render_in_front = "0"
					start_active = "0"
					targetname = "tombstone_witch_spawn_particles"
					origin = Vector( 1, -5.96046e-007, 2 )
				}
			}
			tombstone_witch_spawn_gibs = 
			{
				SpawnInfo =
				{
					classname = "env_shooter"
					angles = Vector( -90, 0, 0 )
					delay = "0"
					disablereceiveshadows = "0"
					disableX360 = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					gibangles = "0 0 0"
					gibanglevelocity = "0"
					gibgravityscale = "1"
					m_flGibLife = "8"
					m_flVariance = "0.15"
					m_flVelocity = "600"
					m_iGibs = "1"
					massoverride = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					nogibshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shootmodel = "models/gibs/hgibs.mdl"
					shootsounds = "-1"
					simulation = "1"
					skin = "0"
					spawnflags = "4"
					targetname = "tombstone_witch_spawn_gibs"
					origin = Vector( 0, -5.96046e-007, 20 )
				}
			}
			tombstone_witch_spawn_gibs1 = 
			{
				SpawnInfo =
				{
					classname = "env_shooter"
					angles = Vector( -90, 180, 0 )
					delay = "0"
					disablereceiveshadows = "0"
					disableX360 = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					gibangles = "0 0 0"
					gibanglevelocity = "0"
					gibgravityscale = "1"
					m_flGibLife = "4"
					m_flVariance = "0.15"
					m_flVelocity = "400"
					m_iGibs = "1"
					massoverride = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					nogibshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shootmodel = "models/infected/limbs/common_infected_w_l_leg_lower_gib.mdl"
					shootsounds = "-1"
					simulation = "2"
					skin = "0"
					spawnflags = "4"
					targetname = "tombstone_witch_spawn_gibs"
					origin = Vector( 12, -1.66893e-006, 20 )
				}
			}
			tombstone_witch_spawn_gibs2 = 
			{
				SpawnInfo =
				{
					classname = "env_shooter"
					angles = Vector( -90, 92, 0 )
					delay = "0"
					disablereceiveshadows = "0"
					disableX360 = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					gibangles = "0 0 0"
					gibanglevelocity = "0"
					gibgravityscale = "1"
					m_flGibLife = "4"
					m_flVariance = "0.15"
					m_flVelocity = "350"
					m_iGibs = "1"
					massoverride = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					nogibshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shootmodel = "models/infected/limbs/common_infected_w_l_leg_upper_gib.mdl"
					shootsounds = "-1"
					simulation = "2"
					skin = "0"
					spawnflags = "4"
					targetname = "tombstone_witch_spawn_gibs"
					origin = Vector( -4, -16, 20 )
				}
			}
			tombstone_witch_spawn_gibs3 = 
			{
				SpawnInfo =
				{
					classname = "env_shooter"
					angles = Vector( -90, 271, 0 )
					delay = "0"
					disablereceiveshadows = "0"
					disableX360 = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					gibangles = "0 0 0"
					gibanglevelocity = "0"
					gibgravityscale = "1"
					m_flGibLife = "4"
					m_flVariance = "0.15"
					m_flVelocity = "330"
					m_iGibs = "1"
					massoverride = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					nogibshadows = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					shootmodel = "models/infected/limbs/common_infected_w_l_arm_lower_gib.mdl"
					shootsounds = "-1"
					simulation = "2"
					skin = "0"
					spawnflags = "4"
					targetname = "tombstone_witch_spawn_gibs"
					origin = Vector( 0, 16, 20 )
				}
			}
			tombstone_witch_mover = 
			{
				SpawnInfo =
				{
					classname = "func_door"
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					dmg = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forceclosed = "0"
					health = "0"
					ignoredebris = "0"
					lip = "-8"
					locked_sentence = "0"
					loopmovesound = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					movedir = "90 0 0"
					origin = Vector( -12, 0, 34.45 )
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					spawnflags = "44"
					spawnpos = "0"
					speed = "20"
					targetname = "tombstone_witch_mover"
					unlocked_sentence = "0"
					wait = "4"
					connections =
					{
						OnFullyClosed =
						{
							cmd1 = "tombstone_shakeStopShake0-1"
							cmd2 = "tombstone_witch_emerge_particlesStop11"
							cmd3 = "tombstone_filterKill0-1"
							cmd4 = "tombstone_style_1_basemodelClearParent0.1-1"
							cmd5 = "tombstone_witch_modelTurnOff0.2-1"
							cmd6 = "tombstone_witch_modelTurnOn0.1-1"
							cmd7 = "tombstone_witch_modelStartGlowing0.11"
							cmd8 = "tombstone_witch_alert_timerEnable0.11"
						}
						OnClose =
						{
							cmd1 = "tombstone_shakeStartShake0-1"
							cmd2 = "tombstone_witch_emerge_particlesStart0-1"
						}
					}
				}
			}
			tombstone_shake = 
			{
				SpawnInfo =
				{
					classname = "env_shake"
					amplitude = "4"
					duration = "6"
					frequency = "100"
					radius = "524"
					spawnflags = "0"
					targetname = "tombstone_shake"
					origin = Vector( 11.7192, 0.632152, 10.153 )
				}
			}
			tombstone_witch_spawn_particles1 = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( -90, 90, 0 )
					effect_name = "weapon_pipebomb_dirt_child_01"
					targetname = "tombstone_witch_spawn_particles"
					origin = Vector( 1, -5.96046e-007, 10 )
				}
			}
			tombstone_witch_emerge_particles = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( -90, 90, 0 )
					effect_name = "apc_wheel_smoke2"
					targetname = "tombstone_witch_emerge_particles"
					origin = Vector( 4, 1.78814e-006, 8 )
				}
			}
			tombstone_filter = 
			{
				SpawnInfo =
				{
					classname = "filter_activator_name"
					filtername = "null"
					Negated = "Allow entities that match criteria"
					targetname = "tombstone_filter"
					origin = Vector( -11.6817, 13, 41.5882 )
				}
			}
			tombstone_style_1_lid = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 0, 180, 0 )
					disablereceiveshadows = "0"
					disableshadows = "1"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "136 0 0 10"
					glowstate = "0"
					health = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/props_placeable/witch_hatch_lid.mdl"
					parentname = "tombstone_witch_hatch_mover"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					targetname = "tombstone_style_1_lid"
					updatechildren = "0"
					origin = Vector( 0, 3.8147e-006, 0 )
				}
			}
			tombstone_witch_hatch_mover = 
			{
				SpawnInfo =
				{
					classname = "func_door_rotating"
					always_fire_blocked_outputs = "0"
					angles = Vector( 0, 0, 0 )
					disablereceiveshadows = "0"
					disableshadows = "0"
					disableX360 = "0"
					distance = "6"
					dmg = "0"
					fademaxdist = "0"
					fademindist = "-1"
					fadescale = "1"
					forceclosed = "0"
					health = "0"
					ignoredebris = "0"
					lip = "0"
					locked_sentence = "0"
					loopmovesound = "0"
					maxcpulevel = "0"
					maxgpulevel = "0"
					mincpulevel = "0"
					mingpulevel = "0"
					origin = Vector( 9, 0, 2 )
					parentname = "tombstone_witch_mover"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					solidbsp = "0"
					spawnflags = "188"
					spawnpos = "0"
					speed = "100"
					targetname = "tombstone_witch_hatch_mover"
					unlocked_sentence = "0"
					wait = "4"
					connections =
					{
						OnFullyOpen =
						{
							cmd1 = "!selfClose0-1"
						}
						OnOpen =
						{
							cmd1 = "tombstone_hatch_dustStart0-1"
							cmd2 = "tombstone_hatch_dustStop1.5-1"
							cmd3 = "tombstone_hatch_pound_soundPlaySound0-1"
						}
					}
				}
			}
			tombstone_hatch_timer = 
			{
				SpawnInfo =
				{
					classname = "logic_timer"
					LowerRandomBound = "2"
					StartDisabled = "1"
					targetname = "tombstone_hatch_timer"
					UpperRandomBound = "5"
					UseRandomTime = "1"
					origin = Vector( -10.0057, 2.2902, 25 )
					connections =
					{
						OnTimer =
						{
							cmd1 = "tombstone_witch_hatch_moverOpen0-1"
						}
					}
				}
			}
			tombstone_hatch_dust = 
			{
				SpawnInfo =
				{
					classname = "info_particle_system"
					angles = Vector( 0, 0, 0 )
					effect_name = "impact_dirt"
					targetname = "tombstone_hatch_dust"
					origin = Vector( -4, 0, 2.88629 )
				}
			}
			tombstone_hatch_pound_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "Doors.Wood.Pound1"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "0"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "tombstone_hatch_pound_sound"
					volstart = "0"
					origin = Vector( 2, -1, 3.14199 )
				}
			}
			tombstone_hatch_break_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					cspinup = "0"
					fadeinsecs = "0"
					fadeoutsecs = "0"
					health = "10"
					lfomodpitch = "0"
					lfomodvol = "0"
					lforate = "0"
					lfotype = "0"
					message = "WoodenDoor.Break"
					pitch = "100"
					pitchstart = "100"
					preset = "0"
					radius = "0"
					spawnflags = "48"
					spindown = "0"
					spinup = "0"
					targetname = "tombstone_hatch_break_sound"
					volstart = "0"
					origin = Vector( 2, -1, 14.142 )
				}
			}
			tombstone_witch_model = 
			{
				SpawnInfo =
				{
					classname = "prop_dynamic_override"
					angles = Vector( 0, 0, 0 )
					DefaultAnim = "Idle_Sitting"
					disablereceiveshadows = "0"
					disableshadows = "1"
					fademindist = "-1"
					fadescale = "1"
					glowbackfacemult = "1.0"
					glowcolor = "136 0 0 10"
					glowrange = "0"
					glowrangemin = "600"
					glowstate = "3"
					health = "0"
					LagCompensate = "0"
					MaxAnimTime = "10"
					MinAnimTime = "5"
					model = "models/infected/witch.mdl"
					parentname = "tombstone_witch_mover"
					RandomAnimation = "0"
					renderamt = "255"
					rendercolor = "255 255 255"
					renderfx = "0"
					rendermode = "0"
					SetBodyGroup = "0"
					skin = "0"
					solid = "0"
					spawnflags = "0"
					targetname = "tombstone_witch_model"
					updatechildren = "0"
					origin = Vector( 4.75056e-021, 2.14577e-006, 0 )
				}
			}
			tombstone_witch_alert_sound = 
			{
				SpawnInfo =
				{
					classname = "ambient_generic"
					health = "10"
					message = "WitchZombie.Despair"
					pitch = "100"
					pitchstart = "100"
					radius = "1250"
					spawnflags = "48"
					targetname = "tombstone_witch_alert_sound"
					origin = Vector( 13, 2, 31 )
				}
			}
			tombstone_witch_alert_timer = 
			{
				SpawnInfo =
				{
					classname = "logic_timer"
					LowerRandomBound = "5"
					StartDisabled = "1"
					targetname = "tombstone_witch_alert_timer"
					UpperRandomBound = "15"
					UseRandomTime = "1"
					origin = Vector( 11, 2.2902, 47 )
					connections =
					{
						OnTimer =
						{
							cmd1 = "tombstone_witch_alert_soundPlaySound0-1"
						}
					}
				}
			}
		} // SpawnTables
	} // EntityGroup
} // WitchTombstone

RegisterEntityGroup( "WitchTombstone", WitchTombstone )
